### ISSUE TITLE
Audio Filter Geeting stuck on previous choice

### ISSUE THREAD

**Issue by wangkesen** [wireapp/wire-ios#1002]
Not sure if your aware of this bug, I'm running the most current Beta so perhaps it's just with the Beta. But whenever I apply a voice filter, after pressing the first filter and then switching to a new one, instead of using the newly selected filter when I sent the voice recording, it stays stuck on the one I've selected before. It's also a repeat issue. Happens every time . Anyways heads up and sorry I'm new at Girhub so if I mess anything up please let me know.

**Comment by jenskasemets** [comment]
Hi @wangkesen,

Thank you for reporting this issue, we'll investigate the cause for it and try to fix it.

**Comment by wangkesen** [comment]
Thanks! :)
