### ISSUE TITLE
Input Bar is not vertivally centered

### ISSUE THREAD

**Issue by niko-h** [wireapp/wire-ios#1003]
In iOS, 4" iPhones, the InputBar (Cursor and entered Text) is not vertically centered with Emoticons- and Time-Buttons, when the Keyboard is open. (With Keyboard closed it is okay.)

**Comment by jenskasemets** [comment]
Hi @niko-h,

Could you please include also a screenshot about this issue.

**Comment by niko-h** [comment]
![](https://files.slack.com/files-pri/T0FJYAGUV-F59HT51L1/image_uploaded_from_ios.jpg)

**Comment by niko-h** [comment]
[Screenshot](https://slack-files.com/T0FJYAGUV-F59HT51L1-1fb7829c74)

**Comment by jenskasemets** [comment]
Thank you. 
Looks like you have dynamic type enabled and you are using small font size for iOS?

**Comment by niko-h** [comment]
That's true. Sorry, I forgot.
