### ISSUE TITLE
Call disconnected when phone is locked

### ISSUE THREAD

**Issue by tnguyen14** [wireapp/wire-ios#1069]
While in a call, if I lock the phone, the call gets disconnected.

Was wondering if anyone has had this issue?

**Comment by mikeger** [comment]
Hey @tnguyen14 ! Thanks for reaching out to us. To help you I would need to understand the problem better. You are having call using CallKit i.e. iOS integrated calling screens? Or you are having a call inside the Wire app?

**Comment by tnguyen14** [comment]
Hi @mikeger it is when having a call inside the Wire app.

/cc @duytin90

**Comment by KoalaBoomka** [comment]
hi @tnguyen14, 
if you have iOS 10, this is an expected behaviour of the platform. If you do the same with a GSM call, it will be also interrupted.
What iOS version do you have?

**Comment by tnguyen14** [comment]
Oh wow. This is rather shocking to me. Thanks for letting me know.
