### ISSUE TITLE
Port iOS app to W10M

### ISSUE THREAD

**Issue by selfus** [wireapp/wire-ios#1080]
Hello,

I am wondering if there are plans or work done to port the iOS app to a UWP app.

If so, is there an ETA?

**Comment by mikeger** [comment]
Hey @selfus ! Thanks for reaching out to us. From my understanding, the issue that you indicated is not relevant to iOS app, so I would kindly ask you to redirect your question to the general wire repo at https://github.com/wireapp/wire/issues .
