### ISSUE TITLE
Media does not arrive on desktop app, especially videos

### ISSUE THREAD

**Issue by MadEgg** [wireapp/wire-ios#1092]
Especially when the sender has a poor internet connection, it seems that there are issues with media being delivered to my desktop app. Usually, after a long wait and a loading screen on my phone the media does show up there, but my desktop Wire client doesn't show any incoming media at all. Not even the loading sign.

**Comment by mikeger** [comment]
Hey @MadEgg ! Thanks for reporting the issue, please cross-post it to the desktop app bug tracker here https://github.com/wireapp/wire-desktop/issues

**Comment by MadEgg** [comment]
You're right, that would've been a better fit, I suppose. As the sender is using iOS, I am leaving it up to you if this issue can be closed. Feel free to close it if if you feel the issue at https://github.com/wireapp/wire-desktop/issues/744 is better suited to cover this.

**Comment by mikeger** [comment]
All right, thanks!
