### ISSUE TITLE
Music via Share Extension Missing URL Preview

### ISSUE THREAD

**Issue by wangkesen** [wireapp/wire-ios#1102]
![URL Preview for Apple Music Songs](http://i.imgur.com/KSZRQ06.jpg)

Wire loads most URL Previews similar with iMessage but it’s currently missing Previews for music files from Apple Music and when shared displays two identical links and no preview.

Top is song shared through Share Extension to iMessage, bottom shared to Wire.

**Comment by wangkesen** [comment]
Sorry about not labeling, API didn’t carry over the label apparently.

**Comment by mikeger** [comment]
Hey @wangkesen , thanks for reporting. We'll check if the website provides the proper headers that we can use to generate the link preview.

**Comment by wangkesen** [comment]
Sounds good:) Thank you

**Comment by daehn** [comment]
Hello @wangkesen, I verified that the behaviour you are observing is indeed a bug in our share extension implementation. Copying an iTunes link and sending it though the main app should work as expected (fetch the link preview information) until we fixed this issue.

**Comment by wangkesen** [comment]
Awesome! Thanks guys !
