### ISSUE TITLE
Is so much file compression needed?

### ISSUE THREAD

**Issue by wangkesen** [wireapp/wire-ios#1103]
I’m not exactly sure if the compression methods used for Wire, but just for example. ![Original Image](http://i.imgur.com/hka6jfp.jpg) is sized at 1.5MB, when sent on Wire, [Resulting Image](http://i.imgur.com/D4mjBex.jpg) is now only 88KB and of obvious reduced quality. I get that images have to be compressed but what’s the standard for compression on Wire when compressing image files? I thought the cap was 15mb, correct? Also with video files the loss in quality is extremely noticeable. I understand the priority is privacy and security I’m just wondering if there are certain files which will compress more or are we able to select original vs compressed quality, or just really if there is a 15mb size cap for files is this for all files? Or images have a lower maximum size. Thanks !

**Comment by mikeger** [comment]
Hey @wangkesen , thanks for your opinion. The current implementation could be suboptimal for your use case. I would suggest to upload images or videos as files, then Wire would not compress them. 

The current logic is coming from 2 main points:
1. Wire download the images immediately when it gets posted.
2. Wire should work well on low bandwidth networks.

I think fair change would be to be able to configure the video quality and give an option to send images as files (so they are not being auto-downloaded).

**Comment by mikeger** [comment]
Related to https://github.com/wireapp/wire-ios/issues/349

**Comment by wangkesen** [comment]
That would be good too!! Or just have an send as original option, either would work. This is just a minor issue obviously anyways. Thanks yo!

**Comment by cardassian-tailor** [comment]
Yes i too have issues with the images being so far compressed that they are unusable. The option to choose the compression type/amount would be very helpful.
