### ISSUE TITLE
Asian Script for Name messed up

### ISSUE THREAD

**Issue by wangkesen** [wireapp/wire-ios#1112]
I actually reported this within app as well but entering Chinese/Japanese is really messed up but I’m not sure if it’s due to IOS 11 dev beta but not happening in any other apps. The problem is with Pinyin Input / Roman for Japanese . Like for example 學校 you’d type xuexiao If using pinyin keyboard. Normally this would just then display 學校 but in wire currently under name entry it will show like 學xue校xiao and then upon backspacing this it will be okay, but only for two characters. If you use three or more it will only display the first two entered then the next entry will be just the pinyin and won’t convert into characters. I’ll post a video as reference. Thanks

**Comment by mikeger** [comment]
Hey @wangkesen , thanks for reporting the issue. I must admit that Wire team is still missing people knowing some (otherwise widely used) languages, so reporting this kind of issues is really important for us.
We would look into fixing the issue. Can you give some walkthrough on how to configure the device to use Pinyin keyboard? Should one just add the Japanese keyboard with input type `Pinyin` ?

**Comment by mikeger** [comment]
One more question @wangkesen , is the issue happening when you type the message, or in the name field when you set your name? Would be great to have a screenshot or video. Thanks in advance!

**Comment by wangkesen** [comment]
So basically like Japanese there’s two entry methods on Apples JP keyboard: 10 key and Romanji which the first being Japanese 10 character input and then the second being just the same keyboard entering using the English letters.  For Chinese, there’s more keyboard but it’s occurring with the equivalent of Romanji which is Pinyin.

So as your typing in Pinyin say the words will convert into the Chinese character as you type, the English script will input [Wherever your typing as seen in the picture notice the “z”](http://i.imgur.com/5fcMhWZ.jpg) and the characters will display right directly above the keyboard this is how it should work. The characters will convert as you type from Roman alphabet to JP/CN.

So what’s happening with Wire and interestingly enough this hasn’t happened before but the first two characters are remembered. So regardless if I write more it’s for example 王先生 It would forget that 王 and only remember the 先生 part and display it as your username.

The other issue is that Wire is only converting the first or first two character properly, after that Or if you make a mistake along the way the input that Wire is accepting is not being accepted as Chinese but it sssms as English so you’ll end up getting something  along the lines of 王xiabnnn先 and backspace doesn’t work actually you need to select and backspace or cut the text out. I’ll attach a video now I meant to earlier but I was really busy these days and forgot but basically yeah I’m sure it’s some issue just with the conversation

**Comment by wangkesen** [comment]
Demo! [Wire CN-TW🀄️](https://youtu.be/R0X-OKyBV4g)

**Comment by mikeger** [comment]
Thanks @wangkesen , we'll look into it. Can you confirm that the issue also occurs on iOS10 ?

**Comment by wangkesen** [comment]
I’m pretty sure it’s just iOS 11, but there have been a few updates with Wire since so I’m not exactly sure but one would think this issue would replicate on other apps and I haven’t seen that happen tho. I don’t think this issue is present in iOS 10 that being said it’s still beta 2 right so I can check again when the 3rd is released as well just to double check. It’s just with the name entry field not for input in typing so it’s not a huge deal

**Comment by wangkesen** [comment]
@Mikeger sorry codehub doesn’t show the names after pressing the at symbol so I forget to tag lol

**Comment by wangkesen** [comment]
Hey! This issue has been corrected on Beta 3! It’s storing more then 2 characters and entry via keyboard is no longer producing the same issue. So if it’s okay I’ll go ahead and close this issue.

**Comment by mikeger** [comment]
Thanks @wangkesen !
