### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by mergesort** [wireapp/wire-ios#1125]
I’ve recently started using Wire on the iPad a lot more, and really wish that it had better keyboard shortcut support. Ideally there would be shortcuts for navigation, but even the ability to send a message with `⌘ + enter` would be a good enough start.

Thanks a lot!

**Comment by mikeger** [comment]
Hey @mergesort , thanks for the request, this sounds perfectly valid, we'll prioritize the request. You can help us a lot if you would spend time defining the shortcuts, i.e. checking with other apps for the common key combinations to switch between conversations and other actions. Thanks a lot!

**Comment by richpersaud** [comment]
Input focus should also be moved.  Currently, if you alt-tab or otherwise switch to Wire, a screen touch is needed to move input focus to the new message field.  It should be possible to type immediately after switching to the app.

**Comment by mikeger** [comment]
@richpersaud can the focus be moved in Wire with tab? I have only experience with Android tablet where all the apps are allowing to be navigated with tab.

**Comment by mikeger** [comment]
Thanks to @daehn we would have `⌘ + enter` sending in the 2.40 release.

**Comment by daehn** [comment]
I think another shortcut which would be nice to have (and which we already have on desktop) is ↑ to start editing the last sent message.

**Comment by mikeger** [comment]
Correction: it would go into 2.41, 2.40 was a hotfix.
