### ISSUE TITLE
Group video calling

### ISSUE THREAD

**Issue by feimgrk** [wireapp/wire-ios#1130]
I see that you are working on paid plans (teams) and you have announced that group video calls will be implemented. Been waiting for this since beginning of 2016 so I'm really happy you are implementing this.
I was wondering whether group video calls will be available for free users as well or if it will be exclusively for team users?

**Comment by mat1th** [comment]
See https://github.com/wireapp/wire-ios/issues/529 for the same issue with a answer from the Wire team.

**Comment by mikeger** [comment]
Hey @feimgrk , thanks for reaching out, the issue is already tracked, going forward I would advise to post the issues that are affecting not only the iOS client but the whole platform to https://github.com/wireapp/wire/issues
