### ISSUE TITLE
Using a new device myself should be handled differently than when others do that

### ISSUE THREAD

**Issue by EgbertW** [wireapp/wire-ios#1132]
I recently was on a computer that I don't normally use and used app.wire.com to connect to my account in the browser.

Wire on my iPhone then proceeds to show me a warning that 'MadEgg started using a new device' when I try to send a message. While I get the general idea behind this notification, it should be handled separately when it's your own account, in my opinion.

As soon as you start using a new device Wire should, IMO, pop up a screen to notify me on other devices, with the option to validate the key right away. I don't think it should wait until I'm trying to send a message: it is more annoying because at that moment I am not focused on that, and it is also less secure because if someone manages to log into my account without me approving, that means that my credentials have been compromised so I would want to know this as soon as possible.

**Comment by mikeger** [comment]
Hey @MadEgg , thanks for the suggestion, we have the device popup if you open profile / settings, but I agree that having it whenever the app sees that you have the second device is a better solution. At the moment we have a plan to handle the issue on the higher level, so please stay tuned.

As always, I would suggest to post the issue that require the changes in all clients to the general-level wire issue tracker at https://github.com/wireapp/wire/issues .

**Comment by MadEgg** [comment]
Good to hear!

I don't know how this situation is handled in different clients - I've only experienced this on the iOS client. My desktop app didn't complain at all about a new device being used, so that's why I reported it here.
