### ISSUE TITLE
Podfile.lock is ignored

### ISSUE THREAD

**Issue by a2** [wireapp/wire-ios#118]
According to [this CocoaPods guide](https://guides.cocoapods.org/using/using-cocoapods.html#what-is-podfilelock), one should not ignore and also commit the `Podfile.lock` file.

[![](http://img.youtube.com/vi/H-zK1mEwTe0/0.jpg)](https://www.youtube.com/watch?v=H-zK1mEwTe0)

**Comment by marcoconti83** [comment]
Hi @a2 , thanks for your suggestion. 
We will evaluate it and post here the conclusions.

**Comment by marcoconti83** [comment]
@a2 we added the Podfile with #140, closing the issue. Thanks for the suggestion!
