### ISSUE TITLE
"New message" notification received without new messages.

### ISSUE THREAD

**Issue by NfNitLoop** [wireapp/wire-ios#1198]
Often, I'll receive "New message" notifications, but when I open the notification, there are no new messages. It's extremely annoying -- it's like the app is constantly "crying wolf" for attention.

Sometimes the messages are alone:

![img_7847](https://user-images.githubusercontent.com/339075/29486254-076b521a-84d1-11e7-8321-3ade51a8cfe8.PNG)

But sometimes they're just redundantly paired w/ another actual real message:

![wire 2017-08-19 at 9 56 47](https://user-images.githubusercontent.com/339075/29486260-18f75bd2-84d1-11e7-9cbe-812bf4318637.png)

**Comment by NfNitLoop** [comment]
This may be related to this other issue:
https://github.com/wireapp/wire-ios/issues/880

Jens's description over here seems relevant: https://github.com/wireapp/wire-ios/issues/662#issuecomment-281092234

Maybe these generic "New Message" notifications are getting sent because my device was temporarily offline and/or couldn't decrypt the first message in time? Why do you need to send a fallback notification though? If my device is offline, won't it just receive the encrypted push notification once it's back online?

**Comment by IpsmLorem** [comment]
It could be related to just https://github.com/wireapp/wire-ios/issues/1184 which is a message notification for a "like".
