### ISSUE TITLE
Remove the possibility to display an expired picture

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#1221]
When a timed picture expires, the sender still have the possibility to tap on it, to maximize it. 
It will leads to failed screen with a waiting icon. 

Why not just remove the possibility ?

**Comment by mikeger** [comment]
Hey @IpsmLorem ! Thanks for the suggestion, it seems completely valid. As @johnxnguyen is working on it now, it is possibly going to be fixed in the next release.

**Comment by mikeger** [comment]
Fixed in https://github.com/wireapp/wire-ios/pull/1223
