### ISSUE TITLE
No voice in video chat

### ISSUE THREAD

**Issue by EgbertW** [wireapp/wire-ios#1233]
On several occasions I tried to use Wire video chat to have a conversation from my iPhone to another iPhone. Unfortunately, on each of these occassions, voice was only one way. Sometimes I wouldn't hear anything and the other party would hear me, and sometimes the other way around. So far I've never been able to have a successful video chat using Wire and had to fall back to using Facetime instead.

This was between my iPhone 5S and either a iPhone 6 or a iPhone 6 Plus.

**Comment by mikeger** [comment]
Hey @EgbertW , thanks for reporting the issue. Which version of the app you are using?

**Comment by EgbertW** [comment]
Always the latest that the App Store offers me ;-) Currently 2.41 (2874)

**Comment by mikeger** [comment]
Hey @EgbertW ! I discovered this old issue, I think it is fixed now, can you confirm?
