### ISSUE TITLE
WireApp - iOS crashes on iOS 10.3.3 (iTunes download)

### ISSUE THREAD

**Issue by Fuzzylr** [wireapp/wire-ios#1250]
Greetings,

I Searched for this issue before posting and I didn't see it mentioned.  So I appologize if this is the wrong spot.

Issue:
Wire crashes on certain iOS devices for users who have never used the application before.  The results have been mixed so I will try to document them as much as possible for you.

iPhone (iOS 10.3.3) - Crashed / refused to connect.  After multiple attempts to get connected the application bricked the iPhone and she had to go to Apple to get her phone reloaded.

iPad Pro (iOS 10.3.3) - Installed application from iTunes and it refuses to connect.  Removed and installed several times.

iPhone 6 Plus (iOS 10.3.3) - No issues.

Is there a way we might be able to do something to get more logging so we can provide it to you so you could help us resolve this issue?

P.S.
Love the application so far.  Thank you for all your hard work.

**Comment by mikeger** [comment]
Hey @Fuzzylr , thanks for reporting the issues. I would need you to answer some questions in order to help with the issues you are facing.

1. Which iPhone model you are referring to in the first case?
2. iPad Pro: the app refuses to connect in the way that it shows the error during login I suppose. Can you provide the error that the application is displaying?

**Comment by Fuzzylr** [comment]
The model of iPhone's are iPhone 6 and iPhone 7.  The young lady who has the iPhone 7 is taking it to Apple.  Apparently it's having issues installing applications.

Also, this might be a false report of a bug.  The iPad user sent the device back to Apple when he was not able to install any Applications at all.  

I am still following up the folks in my group.  I will continue to update this post.

**Comment by Fuzzylr** [comment]
Both the phone user and iPad Pro users sent their devices to Apple.  I've not heard anyting back yet.  Two Andriod users and 1 Apple user so far are fine.

**Comment by mikeger** [comment]
Thanks @Fuzzylr !
