### ISSUE TITLE
Emoji no longer available

### ISSUE THREAD

**Issue by rbieb** [wireapp/wire-ios#1258]
Ever since the update that brought markdown support, emoji are no longer available. The markdown button has replaced the emoji button and therefore I can no longer send any emoji.

I get markdown is a nice feature to have, but who ever decided that it was more important than emoji (on a mobile device!) did obviously not think this through.

**Comment by johnxnguyen** [comment]
Hi @rbieb, you can still access emojis from the keyboard. You need to make sure that you have the emoji keyboard enabled in the iPhone's system settings under **General > Keyboard > Keyboards > Add New Keyboard > Emoji**. Then you can access the emoji keyboard by selecting it with the button immediately left of the space bar.

**Comment by mat1th** [comment]
There is a native emoij iOS keyboard. You can use that one. See https://support.apple.com/en-us/HT202332
