### ISSUE TITLE
iOS Sharing without Internet access

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#1266]
When iOS sharing to Wire without Internet access an endless  wating occur.
It would be better to just store it for sending in Wire as soon as the network is up again without wait.
![img_7807](https://user-images.githubusercontent.com/1250795/30524197-5328fede-9bef-11e7-9f4b-94c8e80de811.PNG)

**Comment by mikeger** [comment]
Hey @IpsmLorem ! Thanks, as usual very useful bug report, we'll consider fixing it.
