### ISSUE TITLE
Check\ Pods\ Manifest.lock

### ISSUE THREAD

**Issue by MarvensBastien** [wireapp/wire-ios#1272]
diff: /Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

**Comment by mikeger** [comment]
Hey @MarvensBastien ! Thanks for the bug report. Please check your cocoapods version (by running in your terminal `pod--version`, we recently switched to 1.3.1. You can update to most recent cocoapods by running `sudo gem install cocoapods`.
