### ISSUE TITLE
Start up time is slow on linux

### ISSUE THREAD

**Issue by michalpirchala** [wireapp/wire-ios#1276]
I use wire on Linux laptop and on Android phone. On Linux, it takes VERY long time to synchronize messages, maybe 10-15 minutes sometimes, I think it depends on number of messages to sync. On Android it is much faster.

**Comment by mikeger** [comment]
Hey @michalpirchala ! Thanks for the bug report. This repo (`wire-ios`) is dedicated for the issues on the iOS client (for iPhone and iPad). Please re-post your issue to the desktop client issues ( https://github.com/wireapp/wire-desktop/issues ).
