### ISSUE TITLE
Some many issues

### ISSUE THREAD

**Issue by MarvensBastien** [wireapp/wire-ios#1277]
![screen shot 2017-09-22 at 3 28 40 am](https://user-images.githubusercontent.com/32110004/30734948-45fe28d8-9f4b-11e7-8a6b-a68b0062a0da.png)

I need some serious help here!!

**Comment by mikeger** [comment]
Hey @MarvensBastien ! Thanks for the report. Please consider running the `./setup.sh` script to install the dependencies. Alternatively you can run `pod install` and `carthage bootstrap` in the root of the checkout directory. You can read about it in detail here https://github.com/wireapp/wire-ios#how-to-build-the-open-source-client
