### ISSUE TITLE
Sketch gets stretched upon device orientation.

### ISSUE THREAD

**Issue by regexident** [wireapp/wire-ios#13]
Rotating the iPad while sketching causes the sketch to be stretched (from portrait to landscape or vice versa).

The bug can easily be reproduced by:
1. Putting iPad into portrait orientation.
2. Opening a sketch.
3. Drawing a vertical as well as a horizontal line with the largest brush available.
4. Rotating the device to landscape orientation.
5. Observing how the vertical line gets widened, compared to the horizontal one.

(Starting the other way round in horizontal orientation yields similar erroneous results.)

A simple fix would be to have the SmoothLineView issue a redraw upon device rotation, correcting the stretch.

---

Drawing another line after rotation triggers a redraw (as expected), which causes the initial drawing to un-stretch and jump.

I would disable rotation entirely while drawing (locking orientation to the one in which the sketch was started, thus allowing for both landscape and portrait sketches, while eliminating the glitches).

**Comment by regexident** [comment]
Further inspection showed that drawing another line after rotation triggers a redraw (as expected), which causes the initial drawing to un-stretch and jump.

I would disable rotation entirely while drawing (locking orientation to the one in which the sketch was started, thus allowing for both landscape and portrait sketches, while eliminating the glitches).

**Comment by KoalaBoomka** [comment]
hi @regexident! Thanks for reporting the issue. We will verify and prioritize it.
