### ISSUE TITLE
Wire process killed due to locked system files

### ISSUE THREAD

**Issue by Siguza** [wireapp/wire-ios#1309]
I've been getting a lot of crash reports for Wire lately with reason `SIMULATED`.  
I just came across this in my syslog:

```
Sep 26 20:49:04 Cameo ReportCrash[19523] <Error>: Process:             Wire [19612]
	Path:                /var/containers/Bundle/Application/89E9A61A-2180-4D36-A444-9EAA974C2E03/Wire.app/Wire
	OS Version:          iOS 9.3.3 (13G34)
Sep 26 20:49:04 Cameo ReportCrash[19523] <Error>: Exception Type:  00000020
	Exception Codes: 0x00000000dead10cc
	Exception Note:  SIMULATED (this is NOT a crash)
	Highlighted by Thread:  4
Sep 26 20:49:04 Cameo ReportCrash[19523] <Error>: Application Specific Information:
	<FBApplicationProcess: 0x126c268e0; Wire; pid: 19612> was suspended with locked system files: 
	/var/mobile/Containers/Shared/AppGroup/49D3CC0E-6103-4C27-874A-C12D987AB47F/AccountData/0A77A3DA-4737-4D3D-B1C0-FFA68C2218D6/store/store.wiredatabase
```

The same shows up in a few crash logs, the majority of them reads this though:

```
Application Specific Information:
<BKNewProcess: 0x145e42800; com.wearezeta.zclient.ios; pid: 19430; hostpid: -1> has active assertions beyond permitted time: 
{(
    <BKProcessAssertion: 0x145d59f80> id: 17655-F7750D84-82D8-4424-8B1B-7B7FE7712A5E name: Background Content Fetching (25) process: <BKNewProcess: 0x145e42800; com.wearezeta.zclient.ios; pid: 19430; hostpid: -1> permittedBackgroundDuration: 30.000000 reason: backgroundContentFetching owner pid:17655 preventSuspend  preventThrottleDownUI  preventIdleSleep  preventSuspendOnSleep 
)}
```

**Comment by mikeger** [comment]
Hey @Siguza ! Thanks for the exceptional bug report, this is the information that we never get from Apple or our crash reporting system. This is most likely caused by Wire taking too much time to process the push notification [1]. Have you experienced the issue with missing pushes while using the app?

> The exception code 0xdead10cc indicates that an application has been terminated by the OS because it held on to a file lock or sqlite database lock during suspension. If your application is performing operations on a locked file or sqlite database at suspension time, it must request additional background execution time to complete those operations and relinquish the lock before suspending.

------------
[1] https://developer.apple.com/library/content/technotes/tn2151/_index.html

**Comment by Siguza** [comment]
"Missing pushes" as in "there are new messages when I open the app, but no notification was shown"? Yes, that happens sometimes. I found that an immediate way of reproducing such a crash/kill is killing Wire from the app switcher. It seems Wire is then relaunched and killed again a few times, producing additional logs (I suppose this ends in the OS deciding to just not restart it anymore at some point).

**Comment by Siguza** [comment]
iPhone SE (N69AP), iOS 9.3.3 (13G34), exactly 1 conversation.
