### ISSUE TITLE
Subtly jagged lines in sketching canvas.

### ISSUE THREAD

**Issue by regexident** [wireapp/wire-ios#14]
Slow or finely detailed drawing sometimes causes a sketch's line to look somewhat (yet rather subtly) jagged or even gapped (even more subtly).

This due to a bug in [`SmoothLineView`](https://github.com/wireapp/SmoothLineView) which leaves gaps for stroke events within the provided distance threshold.

I have submitted a fix for this to the [upstream repository](https://github.com/kompozer/SmoothLineView/pull/7). A simple downstream pull should fix the visual glitch.

**Comment by mikeger** [comment]
Hey @regexident! Thanks for the contribution. I've merged back changes from the upstream and included the new version in `develop` of `wire-ios`: https://github.com/wireapp/wire-ios/commit/558ab299d23232136e1d424db2a2f446ad1577fa

Please confirm if the issue is fixed

**Comment by regexident** [comment]
Fixed! 🎉
