### ISSUE TITLE
Wire is not in the Chinese App Store

### ISSUE THREAD

**Issue by kc1212** [wireapp/wire-ios#1400]
Hi, I was not able to find Wire in the Chinese App Store. Is there a particular reason for this?

**Comment by teller** [comment]
Thanks for the report. We checked with another person in China and they can find Wire in the AppStore.
![f8nvqitm jpg-large](https://user-images.githubusercontent.com/411583/32491574-7ca2bb2a-c3b7-11e7-98d2-27dcde31e3f1.jpeg)

**Comment by kc1212** [comment]
Sorry about that, I see it now. Not sure why I missed it earlier.

**Comment by GPX-NSlog** [comment]
I can't search for the wire in the app store in China. Is it a shelf in China?

**Comment by mikeger** [comment]
hey @GPX-NSlog , we are unable to release the app in China due to the government regulation that the CallKit must be disabled for the Chinese users. More on the topic: https://9to5mac.com/2018/05/19/apple-cracking-down-on-callkit-apps-in-china-app-store-due-to-government-regulation/
