### ISSUE TITLE
Fail to paste image from clipboard into text field

### ISSUE THREAD

**Issue by AndreaVEH** [wireapp/wire-ios#1485]
## Checklist (please check before submitting)

- [x]  I checked the existing issues, and the issue was not reported before.

## The problem

After copying an image elsewhere, I cannot paste the image into text field. There is no response after I tap the paste of edit menus. In Notes app, I can normally paste the image whether it is from local clipboard or universal clipboard. But in Wire, it always fails. No response when tapping paste option of edit menus from local clipboard. And when I want to invoke edit menus to paste from universal clipboard, Wire will not show edit menus, instead it will automatically show a panel displaying "Pasting from X's device" and fade away like nothing has happened. After that failure, I can invoke edit menus, but tapping paste option will have no response like pasting from local clipboard. 

But when if I cut the image into the local clipboard, then I can normally paste it into text field and send it to friends. 

And copying and pasting images works in other third-party apps. 

## Environment

* Wire version that exhibits the issue: **Version 3.2(2921)**
* Last Wire version that did not exhibit the issue (if applicable): **Version 3.1**
* iOS version used to run Wire: **iOS 11.1.2**
* iOS device type: **iPhone SE**
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): **Wi-Fi**
* Exact date, time and timezone (only for the crash issues): 

## Details

1. Copy an image elsewhere into clipboard(local clipboard when on the same iOS device or universal clipboard when on the other iOS or macOS device)
2. Open Wire then touch and hold or double-tap in a text field to invoke edit menus
3. From local clipboard paste option will appear and tap it, but nothing will happen. 
4. From universal clipboard paste option will not appear at first, instead a panel showing "Pasting from XXX" will appear and fade away automatically. After that, edit menus can be invoked, but nothing will happen after tapping paste option.
5. Cut an image from other app on the same device and can be able to paste into text field through tapping paste option of edit menus.

**Comment by AndreaVEH** [comment]
The problem still exists in iOS 11.2. And I find the problem only appears when copy item is an image. There is no problem if copying text via local clipboard or universal clipboard.

**Comment by AndreaVEH** [comment]
The problem still appears on Version 3.3(2934).

**Comment by mikeger** [comment]
Hey @AndreaVEH ! Thanks for reporting the issue, we'll look into it.

**Comment by AndreaVEH** [comment]
So does Version 3.4 (2941).

**Comment by AndreaVEH** [comment]
So does Version 3.5 (2945).

**Comment by AndreaVEH** [comment]
Hi @mikeger , in the Version 3.6 (2962), iOS 11.2.5, the problem still exists. 

1.  Copying from universal clipboard failed
2. Copying from other apps via the copy option of action sheets of **Save Photo** and **Copy** may succeed
3. Copying from other apps via the copy option of edit menus failed
4. Cutting from other apps via the cut option of edit menus may succeed

**Comment by mikeger** [comment]
Hey @AndreaVEH ! Thanks for the update, we have the issue on our radar, we'll prioritize it, may be someone from external contributors are going to pick it up.

**Comment by AndreaVEH** [comment]
Thank you for your hard works, @mikeger , @nicorsm . The problem has been solved.
