### ISSUE TITLE
When switching accounts the arrow in the send message bar stay's wrong color.

### ISSUE THREAD

**Issue by mat1th** [wireapp/wire-ios#1492]
## Checklist (please check before submitting)

* [x]  I checked the existing issues, and the issue was not reported before.

## The problem

I'm logged in with 2 accounts in the Wire app. The first one has a bleu accent color, the second one green. When I switch the account from bleu to green. All accent colours switching except the send button.

## Environment

* Wire version that exhibits the issue: 3.2 (2921)
* Last Wire version that did not exhibit the issue (if applicable): Unknown
* iOS version used to run Wire: iOS 11.2
* iOS device type: All
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): All
* Exact date, time and timezone (only for the crash issues): Not necessary

## Details

1. Log in to two accounts. (Account `Green` and `Bleu`)
2. Select Account `Green`. 
3. Kill the app in the app switcher.
4. Open the Wire app (it should open in the  `Green` account)
5. Send a message to a contact.
6. Switch to the other account. (So the `Bleu` account is now selected)
7. Open a chat. You see now that the send button is still `Green`. (It should be `bleu`. because the tint color of that account is `Bleu`.) 

## Calling Debug logs (only for calling issues)
It's not a calling issue.

## Screenshots

![test](https://user-images.githubusercontent.com/6486389/33516642-1bb9496c-d76e-11e7-88a2-f287cbc8ff97.jpeg)

**Comment by mikeger** [comment]
Hey @mat1th ! Thanks for reporting the issue!

**Comment by billypchan** [comment]
fixed
