### ISSUE TITLE
Rotating device can cause sketch to be sent with wrong orientation

### ISSUE THREAD

**Issue by regexident** [wireapp/wire-ios#15]
Given:
- A sketch in Wire on iPad.

When:
- One changes the device's orientation.
- One taps the "OK" (checkmark) button.

Then:
- The sketch may get sent with wrong orientation (depending on the artist's intentions, obviously).

---

The issue here is that the device orientation at time of sketch finalization does not necessarily have to be the desired orientation of the sketch. Especially on the iPad I find myself to rotate the device frequently when drawing. Just like one would do with a real sketch book & pencil.

Combined with [issue 13](https://github.com/wireapp/wire-ios/issues/13) I'd prefer SketchViewController to not allow for rotation at all. The view controller's initial orientation should be preserved and used for the final image.

**Comment by KoalaBoomka** [comment]
Hi @regexident! Thanks for getting in touch with us! 
We really appreciate your bug report and will verify, confirm and prioritize the issue you reported.

**Comment by KoalaBoomka** [comment]
Rotation sketch issue is solved.
