### ISSUE TITLE
Messages can not be displayed due to Wire app being outdated (while on the beta)

### ISSUE THREAD

**Issue by malicioustoker** [wireapp/wire-ios#1506]
I keep getting a message every now and then stating that the message could not be displayed because my Wire app is outdated. Im on the most current beta version - can’t get any more up to date than that. 

Running iOS 11.2

Happens on both Cellular and Wifi

**Comment by mikeger** [comment]
Hey @malicioustoker ! Thanks for reporting the issue. Do you know by any chance what is the action from the other side that makes the "cannot be displayed" message appear on your side?

**Comment by malicioustoker** [comment]
I’m actually not sure - but this can be closed. The issue seems to have been resolved in the latest TestFlight build. Version 3.3 (2934)
