### ISSUE TITLE
Skipped installing Marklight.framework binary due to the error

### ISSUE THREAD

**Issue by 353243186** [wireapp/wire-ios#1518]
Xcode 9.0.1
Dear supporters,
when I cloned the Wire repository and executed setup.sh
I get the following linker error:
ℹ️  Carthage bootstrap. This might take a while...
*** Downloading PureLayout.framework binary at "v3.0.0"
*** Downloading AFNetworking.framework binary at "2.6.3-iOS8"
*** Downloading ocmock.framework binary at "v3.4"
*** Downloading mixpanel-swift.framework binary at "v2.2.2"
*** Downloading wire-ios-message-strategy.framework binary at "67.0.0: toads really love eating basil"
*** Downloading wire-ios-utilities.framework binary at "18.1.0: It smells like a warlike bike"
*** Downloading Cartography.framework binary at "Swift 4.0"
*** Downloading wire-ios-canvas.framework binary at "5.0.1: Sharon Carter VS. Metal Men"
*** Downloading wire-ios-transport.framework binary at "30.0.2: Black-faced ibis"
*** Downloading avs-ios-binaries.framework binary at "Version 3.6.117"
*** Downloading wire-ios-share-engine.framework binary at "53.0.0: I'd like a unnatural cajun seasoning and pepperoni burger without quinoa, please"
*** Downloading ZipArchive.framework binary at "v2.0.8"
*** Downloading wire-ios-system.framework binary at "19.0.1: Dagan the upset blue slaad from Albstadt"
*** Downloading protobuf-objc.framework binary at "macOS"
*** Downloading wire-ios-images.framework binary at "12.0.1: The One with the Rockin' New Year"
*** Downloading wire-ios-protos.framework binary at "12.0.1: Please plant the same crow"
*** Downloading wire-ios-request-strategy.framework binary at "66.0.0: A giant frail water buffalo was spotted near Dessau-Roßlau"
*** Downloading ono.framework binary at "Swift 3.1"
*** Downloading wire-ios-ziphy.framework binary at "7.0.1: From Nanning to Papeete"
*** Downloading PINCache.framework binary at "Swift 3.1"
*** Downloading wire-ios-link-preview.framework binary at "6.0.2: The responsive grass roots clam"
*** Downloading HockeySDK-iOS.framework binary at "Swift 3.1"
*** Downloading FLAnimatedImage.framework binary at "1.0.12-wire"
*** Downloading libPhoneNumber-iOS.framework binary at "Swift 3.1"
*** Downloading ios-snapshot-test-case.framework binary at "Swift 4.0"
*** Downloading FormatterKit.framework binary at "Swift 3.0.2"
*** Downloading onepassword-app-extension.framework binary at "Swift 3.0.2"
*** Downloading Marklight.framework binary at "Wire Version 1 Beta 9"
*** Skipped installing Marklight.framework binary due to the error:
	"A shell task (/usr/bin/env unzip -uo -qq -d /var/folders/0h/34py2shj5m159czbyjgbk3340000gn/T/carthage-archive.SmJ7an /Users/user/Library/Caches/org.carthage.CarthageKit/binaries/Marklight/1.0.9/ID<Asset>(rawValue:\ 5140728)-Marklight.framework.zip) failed with exit code 9:
[/Users/user/Library/Caches/org.carthage.CarthageKit/binaries/Marklight/1.0.9/ID<Asset>(rawValue: 5140728)-Marklight.framework.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /Users/user/Library/Caches/org.carthage.CarthageKit/binaries/Marklight/1.0.9/ID<Asset>(rawValue: 5140728)-Marklight.framework.zip or
        /Users/user/Library/Caches/org.carthage.CarthageKit/binaries/Marklight/1.0.9/ID<Asset>(rawValue: 5140728)-Marklight.framework.zip.zip, and cannot find /Users/user/Library/Caches/org.carthage.CarthageKit/binaries/Marklight/1.0.9/ID<Asset>(rawValue: 5140728)-Marklight.framework.zip.ZIP, period.
"
*** Checking out Marklight at "1.0.9"
*** Downloading TTTAttributedLabel.framework binary at "Swift 3.0.2"
*** Downloading wire-ios-sync-engine.framework binary at "127.0.6: Kelbra"
*** Downloading Classy.framework binary at "Swift 3.0.2"
*** Downloading CocoaLumberjack.framework binary at "3.3.0"
*** Downloading wire-ios-cryptobox.framework binary at "11.0.1: You should never harm in Huai'an"
*** Downloading wire-ios-data-model.framework binary at "81.2.3: What would Monica S. Lam do?"
*** xcodebuild output can be found in /var/folders/0h/34py2shj5m159czbyjgbk3340000gn/T/carthage-xcodebuild.LbDd2G.log
*** Building scheme "Marklight" in Marklight Sample.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/user/Desktop/newWire/Carthage/Checkouts/Marklight/Sample/Marklight\ Sample.xcworkspace -scheme Marklight -configuration Release -derivedDataPath /Users/user/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0.1_9A1004/Marklight/1.0.9 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/0h/34py2shj5m159czbyjgbk3340000gn/T/Marklight SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO (launched in /Users/user/Desktop/newWire/Carthage/Checkouts/Marklight)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/0h/34py2shj5m159czbyjgbk3340000gn/T/carthage-xcodebuild.LbDd2G.log

Could you please explain to us what was wrong ?

Thanks!

**Comment by mikeger** [comment]
Hey @353243186 ! Thanks for reaching out to us. Please try to remove the `Carthage` directory and it's contents (it should reside in your checkout folder) and re-run `carthage bootstrap --platform ios`. I hope this would help!

**Comment by vytis** [comment]
Also worth removing Carthage caches from `/Users/user/Library/Caches/org.carthage.CarthageKit` and `/Users/user/Library/Caches/carthage`.

**Comment by 353243186** [comment]
Thanks a lot,I have solved the problem according to your guidance!
