### ISSUE TITLE
More of a question than an actual issue

### ISSUE THREAD

**Issue by malicioustoker** [wireapp/wire-ios#1527]
I wasn’t sure where to post this question, so I apologize in advance if this is the incorrect place to do so. What is the determining factor when pushing out the TestFlight betas? Personally - I wouldn’t mind weekly or even daily updates! I am extremely into what you guys stand for and would love more consistent updates to test for you guys - if at all possible. Thanks for your time!

**Comment by mikeger** [comment]
Hey @malicioustoker ! Thanks for the feedback. Our delivery process right now consists of the several stages, those are:
1. Actual development (usually happens on the feature branch).
2. First internal version for use inside Wire when the feature branch is merged to `develop`.
3. TF release before the RC (release candidate) is going to start.
4. RC approval and app store submit.

As you might see, you are right that we are pushing the TF build fairly late in the process. Certainly there is no issue into pushing the build more frequently for the external users to give it a try. We might try it with some features.

**Comment by malicioustoker** [comment]
@mikeger Thank you for taking time out of your busy schedule to answer my question - you guys truly are amazing!! Keep up the great work!!
