### ISSUE TITLE
Issue with audio and video calls

### ISSUE THREAD

**Issue by malicioustoker** [wireapp/wire-ios#1579]
I’m not sure if its just me, but whenever I attempt to call someone on Wire either using an audio or video call, it just keeps ringing and the recipients report that they never received a call on their end. I have tested this with multiple people, both on WiFi and Cellular and I have had the same response.

Running the most recent TestFlight version of Wire (3.5 | 2945) but I have also had this issue in previous versions of Wire.

Running iOS 11.2.5 beta 3, though it was also an issue in beta 2.

iPhone X

I have even tried to use the Public version and still have this issue. I have even tried with “Variable Bit Rate Encoding” on and off. 

Is there anything I can do on my end to try to fix this issue, or is it a known bug?

**Comment by malicioustoker** [comment]
Just attempted this on my iPad Pro as well running the same iOS version and Wire version as the iPhone X and had the same issue.

![6e99f3ff-ffec-498e-b1ee-b902215e02ad](https://user-images.githubusercontent.com/1431774/34623903-f3dd312e-f207-11e7-91c7-40f545222b81.jpeg)

**Comment by mikeger** [comment]
Hey @malicioustoker ! Thanks for reporting the issue, do you know by any chance the network conditions when it happened? Otherwise @jspittka would check from his side if anything can be done.

**Comment by malicioustoker** [comment]
@mikeger no network issues at all - everything else works just fine

**Comment by jspittka** [comment]
Do you use a firewall? All UDP ports have to be open for calling. Please also look at: https://support.wire.com/hc/en-us/articles/115005338109-What-domain-names-and-ports-does-Wire-connect-to-

**Comment by malicioustoker** [comment]
Seems to have been an iOS issue, resetting the Network Settings fixed the issue!
