### ISSUE TITLE
Spacing issue on iPhone X

### ISSUE THREAD

**Issue by malicioustoker** [wireapp/wire-ios#1582]
This issue occurs when you load a place within Wire that launches the in app browser. As you can see at the top, the text gets all squished up with the top sensor bar, the time, and the battery. ![GitHawk Upload by malicioustoker](https://i.imgur.com/Hger6x4.jpg)

You can’t see it in the photo, but on the iPhone X itself, where it says “Wire-Support” part of that gets cut off by the “notch”

**Comment by mikeger** [comment]
Thanks for the report, definitely something to fix on our side, @nicorsm something we can easily replace with `SFSafariViewController` ?

**Comment by nicorsm** [comment]
@mikeger I'll take a look.

**Comment by nicorsm** [comment]
Fix has been merged into `develop`.
