### ISSUE TITLE
Wire delete contact

### ISSUE THREAD

**Issue by cardassian-tailor** [wireapp/wire-ios#1584]
Please, Please, please create a way to actually disconnect from a user, delete them entirely.

**Comment by mikeger** [comment]
Hey @cardassian-tailor ! Thanks for the feature request. It might be worth it to request on the high level in https://github.com/wireapp/wire , since this looks like a feature for the whole platform. Just to check, you know that you can ignore a user and then delete the conversation with this user?

**Comment by cardassian-tailor** [comment]
Yes I have known about the ability to ignore a user and archive them. 

Is there any way to move this to the other channel/branch or should i close and reopen?

**Comment by 0ki** [comment]
I suggest closing this and reopening in wireapp/wire.

**Comment by cardassian-tailor** [comment]
closing to reopen as requested.
