### ISSUE TITLE
“Version Technical Details” bug

### ISSUE THREAD

**Issue by malicioustoker** [wireapp/wire-ios#1593]
Just reporting another bug (small one this time)

ºThe “Version Technical Details” button (Found in Settings / Advanced) on the iPad version it not tappable / doesn’t function at all.
It works just fine on the iPhone version, but on my iPad Pro, it is not tappable at all. Just thought I’d let y’all know!

**Comment by mikeger** [comment]
Hey @malicioustoker ! Thanks for the report, seems like an issue that is fairly easy to fix.

**Comment by malicioustoker** [comment]
Fixed in TestFlight version 3.7 (2966)
