### ISSUE TITLE
Flakey behavior when tilting/rotating the device while sketching.

### ISSUE THREAD

**Issue by regexident** [wireapp/wire-ios#16]
When run on an iPad the app currently behaves somewhat flakey when tilting/rotating the device while sketching.

Both device rotation as well as device tilt/yaw seem to trigger different behaviors:
- Rotation: entire SketchViewController rotates, leading to [bug #13](https://github.com/wireapp/wire-ios/issues/13).
- Tilt/yaw: only "checkmark" button and "help" label rotate (90º), leading to [bug #15](https://github.com/wireapp/wire-ios/issues/15).

The preferred behavior would probably be to not rotate at all (in either cases).

**Comment by KoalaBoomka** [comment]
Hi @regexident! I assume this bug is a duplicate for two other bugs mentioned in the description and close it.

**Comment by regexident** [comment]
Not so much a duplicate but more a meta-ticket. But yeah. :wink:
