### ISSUE TITLE
module compiled with Swift 4.0 cannot be imported in Swift 3.2.3

### ISSUE THREAD

**Issue by 353243186** [wireapp/wire-ios#1607]
Dear supporters:
when I updated XCode from 9.0.1 to 9.2,
I get the following  errors,this is one of them:
module compiled with Swift 4.0 cannot be imported in Swift 3.2.3: /Users/hexamon/Desktop/Wire-ios/Carthage/Build/iOS/WireDataModel.framework/Modules/WireDataModel.swiftmodule/x86_64.swiftmodule

**Comment by johnxnguyen** [comment]
Hey @353243186 ! Unfortunately we haven't yet migrated our frameworks to swift 4 yet (we are planning to do this soon) and as a result, 9.0.1 is currently the highest version of XCode that will compile the entire project "straight out of the box". As soon as we update the frameworks, you will be able to use XCode 9.2. Until then, I would suggest keeping an installation of 9.0.1.
