### ISSUE TITLE
Wire for iOS and Bluetooth headsets

### ISSUE THREAD

**Issue by TubaOrNotTuba** [wireapp/wire-ios#1633]
When Bluetooth earbuds/headsets are connected to an iOS device, in my case iPhone 7 Plus 256 on iOS 11.2.2, audio from video conversations continues to be forced through the phone's speakers rather than the appropriate channel, the connected Bluetooth headset/earbuds.

## Environment

* Wire version that exhibits the issue: 3.5 (2945)
* Last Wire version that did not exhibit the issue (if applicable): N/A
* iOS version used to run Wire: 11.2.2
* iOS device type: iPhone 7 Plus 256 Verizon
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): All
* Exact date, time and timezone (only for the crash issues): 

FYI, audio-only calls work fine and calls in WhatsApp, both audio & video, as well as video calls in FaceTime properly route audio through the connected Bluetooth device.

**Comment by mikeger** [comment]
Hey @TubaOrNotTuba ! Thanks for the bugreport. We'll look into this issue.

**Comment by malicioustoker** [comment]
I have this same issue with AirPods. I know y’all are already on it though!

**Comment by malicioustoker** [comment]
This appears to be fixed in in TestFlight version 3.7 (2966), but I will continue testing!

**Comment by mikeger** [comment]
You are right, it should be fixed in 3.7, I am going to close the ticket when 3.7 is officially out.
