### ISSUE TITLE
Slow detailed sketching falsely triggering canvas fill.

### ISSUE THREAD

**Issue by regexident** [wireapp/wire-ios#17]
Touching down with the Pencil in a slow manner (for the purpose of drawing a small detail) triggers the fill action. 9 out of 10 times one did not want to fill though.

This happens most notably with the Apple Pencil as one seldomly attempts to draw fine details with one's clumsy fingertips.

I would thus like to suggest a different gesture to be considered for canvas filling. Double tap maybe (with two fingers – just to be sure – even)?

**Comment by david-wire** [comment]
Hello, sorry for the delay in responding.

Thanks for highlighting this. We'll take your suggestion into consideration. We are always looking for ways to improve Wire, and we appreciate your taking the time to send us your comments.
