### ISSUE TITLE
Loading bar is not appropriate in iPhone X.

### ISSUE THREAD

**Issue by starkshaw** [wireapp/wire-ios#1713]
## Checklist (please check before submitting)

* [x] I checked the existing issues, and the issue was not reported before.

## The problem

The loading bar at the top of screen is not shown properly in iPhone X as its curved edge and notch.
It is a nice touch on Desktop application, but merely two thin lines on iPhone X. For people new to Wire but have not used it on other platforms, this is confusing.

## Environment

* Wire version that exhibits the issue: 3.7 (2966) along with all old versions
* Last Wire version that did not exhibit the issue (if applicable):
* iOS version used to run Wire: 11.3 beta 2
* iOS device type: iPhone X
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): All

## Details

When the app needs to load, this issue appears.

## Screenshots

It cannot be observed via screenshoots as the screenshoot from iPhone X is rectangular but screen edge is curved. It can be seen on real device or probably simulator.

**Comment by typfel** [comment]
Hi, thanks for the report!
We are aware of this issue and are actually almost finished with a new design of the loading bar. You can track the progress of it here https://github.com/wireapp/wire-ios/pull/1640

**Comment by starkshaw** [comment]
Hi @typfel 
Thank you for letting me know!

Close this case.
