### ISSUE TITLE
Dark theme is not available on iPad

### ISSUE THREAD

**Issue by jcredmond** [wireapp/wire-ios#1718]
## Checklist (please check before submitting)

* [x] I checked the existing issues, and the issue was not reported before.

## The problem

Dark theme is not available on iPad.

## Environment

* Wire version that exhibits the issue: all
* iOS version used to run Wire: all
* iOS device type: iPad

## Details

Is there any reason why the dark theme is not available on iPad? See [the code](https://github.com/wireapp/wire-ios/blob/4f81ebf7f6bbae999096f392be0e8e9b99448388/Wire-iOS/Sources/UserInterface/Settings/CellDescriptors/SettingsCellDescriptorFactory%2BOptions.swift#L169):

```swift
if UIDevice.current.userInterfaceIdiom != .pad {
    let darkThemeElement = SettingsPropertyToggleCellDescriptor(settingsProperty: settingsPropertyFactory.property(.darkMode))
    popularDemandDescriptors.insert(darkThemeElement, at: 0)
}
```

**Comment by malicioustoker** [comment]
I would love to see this!

**Comment by mikeger** [comment]
Hey, the iPad is following the desktop version logic with the theme to simplify the development. Unfortunately there are no plans to implement it right now.

**Comment by jcredmond** [comment]
I would like to ask you to reconsider this position. It seems like an artificially imposed limitation given that the code is shared between iPad and iPhone.

**Comment by jcredmond** [comment]
Now that the desktop supports dark mode, when can we expect it on iPad?

**Comment by jcredmond** [comment]
Can someone re-open this or should I file a new issue? Now that dark mode is available on all other platforms except iPad, and you said the iPad is following the desktop version logic, this seems to be a valid issue that deserves to be tracked.
