### ISSUE TITLE
Add UI test cases 

### ISSUE THREAD

**Issue by michelleXue** [wireapp/wire-ios#1840]
## Checklist (please check before submitting)

* [x] I checked the existing issues, and the issue was not reported before.

## The problem

Adding UI test cases to cover most GUIs to help users' daily usage.

## Environment

* Wire version that exhibits the issue: 2.41
* Last Wire version that did not exhibit the issue (if applicable):
* iOS version used to run Wire: iOS 10.3
* iOS device type: iPhone 7
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): Wi-Fi
* Exact date, time and timezone (only for the crash issues):

**Comment by mikeger** [comment]
Hey @michelleXue ! Thanks for submitting the issue. Can you elaborate more on what you see as an issue, and what should happen for it to be solved. Right now the issue is basically replicating your PR https://github.com/wireapp/wire-ios/pull/1841
