### ISSUE TITLE
Unable to create shared container url using app group identifier

### ISSUE THREAD

**Issue by liujieyuu** [wireapp/wire-ios#1872]
I try to compile the project operation, but when the show start page collapsed and console print < Warning > : / Users/pastjie/Downloads/wire - ios - develop2 / Carthage/Checkouts/wire - ios - utilities/Source/ZMDeploymentEnvironment. M: 39 ZMDeploymentEnvironment: internal
Fatal error: Unable to create Shared container url using app group identifier: group.com.Wire: file/Users/pastjie/Downloads/wire - ios - develop2 / Carthage/Checkouts/wire - ios - system/Source/ZMSAsserts. Swift, line 26

**Comment by vytis** [comment]
Hello @liujieyuu,
Are you trying to run in on device? It might be a bit of a problem because for everything to work correctly you need to have valid Wire development certificate in your machine. Running on simulator should be fine though!

**Comment by liujieyuu** [comment]
@vytis Yes, I ran it on the real machine, with my own developer account and certificate, but I don't know why, it crashed and then prompted this?

**Comment by vytis** [comment]
I think the best bet is to try running on debug build on simulator, running on real phone is much more tricky. It is possible to make it run on a phone, but you need to set up all provisioning profiles, app IDs and entitlements on your own developer account and change all these values in the codebase. This is not very straightforward, but should definitely be possible to do. However I cannot provide exact steps how to do it...

**Comment by liujieyuu** [comment]
@vytis Thank you. I've already configured it.

**Comment by vytis** [comment]
If it's not too hard, maybe you could describe what steps you took to get it running? Might be useful for other people that encounter a similar issue.

**Comment by vytis** [comment]
I will close this for now, feel free to open a new issue if you experience any other problems!

**Comment by liujieyuu** [comment]
@vytis It is to use the developer's account to create new APP ID, groupid and icloud container in the developer center, then select the newly built groupid and icloud container in the project, and the APP ID needs to be corresponding to the groupid.
