### ISSUE TITLE
Wire crashes when pressing re-record while playing recorded voice message

### ISSUE THREAD

**Issue by wire-issues** [wireapp/wire-ios#1880]
## Checklist (please check before submitting)

* [X] I checked the existing issues, and the issue was not reported before.

## The problem

Wire crashes when re-record button is pressed while the recently recorded voice message is being played.

## Environment

* Wire version that exhibits the issue: 3.8
* Last Wire version that did not exhibit the issue (if applicable): N/A
* iOS version used to run Wire: 9.3.3
* iOS device type: iPhone 5S
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): N/A
* Exact date, time and timezone (only for the crash issues): N/A

## Details

1. Record Voice Message.
2. Click to Listen recorded voice message.
3. Press re-record button while the message is playing.
4. **Wire Crash**.

**Comment by mikeger** [comment]
Hey @wire-issues ! It's flattering that you've created the special account (as I assume from it's name) to report the issues to us. Thanks for the report, it should be easy to reproduce and fix.
