### ISSUE TITLE
Can't install ./setup.sh

### ISSUE THREAD

**Issue by hprobotic** [wireapp/wire-ios#19]
When i try run ./setup.sh in project folder
Terminal show this message:
http://i.imgur.com/Lqvoerp.png

![image](https://cloud.githubusercontent.com/assets/5791885/17125944/67dd1066-5322-11e6-8331-d413565b233c.png)

How to fix?

**Comment by mikeger** [comment]
Hey @hprobotic! Thanks for reporting the issue. We will check it and give you the possible workaround/fix.

**Comment by hprobotic** [comment]
Hi @mikeger 
Thanks for your response, after few minutes, i will run this project
But i think we should update our install document:
- Run ./setup.sh by sudo
- Run `pod install`
- Open ProjectName.xcworkspace
Hope that help

**Comment by mikeger** [comment]
@hprobotic hey! Thanks for the feedback. If you check, `setup.sh` is already doing `pod install` on line 54: https://github.com/wireapp/wire-ios/blob/develop/setup.sh#L54

Also doing `setup.sh` is not required and *DANGEROUS* under sudo (usually). Also it is not convenient, if you do it under sudo your pods workspace would be created by superuser, and you would be unable to edit it. 

The issue you are facing is connected to renaming the frameworks: we used to have `zmc` prefix, now we are migrating to `wire-ios` prefix. Please stand by until we update all the frameworks & `Cartfile` in out repo

**Comment by mikeger** [comment]
@hprobotic can you try to pull and test it now? It should be fixed. Have fun! 👍

**Comment by marcoconti83** [comment]
@hprobotic please let us know if the problem is fixed for you on the most recent master branch, so we can close the issue. Thanks!

**Comment by hprobotic** [comment]
Thanks @marcoconti83 and your team for hard work, every things work like charm right now, We able to close this issue. Hope can return asap 💃
