### ISSUE TITLE
Change the ios app request address.

### ISSUE THREAD

**Issue by liujieyuu** [wireapp/wire-ios#1936]
Hello, now we servers, ios mobile terminal, all using this code, you want to run, but the ios side when local access address changes to the question, I address changed to our servers, however, is the HTTPS protocol, our server is http:// for me, don't know how to change now, hope you can help me.

**Comment by mikeger** [comment]
Hey @liujieyuu ! I think that iOS forbids using the un-encrypted HTTP nowadays. Please consider getting yourself a HTTPs certificate from [LetsEncrypt](https://letsencrypt.org/) -- it's free. Additionally you have to drop the requirements for the certificate pinning that we are setting in [ZMServerTrust.m](https://github.com/wireapp/wire-ios-transport/blob/develop/Source/URLSession/ZMServerTrust.m).

**Comment by mikeger** [comment]
Hey @liujieyuu ! If you have no follow-up questions I guess I can close the ticket for the sake of housekeeping?

**Comment by liujieyuu** [comment]
@mikeger thanks
