### ISSUE TITLE
Render transparent background images (PNG) correctly

### ISSUE THREAD

**Issue by WildYorkies** [wireapp/wire-ios#1953]
## Checklist (please check before submitting)

* [x] I checked the existing issues, and the issue was not reported before.

## The problem

I posted a PNG with a transparent background into the conversation. Instead of having a transparent background (like a Telegram sticker), it was inside of a white box. 

Issue is that the background defaulted to pure white and there was a box with defined borders around it.

If people want to do funny things like "stickers", I think rendering these correctly is a first step.

## Environment

* iOS version used to run Wire:latest
* iOS device type: latest

## Details

Find any PNG with a transparent background and send it to someone.

## Screenshots

![wire 2018-04-02 at 14 22 16](https://user-images.githubusercontent.com/1299322/38216980-66c31d12-3681-11e8-8620-19f5627be96d.jpeg)

**Comment by billypchan** [comment]
Hi @WildYorkies, thank you for your report. We are working on this issue.

**Comment by billypchan** [comment]
This feature is implemented in the current version.
