### ISSUE TITLE
iPhone 4 / iOS 7 Support

### ISSUE THREAD

**Issue by aqeeliz** [wireapp/wire-ios#196]
Hi,

I invited someone on wire, but they are using iPhone 4 which only supports iOS versions upto 7, whereas wire requires minimum of iOS 8.

Is there any way to make wire run on iOS7? Or does iOS 7 lack certain feature without which wire can't work?

**Comment by david-wire** [comment]
Hello,

Thanks for the feedback. Like most start-up companies, we aim to balance product improvements and updates with a delivery of the best user experience. We optimize Wire to deliver the smoothest user experience on the latest devices and operating systems. iOS 7 is currently not on our roadmap.

Wire Support Team.
