### ISSUE TITLE
Full "Off line first"

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#197]
It would be interesting to have a full "offline first" app.

Each user action, could be localy stored on a stack (with a timestamp). 
As soon as there is a network available, the app unstack them online -- in the correct order (FIFO) -- and retry until explicit user cancelation only (for each individual items).

The "to be sent" and "sending" state could be rendered by fading the writing for the former and blinking for the later.

**Comment by david-wire** [comment]
Hello,

Thanks for the feedback. We are always looking for ways to improve Wire. 
This is an interesting point. I'll pass it onto the team.

Wire Support Team.
