### ISSUE TITLE
Multiple ID for usage isolation

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#199]
For usage isolation, it would interesting to be able to have multiple ID at the same time on the app.

For exemple, one ID for friend, one for family and one for work.
Each ID, have their own notification (with separate notification token) and contact list / conversation.

**Comment by david-wire** [comment]
Hello,

Thanks for the feedback. This is also an interesting point and thanks for taking the time to share this. I'll forward to the team.

Wire Support Team.

**Comment by vorobievalex** [comment]
This seems already implemented. I receive notification to the both active and other accounts added in the app.

**Comment by typfel** [comment]
Yes, this implemented since a few releases.
