### ISSUE TITLE
Unable to build because can’t find GoogleAPIClient

### ISSUE THREAD

**Issue by jaanus** [wireapp/wire-ios#2]
Was following the build instructions, doing a build from scratch and everything went smoothly, until it didn’t. Can’t resolve `GoogleAPIClient/YouTube (= 1.0.4)` for whatever reason.

```
[!] Unable to satisfy the following requirements:

- `GoogleAPIClient/YouTube (= 1.0.4)` required by `Podfile`
- `GoogleAPIClient/YouTube (= 1.0.4)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `GoogleAPIClient/YouTube (= 1.0.4)`.
```

![screen shot 2016-07-22 at 14 12 42](https://cloud.githubusercontent.com/assets/184253/17055622/a29a03b2-5016-11e6-9e10-2fafe6ad7cd7.png)

**Comment by daehn** [comment]
Hey, thanks for letting us know. It might be the case that your local pod repo is not in sync with the CocoaPods master repo. Please try running a `pod repo update` and run the setup script  afterwards, we might need to add this step to the script as CocoaPods 1.0 does not do an initial repo update on pod install.

**Comment by jaanus** [comment]
Yep, this was a fresh install of all the tools. Indeed, running `bundle exec pod repo update` and then running the setup again fixed it, thanks 👍  You may want to update the readme with that.

**Comment by daehn** [comment]
Updated the README with instructions in https://github.com/wireapp/wire-ios/pull/5
