### ISSUE TITLE
Security : do not store picture into picture roll by default

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#200]
In a way to improve security / privacy, it would be better to not store taken pictures to the user picture roll.

Maybe it would be better to be optional and turned off by default.

What's happen in wire, stay in wire :p

**Comment by david-wire** [comment]
Hello,

Thanks for the feedback. I'll raise this with the team. This is not planned at the moment but as soon as we have new app developments, we will communicate them via our website and our blog.
We are taking users' desired features very much into account in our planning, and we aim to get new features out as quickly as we can.

Wire Support Team.

**Comment by BenoitFroment** [comment]
Any update on this ?
