### ISSUE TITLE
Low profile notification

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#201]
In a way to improve security/privacy, it would be better to show minimum information about a message, on the notification.
By default, just something like "You just received a new wire" to draw the user attention back to the app.

**Comment by david-wire** [comment]
Hello,

Thanks for the feedback. This is already an option in Settings (Sounds & Alerts > Notifications > Message previews: toggle off).
I hope that helps.

Wire Support Team.

**Comment by mikeger** [comment]
@IpsmLorem we have it, under cogwheel icon -> Settings -> Sounds & Alerts
<img width="487" alt="screen shot 2016-09-13 at 15 52 12" src="https://cloud.githubusercontent.com/assets/715129/18476433/4249a728-79ca-11e6-9b8d-5e49e5ac967f.png">

**Comment by IpsmLorem** [comment]
Thank you for pointing it out !
Maybe, to follow a secure by default policy, switch detail off by default ?

**Comment by jenskasemets** [comment]
Majority of our users prefer to see message content on notification, currently we decided to keep it like it is. If in the future we have different factual data, we might reconsider this decision.
