### ISSUE TITLE
ERROR ITMS-90206:"Invalid Bundle. The bundle at  ‘Wire.app/Frameworks/WireCryptobox.framework contains disallow file Frameworks’

### ISSUE THREAD

**Issue by liujieyuu** [wireapp/wire-ios#2019]
Me something in your code encapsulation in my project, ready to submit to The App Store, The result ERROR when uploading prompt ERROR ITMS - 90206: "Invalid Bundle. The Bundle at 'Wire. The App/Frameworks/WireCryptobox framework contains disallow The file Frameworks'. I tried a lot of methods on Google, but I still don't know if there is a solution to your problem. My xcode version is xcode9.x.

**Comment by mikeger** [comment]
Hi @liujieyuu  ,

Please note that our source code is licensed under GPLv3, which means that all derived work/projects needs to be open sourced under the same license. There are also conflicts between the AppStore terms and GPLv3 which prevent submitting apps containing code licensed under GPLv3 to the AppStore. You can find more details here: https://www.fsf.org/blogs/licensing/more-about-the-app-store-gpl-enforcement.

**Comment by liujieyuu** [comment]
@mikeger thanks

**Comment by UjeshPatelSA** [comment]
@liujieyuu How did you get resolve it?
