### ISSUE TITLE
Prevent leading people to dangerous links

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#204]
When you send a link to someone, the recipient wire app dowload the link and interpret / parse the target to retrieve enough elements to be able to construct a preview.
This could lead to a drive-by-download attack to a malware or a legal issue (forbidden link).

Could you reverse the approach ?
The sender download itself (he can take the responsability for the safety of their own material, right ?) the URL target is downloaded be the sender, and only a safe picture preview is sent to the recipient, with a link.
Up to the recipient to visit this link, if he wants to.

**Comment by typfel** [comment]
That's how it works when you share a link on wire. The sender parses the webpage and sends the preview as an update to the original message. The receiver never hits any external server until he/she decides to open the link.

**Comment by IpsmLorem** [comment]
Congratulation then. Good work ! :+1:
