### ISSUE TITLE
More actions to a message

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#205]
When you long press a message you have the actions: Copy/Like/Edit/Delete

It would be interesting to add:
- Reply: take the orginal message/media and let the sender add something to it, with a quote of the orginal message/media
- Forward: forward the message to another conversation / contact

**Comment by david-wire** [comment]
Thanks for the insights.

**Comment by jenskasemets** [comment]
Message forwarding is now available in version 2.23

**Comment by jenskasemets** [comment]
I'm closing this issue now as forwarding is available and request for replying messages is covered in separete issue: #428
