### ISSUE TITLE
Define recipient storage policy

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#206]
Wire has a great feature: be able to delete (and even modify) a sent message/media.
It would be interesting to define an automatic delete / export policy, according to a message / contact / conversation. 

For exemple: all sending to the recipient (A) must be deleted 30' after being viewed on at least one device and cannot be exported (prevent saving / screenshot)

The purpose is not to prevent threat from a malicious recipient but lower the leakage risk by setting usefulness context of sending and give them to the recipients.

For exemple, a sender may set their policy to delete all sent messages after 2 days. 
He thinks that it's sufficient to read/understand/enjoy their messages and there is no need for longer storage anywhere.

**Comment by someoneEsle** [comment]
To be honest I think this is unnecessary and a little bit confusing too. I can't think of a good, clear and unmistakable way of letting the users know that they have this option

**Comment by IpsmLorem** [comment]
A simple way:  a per discussion option, to automatically delete all sent message after the threshold set.
For exemple: 
* for the discussion with your beloved one Katty, go to their discussion options (right slide on a the discussion to display Mute/Archive/Delete/Block/Policy) and choose policy
* choose your sending policy for this discussion: i.e. delete all sent / received messages for all recipients after 1 hour

The wire behavior would be the same as deleting "by hand" after one our, each sent and received message

On the general settings (wheel icon/settings/Privacy & Security), one can set the default policy for each new discussions.

**Comment by jenskasemets** [comment]
Timed messages were now introduced in last releases, enjoy!
