### ISSUE TITLE
Wire is running in background a lot

### ISSUE THREAD

**Issue by rbieb** [wireapp/wire-ios#2084]
## The problem

Wire is running a lot in the background (as can be seen in iOS's battery usage info. This is even the case, when there are barely no messages incoming or being sent.

Background usage should be limited to minimum, as is the case with other messengers, like Whatsapp or Telegram.

## Environment

* Wire version that exhibits the issue: All of them
* iOS version used to run Wire: 11.3.1
* iOS device type: iPhone X
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): Definitely LTE and Wifi, no idea about the rest

## Details

Just look at the battery info in iOS and check out the battery usage of wire.

**Comment by typfel** [comment]
Hi, thanks for reporting this. Could you provide how many hours Wire has spent active in background for the last 24h / 7 days. To show this information show you need to tap the clock button on the right side.

![img_1083](https://user-images.githubusercontent.com/7156/39693213-98d54550-51e3-11e8-9aae-851740c0c27a.jpg)

**Comment by cardassian-tailor** [comment]
I was curious about this also. Mine seemed a bit high. For me, past seven days background hours is 8.5 hours.

**Comment by Siguza** [comment]
Last night my phone had almost its entire battery drained by Wire. I went to sleep shortly after midnight and put the phone in airplane mode. I think the screenshot speaks for itself.

![IMG_1296](https://user-images.githubusercontent.com/1659374/89468726-6217dd80-d778-11ea-93c8-c58a7b63ae80.png)

iPhone SE 2020, iOS 13.6, Wire v3.63.
