### ISSUE TITLE
Assets not found for iOS client

### ISSUE THREAD

**Issue by SV8** [wireapp/wire-ios#2118]
## The problem

./setup.sh
No access to assets

Or:
./Scripts/download-assets.sh
No access to assets

Or:
git clone --depth 1 git@github.com:wireapp/wire-ios-build-assets.git
Cloning into 'wire-ios-build-assets'...
ERROR: Repository not found.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

Finally I checked the repos under https://github.com/wireapp. No repo named "wire-ios-build-assets" out there.

**Comment by mikeger** [comment]
Hey @SV8 ! The assets are containing the private xcconfig files that contain the API keys for Wire app. You generally don't need those API keys when you compile locally:
1. Youtube image preview fetching would not work on the simulator, so no need for the Youtube API key;
2. Tracking is disabled, so no need for the tracking API key (Mixpanel);
3. Giphy is using the public debug API key, so it will work;
4. Crash reporting is disabled in non-release build
