### ISSUE TITLE
Be able to have several discussions with the same recipients

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#212]
It would be interesting to be able to have several discussions with the same recipients. This could make easier to have separate topics and follow them.

For exemple, with Katty and John:
- a named discussion "Next week-end party"
- a named discussion "Casual chat"

**Comment by david-wire** [comment]
Interesting point, nothing planned in this area for now though.

**Comment by IpsmLorem** [comment]
Thanks, nice to know. Can you do several group discussions whith the same recipients ?

**Comment by marcoconti83** [comment]
Yes, you can create new group conversations independently of whether you are already in another group conversation with exactly the same people.
