### ISSUE TITLE
Improve getting missed messages

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#213]
When getting missed messages "message from xxx was not received", give the recipient the choice to tap on it.
It would send back to the sender a warning (quoting/pointing  the orginal message) to ask to resend it.

**Comment by marcoconti83** [comment]
This is linked to https://github.com/wireapp/wire-ios/issues/358.
As mentioned there, we expect to eliminate completely the "message from xxx was received" as we fix the bug that causes it.
