### ISSUE TITLE
Wire application access prevention

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#217]
Since Wire content sensitive data in the first place, it would be interesting to give to user a way to prevent unwanted/inadvertently access to the application.

An optional 4 digits tri-pin (geometric form / color / number) to open the iOS app would be interesting. The tri-PIN prevent compromising the PIN by shoulder surfing, since each time the tri-PIN keyboard is displayed, the position of each symbol is randomly changed.
See http://www.onesafe-apps.com/tri-pin

TouchID option coudl also be used if available.

**Comment by raphaelrobert** [comment]
This was addressed in #210 already.

**Comment by IpsmLorem** [comment]
Thank you.
I hope I was not confusing. I was refering to storage protection in #210 and application access protection on this one.
