### ISSUE TITLE
Line break sending and send button hiden

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#218]
When choosing the emoji Keyboard, the send button disappear, forcing the user to revert back to the regular keyboard.
Furthermore, it would be nice to be able to send breaking line.

One way to cover both needs, would be to display a dedicated send button within the app (instead of the GIF button, which could be go to the media menu below the editing line ?)

**Comment by david-wire** [comment]
Thanks for the feedback, will certainly let our designers know.

**Comment by jenskasemets** [comment]
This change was implemented in release 2.18
