### ISSUE TITLE
Security / management messages display within discussions

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#219]
Security / management messages ("you add a new device", "message was not recevied" and so on) within discussions should be displayed differently than users messages (sent / received).

See wire as a passive discussion sender, staying there for the smooth running of the discussion.

**Comment by david-wire** [comment]
Hi, thanks for the note. Not sure I understand this one. "A message was not received" is already displayed differently that user messages (upper case / lower case and different font). Any other input appreciated.

**Comment by IpsmLorem** [comment]
System messages from Wire (e.g. 1 and 2) should be displayed differently than contact messages (e.g. 3), since they are far more important:

![cap](https://cloud.githubusercontent.com/assets/1250795/19761804/a9dc9172-9c37-11e6-81c6-13aec8d0a92e.png)

**Comment by jenskasemets** [comment]
Thank you for your input. As @david-wire mentioned above, messages sent from users and system messages are already quite different: different font size, uppercase vs lowercase, horizontal line etc. 
We have tried different approaches to differentiate system messages from user created content and this current solution has best balance between usability, visual design, readability etc.

We constantly improve our app components design, we'll keep this request in mind when next time will need to change design for the messages in the conversation.
