### ISSUE TITLE
Zooming images in fullscreen mode

### ISSUE THREAD

**Issue by iwxxcz** [wireapp/wire-ios#2227]
## Checklist (please check before submitting)

* [x] I checked the existing issues, and the issue was not reported before.

## The problem

Image of certain sizes (e.g 338x600) not presenting for whole width nor height (see first picture). Also zooming in vertical orientation for this image is disabled at all. 

Suggestion: present images scaled up to size of view (see second picture)

## Environment

* Wire version that exhibits the issue: 3.14 (3036)
* iOS version used to run Wire: 11.4
* iOS device type: iPhone 7

## Screenshots
![1](https://user-images.githubusercontent.com/8351932/40853837-19a8ae4e-65d8-11e8-9e19-c5965d78eae2.png)
![2](https://user-images.githubusercontent.com/8351932/40853900-4642561c-65d8-11e8-8fcc-393aa01a7fec.png)

**Comment by mikeger** [comment]
Hey @iwxxcz ! Thanks for reporting the issue, we are going to take a look and try to include the fix in the coming releases.

**Comment by billypchan** [comment]
This feature is included in the latest release.
