### ISSUE TITLE
Forensic trace of deleted message ?

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#226]
As stated on (http://www.zdziarski.com/blog/?p=5993 / http://www.zdziarski.com/blog/?p=6143), some storage engine (E.g. SQLlite) doen"t really delete stuff, but only marked them as "freeable", for performance purpose.

I don't know what Wire use as the storage engine, but that kind of risk must be taken into account.

As proposed at #210 , Wire encryption at rest on iOS can adress the issue.

Quoting:

> What about a first run generated key, stored in the keychain, used only for local storage encryption ?
No password derived at all and can be used by Wire app without further user interaction.
By the way, this could open the option to provide to user a stronger ACL, if desired.

**Comment by raphaelrobert** [comment]
The concerns were already addressed in #210 in a larger context. Additional encryption at rest doesn't solve any problem at this point.
