### ISSUE TITLE
Migrate to Swift 4

### ISSUE THREAD

**Issue by crystalztl** [wireapp/wire-ios#2268]
Could I know when will you migrate to Swift4?

**Comment by vytis** [comment]
Hello, we are currently in progress, see https://github.com/wireapp/wire-ios-system/pull/27 and https://github.com/wireapp/wire-ios-utilities/pull/41. However the app includes 16 frameworks in total and it's quite a lot of work to do the migration, but we are on it.

**Comment by vytis** [comment]
We just finished migrating to Swift 4!
