### ISSUE TITLE
wire 2.15 crashes on startup on iOS 8.x

### ISSUE THREAD

**Issue by 0ki** [wireapp/wire-ios#227]
Worked fine with previous wire version.

**Comment by mikeger** [comment]
Hey @0ki ! Thanks for reporting the issue. We support iOS8, and in the next release (2.16) we would have this issue fixed. If you would like to get the fix faster you can check out branch `release/2.16` and build your own client from sources.

**Comment by 0ki** [comment]
Resolved.
