### ISSUE TITLE
Delay notification mechanism like Slack

### ISSUE THREAD

**Issue by Marcopohlo** [wireapp/wire-ios#2293]
Hello,

Currently even if you have wire desktop open and active on chat, whenever new message arrives, you are notified on all linked devices. That includes iPhone and Apple Watch. Which is really annoying. 

I would love to see a settings which would allow you to set period of time before you will receive notification on your mobile device while you are actively using desktop app.

Thank you very much.

**Comment by mikeger** [comment]
Hey @Marcopohlo ! Thanks for the suggestion, I believe we have the improvements that you've mentioned on our radar. As you might guess, the changes of this kind cannot be done on one platform, so I would suggest to repost your suggestion to the general issue tracker at https://github.com/wireapp/wire/issues
