### ISSUE TITLE
iOS users can't watch .webm videos if android- or webusers send them (because they can see and watch them)

### ISSUE THREAD

**Issue by tokariu** [wireapp/wire-ios#2316]
iPhone (or iOS) users seem to have problem to watch .webm video clips within wire.

android and desktop client users (at least on windows/linux) do not seem to have a problem watching .webm movies in wire. And because .webm is working for them, they tend to forward them to other users, but when they are using an iOS client, they can't watch them.
I therefor often get conversation like this:
"I can't watch this video you sent"
"why not? ..i can see it?"
"I don't know!"
(other 3rd person) "I can see it too"
(other 4th person) - "I can't see it either.."
etc..

I had a little research and as it seems apple does not support webm and googles codec out of the box because they supported mp4/h.264. therefor all chromium browsers and chromium based apps lack the support of .webm videos on iOS. This really sucks if you share a .webm in a group where different people use different clients and some people can see the video while others can't.

Is there any way to help people on iOS clients to be able to watch these videos?

**Comment by mikeger** [comment]
@tokariu we are using the iOS integrated media stack in order to play the video messages, this implies that we are going to support exactly what iOS does, and unfortunately this does not include the WebM container / VP8+VP9 codec formats. Unfortunately we have no plans at the moment to change that approach, since it implies the significant amount of work in order to introduce the custom video player.

As the workaround I can propose to separate the concerns and install the dedicated WebM player on iOS, in order to play those messages with it.

**Comment by tokariu** [comment]
so what is the way to go for iOS users? I don't own any iOS device.

should they install something like xtremeplayer or VLC (if available)? if they click on the broken video in the conversation, do they get a choice to play the video in an external player?

**Comment by mikeger** [comment]
I've just tested it, when the webm video is sent from the desktop version, on iOS it appears as the video, but it's not possible to neither play, nor forward to another app, so it's basically not possible to use. I think the possible initial fix from our side would be to display webm file as the document, so user at least can open it in VLC or other player.

**Comment by mikeger** [comment]
Hey @tokariu ! I tested it (receiving the WebM video on iOS) with and without the player (VLC) insatlled, if the player was not installed, we display the file as the document, if it is installed, we are displaying the file as the video, but the iOS integrated control is failing to play it.

This fix must make it always show the WebM as the document, so it's possible to play it in VLC: https://github.com/wireapp/wire-ios-data-model/pull/506

**Comment by tokariu** [comment]
@mikeger okay.. so after next release what is it going to look like?
do iOS users still get a video preview thumbnail in the conversation if it's .webm? or do they only get the preview if an external video player supporting webm is installed?

as far as i understand, the .webm video is going to be displayed as a document attachment then, rather than a video preview thumbnail. obviously this is needed to open the file with an external player. correct me if I'm wrong.

if this is the case I find this solution improvable. because nothing is less attractive as a video file without an image preview in the conversation. and it's also really clumsy to open an attachment (count the menu's and clicks until you get there!) just to play it with an external player. 

the most elegant solution would be: if a webm capable player is installed on iOS, render a video thumbnail in the conversation. if the iOS user clicks on it, let it open/play in the external player. do not handle it as attachment with the clumsy submenus. 
if the user does not have a webm capable player installed on iOS, then show it as document attachment. no video preview. user can download the video attachement as document file.

**Comment by mikeger** [comment]
Hey, I realize that the current fix is not ideal, however it allows the video file to be played. The video appears as the file with the small preview. Clicking on it offers the iOS open in dialogue where it is possible to select the VLC or other player.

**Comment by tokariu** [comment]
ah okay, so.. that actually sounds promising.. 
as I don't own an iOS device.. could you be so kind and make a screenshot of how it looks like for iOS users when they have a .webm video in their conversation? (w/ and w/o a vlc player installed?). is the thumbnail the same as the one on android/desktop regarding size?
