### ISSUE TITLE
Data leak: Wire not respecting data usage permissions (hockeyapp.net)

### ISSUE THREAD

**Issue by romainw** [wireapp/wire-ios#2318]
Even after disabling "Send Anonymous Data" and "Calling Debug Report", and dully restarting the application, Wire-ios (3.15 (3044) on iOS 11 always does contact gat.hockeyapp.net upon start-up.

POST /v2/track HTTP/1.1
Host: gate.hockeyapp.net
Content-Type: application/x-json-stream
Connection: close
Charset: UTF-8
Accept: */*
Content-Encoding: gzip
Accept-Language: en-gb
Content-Length: 441
Accept-Encoding: gzip, deflate
User-Agent: Wire/3044 CFNetwork/901.1 Darwin/17.6.0
Decoded-Content:

{"iKey":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX","name":"Microsoft.ApplicationInsights.SessionState","time":"2018-06-26T09:32:39.674Z","data":{"baseData":{"ver":2,"state":0},"baseType":"SessionStateData"},"ver":1,"sampleRate":100,"tags":{"ai.device.screenResolution":"1334x750","ai.user.id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX","ai.device.locale":"en_FR","ai.device.model":"iPhone9,3","ai.application.ver":"3.15 (3044)","ai.device.type":"Phone","ai.internal.sdkVersion":"ios:5.0.0","ai.device.oemName":"Apple","ai.device.osVersion":"11.4 (15F79)","ai.session.isFirst":"false","ai.device.id":"XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX","ai.session.id":"XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX","ai.device.language":"en","ai.session.isNew":"true","ai.device.os":"iOS"}}

This does seem to include a unique ID for the device.

Obviously, sending tracking information despite the user explicit request not to do so is an issue.

I suspect the technical issue is linked with the iOS SDK used to compile the application, not necessarily with the Wire-ios source code itself.

**Comment by mikeger** [comment]
Hey @romainw ! Thanks for the report, we are going to investigate it as the 1st priority.

**Comment by vytis** [comment]
Thanks again for reporting, we confirmed the issue and fix will go out with the next update!

**Comment by romainw** [comment]
Many thanks for the very quick fix!

Given device or user (?) unique identifiers were shared with a third party despite user explicit opt-out, there is a potential privacy impact linked with this issue.
In order to continue position Wire as a strongly privacy-aware company and product, I think it would be greatly helpful to explain transparently what happened (#2326 is quite explicit) and what information exactly was erroneously shared with Hockeyapp, as part of the next release notes.

(There are also various GDPR templates which could help (https://gdpr-info.eu/art-33-gdpr/, etc.).)

Thank you again for your prompt reaction.
