### ISSUE TITLE
Pronounceable Mnemonic for audio key verification by using BIP39

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#232]
For an easy audio key verification, it would be interesting to display the key as a pronounceable mnemonic phrase.

What about using the BIP39 (https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki) standard to transforme the 256 bits key to 24 words suite ?
That way, your key can be read out loud over a side audio channel and can be translated in several language (English, Japanese, Spanish, Chinese, French, Italian) : https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md

**Comment by raphaelrobert** [comment]
Sounds like an original idea to make fingerprints more fun!

**Comment by IpsmLorem** [comment]
Close by mistake or this wasn't a realistic idea ?

**Comment by raphaelrobert** [comment]
This is not an idea we will pursue right now.
