### ISSUE TITLE
Invite Link generation like desktop app

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#242]
iOS app cannot create invite link like the desktop app can:
"This link can be used for 2 weeks : Let’s connect on Wire.
Modern, private communication. https://wire.com/c/************"

**Comment by mikeger** [comment]
Hey @IpsmLorem , thanks for your suggestion! We are looking on how to put it up in the best way. We'll have you tuned when the changes would be scheduled for the release.

**Comment by IpsmLorem** [comment]
It seems that the feature is gone on desktop too ?

**Comment by marcoconti83** [comment]
Hi @IpsmLorem , we are working on something that will change the entire invitation system. Stay tuned.

**Comment by jenskasemets** [comment]
Now invite links on all platforms use usernames:
https://medium.com/wire-news/time-to-get-your-username-3a54fd31edc3
