### ISSUE TITLE
vanishing messages

### ISSUE THREAD

**Issue by dbquarrel** [wireapp/wire-ios#2427]
## Checklist (please check before submitting)

* [x] I checked the existing issues, and the issue was not reported before.

## The problem

Sent messages disappear after less than one second.

## Environment

* Wire version that exhibits the issue: 3.17
* Last Wire version that did not exhibit the issue (if applicable): 3.15
* iOS version used to run Wire: 10.3.3 / 11.4
* iOS device type: iPhone 6 / iPhone X
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): wifi
* Exact date, time and timezone (only for the crash issues): 

## Details

Talking with a contact that has 1 hour message expiration, me with 1 hour message expiration, some of my messages delete in less than one second for both sender and recipient. As well, with the contact having no expiration timer at all, the contacts messages have deleted in less than one second on both ends. This seems to be new behavior from the last one or two versions. 

Also it is on the desktop, not just iOS.

This appeared with contacts in the same time zone as me, or in different timezones.

**Comment by mikeger** [comment]
Hey @dbquarrel ! Thanks for reaching out to us. Unfortunately I cannot reproduce the issue. Can you check if you do something special when the issue appears?
