### ISSUE TITLE
Some Memory error

### ISSUE THREAD

**Issue by crystalztl** [wireapp/wire-ios#2449]
Please refer to the pictures.
<img width="858" alt="screen shot 2018-07-26 at 2 53 57 pm" src="https://user-images.githubusercontent.com/8706166/43246514-745f15f8-90e4-11e8-9a5a-05e7f236170c.png">
<img width="861" alt="screen shot 2018-07-26 at 2 55 19 pm" src="https://user-images.githubusercontent.com/8706166/43246516-749f5ee2-90e4-11e8-9e8b-92ee0e8e0fd9.png">
<img width="879" alt="screen shot 2018-07-26 at 2 56 27 pm" src="https://user-images.githubusercontent.com/8706166/43246518-74da1b04-90e4-11e8-9da4-5a7eb039601b.png">
<img width="871" alt="screen shot 2018-07-26 at 2 56 52 pm" src="https://user-images.githubusercontent.com/8706166/43246520-751a64a2-90e4-11e8-996b-5b4077d8bd05.png">
<img width="857" alt="screen shot 2018-07-26 at 2 57 34 pm" src="https://user-images.githubusercontent.com/8706166/43246521-7559e6d6-90e4-11e8-9672-15699724e814.png">

**Comment by alexaubry** [comment]
Fixed with #3198.
