### ISSUE TITLE
 Where is encryption and decryption triggered when sending a message, and what type?

### ISSUE THREAD

**Issue by liujieyuu** [wireapp/wire-ios#2464]
I installed one on the ios side and the background server side of your app, and found that the data was encrypted. I would like to ask which method is the encryption and decryption in the wire-ios-cryptobox?

**Comment by liujieyuu** [comment]
The introduction of the wire-ios project mentions:The sync engine itself is built on top of a few third-party frameworks, and uses Wire components that are shared between platforms for cryptography (Proteus/Cryptobox) and audio-video signaling (AVS).I want to know exactly where the encryption is implemented and the class file of the encryption method. Could you please tell me

**Comment by mikeger** [comment]
Hey @liujieyuu ! Thanks for interesting in our encryption system. You can read more in our security whitepaper here https://wire-docs.wire.com/download/Wire+Security+Whitepaper.pdf
