### ISSUE TITLE
Asking for notification permission every time

### ISSUE THREAD

**Issue by 0ki** [wireapp/wire-ios#250]
Every time I open Wire on my secondary device (where I have notifications disabled in Settings), it hides my contact list and shows "Please enable notifications" instead.

The option "never ask me again" is not there. I can either enable notification or get a reminder next time.

I believe this is a bug.

**Comment by david-wire** [comment]
Thanks for the note. This happens when you have not opened Wire for a while on your secondary device. 
We do not have that option available, but a 'Maybe later' one instead. Thanks for the feedback though, I will forward to the team.

**Comment by 0ki** [comment]
This bug is still present in 2.17.

**Comment by 0ki** [comment]
Bug still present in 2.20. How do I reopen this?

**Comment by 0ki** [comment]
Please re-open.

**Comment by IpsmLorem** [comment]
#243

**Comment by 0ki** [comment]
Still present in 2.23.

**Comment by 0ki** [comment]
Seems to be fixed in 2.28.
