### ISSUE TITLE
Unremovable unwanted contacts

### ISSUE THREAD

**Issue by mmokhi** [wireapp/wire-ios#2609]
Hi,
There was a weird issue, just after I installed the app.
Not technically probably but in design of the app's systems...

When I let it add contacts from my contact-list it adds everyone who uses Wire which is OK, but the problem is I can't later decide who is "really" I wanna keep in my "connections list" .

So let's say I have phone number of the pizza delivery guy at district in my contact-list on phone and now he is in my "connections" in Wire...
I couldn't find any way to remove them from my connections and on FAQ the only suggestion is to block...
Am I missing something or you need to add a "remove from connections" feature on app :slightly_smiling_face:

**Comment by mikeger** [comment]
Hey @mmokhi ! Sorry to hear that you are having the issue, I believe the only way to remove the people you don't want from the app is to block those people, may be going forward we are going to revisit this part, but for now it's not the case. Sorry!

**Comment by mmokhi** [comment]
Hey,
Thanks for quick response :+1: 

OK, for now I blocked the unwanted contacts, hopefully we'll see the feature soon-ish
(or maybe I'll apply for a job there and you'll have a guy to fix it :thinking: :wink: )

**Comment by mikeger** [comment]
I'll close it for the time being, thanks!
