### ISSUE TITLE
Iphone SE cannot play voice messages sent from Android

### ISSUE THREAD

**Issue by DrAxelbauer** [wireapp/wire-ios#2618]
I sent from my Android smartphone a voice message into the group chat. All the other people can play the voice message except iphone se users. Seems to be a bug in ios.

Environment
Iphone SE 
11.4.1 (15G77)
MP822DN/A
FDDW900HTVL
Wire Version: freshly updated 3.19

Android Device used für recording the voice message:
Wire Version: 3.16.638
Meizu MX4 
M461 
Flyme 6.2.0.0G
Android Version: 5.1

**Comment by mikeger** [comment]
Hey @DrAxelbauer ! This issue was fixed from the android side, please advise the message sender to update when the next release would be available. Thanks!

**Comment by DrAxelbauer** [comment]
...Interesting...i had version 3.16.638 and downgraded to 3.15.634..now it works again..

**Comment by mikeger** [comment]
Most likely the version 3.16.638 has the regression that was fixed now, but not published yet. Please stay tuned.

**Comment by axel-rank** [comment]
Even if you record a message on ios and send it to a android contact you cant hear your own message.
How to install the 3.17. rc? Have to build the .apk from source?
Anyway this is a heavy bug. Why didn't you released a bugfix yet?
Where to find the .apk from older releases?

**Comment by mikeger** [comment]
Hey @axel-rank ! Thanks for the information about the issue. The Android release is being released as we speak. You must get the update in the upcoming days (it's the staged rollout, so it can come earlier or later).

**Comment by mikeger** [comment]
@alex-rank this must be fixed with the current Android release. Can you confirm?

**Comment by axel-rank** [comment]
Yes, working again.

**Comment by mikeger** [comment]
Glad to hear!
