### ISSUE TITLE
Hyperlink to Wire Profile?

### ISSUE THREAD

**Issue by kesenwang** [wireapp/wire-ios#2636]
## Checklist (please check before submitting)

* [ x] I checked the existing issues, and the issue was not reported before.

## The problem

I was just wondering if this is possible and how to pull it off, but is there anyway to link to a Wire profile and have it open in app, like not a share extension but rather like a link and when someone clicks it Wire would open to the profile specified and allow the user to then request to become connected with that profile? Because now it’s just like you would have to search the username right.

## Environment

* Wire version that exhibits the issue: iOS Beta
* Last Wire version that did not exhibit the issue (if applicable):
* iOS version used to run Wire: 12
* iOS device type: iPhone 8
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): LTE
* Exact date, time and timezone (only for the crash issues):

**Comment by mikeger** [comment]
Hey @kesenwang ! Thanks for the suggestion, we've been thinking about this, but no timeline to be shared yet. I would also suggest to post the high-level (i.e. not directly iOS-client related) issues here: https://github.com/wireapp/wire
