### ISSUE TITLE
Turning off "message previews" cripples ability to receive calls

### ISSUE THREAD

**Issue by 0ki** [wireapp/wire-ios#264]
When "Message previews" are turned off (great security feature, kudos!), it does not only remove the source and content of the message from the notification. It also removes information about interaction type. Thus wire cannot determine if it's a message, ping or an incoming call.
Ergo, it cannot play the correct sound. This leads to tons of missed calls.

Please make it so that type of notification is visible when "message previews" are off.

**Comment by marcoconti83** [comment]
Hi @0ki , thanks for reporting the issue. We will look into it.

**Comment by 0ki** [comment]
A related, but not necessarily causated bug report. Please take a look at it, while working on notifications.

Seems that I am sporadicly receiving phantom "New message" notifications when a users starts typing a message, even when it's not being sent. Could that be a thing?

**Comment by 0ki** [comment]
This seems to be fixed with 2.23 CallKit integration. Can someone else confirm?

**Comment by jenskasemets** [comment]
Closing as there's no more feedback and issue is fixed
