### ISSUE TITLE
How do you change the server ip address to own dedicated wire-server instance ip?

### ISSUE THREAD

**Issue by imanodaysoffdotcom** [wireapp/wire-ios#2644]
For ios and Android How do you change the server ip address to own dedicated wire-server instance ip?

**Comment by mikeger** [comment]
Hey @imanodaysoffdotcom ! Thanks for the request, you can change the backend URL here https://github.com/wireapp/wire-ios-transport/blob/develop/Source/Environments/ZMBackendEnvironment.m
