### ISSUE TITLE
Can't login, "First time you are using Wire on this device" screen is scrolled down

### ISSUE THREAD

**Issue by aaronraimist** [wireapp/wire-ios#2645]
## Checklist (please check before submitting)

* [x] I checked the existing issues, and the issue was not reported before.

## The problem

Attempted to login. After my password was accepted I was brought to the screen below. The first time I logged in it was *slightly* more scrolled up than this but I still couldn't see any buttons. I force quit and tried to login again and got to this screen:

## Environment

* Wire version that exhibits the issue: 3.19 from the App Store
* Last Wire version that did not exhibit the issue (if applicable): I don't know
* iOS version used to run Wire: iOS 12 developer beta 12
* iOS device type: iPhone X
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): Wi-Fi

## Screenshots

![img_8924](https://user-images.githubusercontent.com/5855073/45260077-af2f8100-b3a2-11e8-8ba6-517fc9f93528.png)

**Comment by mikeger** [comment]
@aaronraimist please try the version 3.21 that just became available on the AppStore.

**Comment by aaronraimist** [comment]
Thanks, this issue seems to be fixed. Opened #2759.
