### ISSUE TITLE
The orange heart emoji is not big

### ISSUE THREAD

**Issue by ilianaw** [wireapp/wire-ios#2647]
## Checklist (please check before submitting)

* [x] I checked the existing issues, and the issue was not reported before.

## The problem

The orange heart emoji is inconsistently small when sent as its own in a message.

## Environment

* Wire version that exhibits the issue: 3.20 (3083)
* Last Wire version that did not exhibit the issue (if applicable): none
* iOS version used to run Wire: iOS 12 beta (latest at time of writing)
* iOS device type: iPhone 8
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): N/A
* Exact date, time and timezone (only for the crash issues): N/A

## Details

The orange heart emoji is not big when sent on a line on its own.

🧡 https://emojipedia.org/orange-heart/

Presumably whatever determines making emoji bigger does not think 🧡 is an emoji.

Oddly, other emoji from [Unicode 10.0](https://emojipedia.org/unicode-10.0/) is big (I tested [star-struck](https://emojipedia.org/grinning-face-with-star-eyes/), [giraffe](https://emojipedia.org/giraffe-face/), and [curling stone](https://emojipedia.org/curling-stone/)).

## Screenshots

Three separate messages, one emoji each:

![](https://user-images.githubusercontent.com/52814/45339371-1e45da80-b547-11e8-8d20-7706db1c65e1.jpg)

**Comment by billypchan** [comment]
Hi @ilianaw, thank you for your report and we will fix the logic to detect Emoji 5.0 emojis.

**Comment by billypchan** [comment]
The fix will be included in next release.
