### ISSUE TITLE
Mesh networking / Multipeer iOS 7+ support

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#272]
It would be interesting to support the Mesh networking / Multipeer iOS 7+  feature (https://developer.apple.com/reference/multipeerconnectivity).

**Comment by mikeger** [comment]
Hey @IpsmLorem ! Thanks for the suggestion. @raphaelrobert can reply on that one.

**Comment by raphaelrobert** [comment]
It is an interesting thought. That particular technology would be limited to iOS though. We are looking into something more multi-platform.

**Comment by jenskasemets** [comment]
Dear @IpsmLorem,

I'm closing this issue now, as we are not planning to implement any platform specific solutions that other platforms (users) can't get any benefits.
