### ISSUE TITLE
Security enhancements

### ISSUE THREAD

**Issue by ghost** [wireapp/wire-ios#275]
Touch ID / passcode lock for app after it's closed or after a set duration since it was last opened.

Hide app contents in recent apps switcher

**Comment by ajkblue** [comment]
Yes, this is standard across many of the top encryption apps, both having Touch ID support and hiding the app screen contents in the app switcher.

**Comment by mikeger** [comment]
Hey @notagithubuser, @ajkblue ! Thanks for the suggestion, we are looking into this features for our client. We'll inform you when those features would be scheduled. 

Hiding app contents in switcher sound like a something that can be done by external contributor, since the change is quite small.

**Comment by jenskasemets** [comment]
This behaviour is now implemented in release 2.30
