### ISSUE TITLE
Login on iPhone SE not possible

### ISSUE THREAD

**Issue by thenktor** [wireapp/wire-ios#2752]
Hi,

login on iPhone SE is not possible. After entering e-mail and password the "you are using wire the first time on this device" screen is shown but it does not fit on screen, so there is no OK button tp proceed.
If Wire is killed and started again, the login screen is shown again.

## Environment

* Wire version that exhibits the issue: current version from app store
* iOS version used to run Wire: 12
* iOS device type: iPhone SE

## Screenshot
![img_20181003_114907](https://user-images.githubusercontent.com/371714/46404690-3ce26000-c706-11e8-9356-c198d3b76723.png)

**Comment by mikeger** [comment]
Fixed in release 3.21.
