### ISSUE TITLE
The Character '。' (no quote mark) is replaced by another character when the message only consists of itself, which makes the message illegible

### ISSUE THREAD

**Issue by AndreaVEH** [wireapp/wire-ios#2764]
## Checklist (please check before submitting)

* [x] I checked the existing issues, and the issue was not reported before.

## The problem

The Character '。' (no quote mark) is replaced by another character when the message only consists of itself. And when the dark theme is turned on, the message is illegible. And the messages sent before current version also have been replaced.

## Environment

* Wire version that exhibits the issue: 3.21(3091)
* Last Wire version that did not exhibit the issue (if applicable): 3.20
* iOS version used to run Wire: iOS 12.0
* iOS device type: iPhone SE & iPhone X🅂
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): Wi-Fi
* Exact date, time and timezone (only for the crash issues): 

## Details

Send a message consist of any number of character '。‘(no quote mark)

## Screenshots

![img_0121](https://user-images.githubusercontent.com/7317368/46582162-84a21800-ca75-11e8-813e-de1d6662c590.jpg)
![img_0120](https://user-images.githubusercontent.com/7317368/46582163-8a97f900-ca75-11e8-98b2-8992073610b3.jpg)

**Comment by AndreaVEH** [comment]
Hello. I have done some research. The replaced character '。' is "Ideographic Full Stop", its Unicode value is U+3002. Hope this information can help.

**Comment by AndreaVEH** [comment]
Hello, @mikeger . Please have a check about this problem.

**Comment by mikeger** [comment]
Hey @AndreaVEH ! Sorry, must have missed the initial report. May be @johnxnguyen can help with that one? May be we consider it for some reason the Markdown list by mistake?

**Comment by billypchan** [comment]
Hi @AndreaVEH! This issue is fixed in the next version. Thanks for the report!
