### ISSUE TITLE
Strange footband appear when switching app on iOS

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#2788]
## Checklist (please check before submitting)

* [X ] I checked the existing issues, and the issue was not reported before.

## The problem

Strange footband appear when switching app on iOS

## Environment

* Wire version that exhibits the issue: 3.21 (3091)
* Last Wire version that did not exhibit the issue (if applicable): ?
* iOS version used to run Wire:12.0.1
* iOS device type: iPhone SE
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): N/A
* Exact date, time and timezone (only for the crash issues):  N/A

## Details

When switching app on iOS, Wire displays a strange footband screen.
Is this a bug ? What is the prupose ?

I never saw anything like that.

## Screenshots

![2018-10-13 10 54 54](https://user-images.githubusercontent.com/1250795/46905863-0c66a700-cefa-11e8-9c3b-70b8ceea4184.png)

**Comment by IpsmLorem** [comment]
> Hey @IpsmLorem ! I believe this is something that iOS is offering as the `handoff` function from another device. Have you tried clicking it?

I did: it launches Wire app.

**Comment by alexaubry** [comment]
Hey @IpsmLorem, this banner is an automatic recommendation from iOS based on your location and time. We don't have any control over it.

**Comment by IpsmLorem** [comment]
Fixed by disabling the Siri App suggestion widget.
