### ISSUE TITLE
Can't send large-size photos using the camera button

### ISSUE THREAD

**Issue by ilianaw** [wireapp/wire-ios#2789]
## Checklist (please check before submitting)

* [x] I checked the existing issues, and the issue was not reported before.

## The problem

Tapping the camera button (lower left), taking a *complex* photo using the built-in camera view, and hitting OK results in an attachment that never successfully uploads.

## Environment

* Wire version that exhibits the issue: 3.22 (3100)
* Last Wire version that did not exhibit the issue (if applicable): 3.21 (3091) -- unsure if this was an issue in 3.22 (3099)
* iOS version used to run Wire: iOS 12.0.1
* iOS device type: iPhone 8
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): n/a
* Exact date, time and timezone (only for the crash issues): n/a

## Details

* Tap the camera button in a conversation
* Take a photo using the built-in camera view; don't tap the expand icon. (To trigger the bug the photo appears to need to be over a size threshold; taking focused photos of my computer screen (causing moiré) triggers the bug, but taking a photo of a solid-color wall does not.)
* See the preview, hit OK
* A small rectangle that I believe is usually used for attachments displays and the attachment never sends

## Screenshots

The two photos taken here are a blurry shot of my screen, and a focused shot of my screen. The blurry shot does not have a moiré and thus the photo likely compressed better.

![img_3039](https://user-images.githubusercontent.com/52814/46921223-7d1acb80-cfad-11e8-94c0-13689e09dc0e.PNG)

**Comment by mikeger** [comment]
Hey @ilianaw ! Thanks for the report, we are working on the fix.

**Comment by mikeger** [comment]
Hey @ilianaw ! This must be fixed now, can you confirm?

**Comment by ilianaw** [comment]
This appears fixed on 3.22 (3105).
