### ISSUE TITLE
Calls seem to override alarms

### ISSUE THREAD

**Issue by iliana** [wireapp/wire-ios#2798]
## Checklist (please check before submitting)

* [x] I checked the existing issues, and the issue was not reported before.

## The problem

When in a call, alarms don't go off.

## Environment

* Wire version that exhibits the issue: 3.22 (3100)
* Last Wire version that did not exhibit the issue (if applicable): unsure
* iOS version used to run Wire: iOS 12.0.1
* iOS device type: iPhone 8
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): Wi-Fi
* Exact date, time and timezone (only for the crash issues): n/a

## Details

Last night I was in a call when both of the callers fell asleep. We've done this before, but ordinarily calling problems would disconnect the call well before we both woke up, or the other caller (on Android, which doesn't seem to have this issue) would wake up first. (Call stability definitely appears to be improving! :tada:)

I had the "bedtime" alarm enabled to go off at 06:35 but I woke up at about 06:50, when I hit the power button on my phone. The phone screen woke up, very briefly showed the screen that displays when the alarm is going off, and appeared to snooze it. At no point until after I hung up the call did the alarm actually go off.

There is sleeping involved in this report so I might have dreamt all this.

## Calling Debug logs (only for calling issues)

Sending as soon as I submit this but I'm not sure it'll help.

**Comment by ilianaw** [comment]
I actually do have CallKit disabled, since I find the iOS call UI wildly unhelpful :)

**Comment by ilianaw** [comment]
I'll see if I can trivially reproduce this evening (US Pacific time) with my partner. I have a theory that sleep is not a required element of this bug.
