### ISSUE TITLE
Significantly downgraded performance in chats with large history

### ISSUE THREAD

**Issue by Dexwell** [wireapp/wire-ios#2807]
## Checklist (please check before submitting)

* [X] I checked the existing issues, and the issue was not reported before.

## The problem

When sending a message in a chat with a large chat history (probably thousands of regular messages (don't know how to look this up), 1000+ pictures, 360+ videos, 100+ links), the UI hangs for sometimes up to 8 seconds. This is really unworkable, and unacceptable on the latest and fastest iPhone models. Sending a message to someone I don't speak as much works as fast as intended. 

## Environment

* Wire version that exhibits the issue: Latest versions, for months
* Last Wire version that did not exhibit the issue (if applicable): n/a
* iOS version used to run Wire: 12.0.1 
* iOS device type: iPhone X, iPhone XS
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): LTE, Wi-Fi

## Details

- Try recreating a chat described above, and sending a message

**Comment by Dexwell** [comment]
@mikeger Good to hear!

**Comment by theranger** [comment]
Seems to be a duplicate of #2578.

**Comment by Dexwell** [comment]
@mikeger It's been 2 months; any ETA? 🖤

**Comment by Dexwell** [comment]
Thanks so much for fixing this in the latest release; it makes a night and day difference! 🎉You can also close https://github.com/wireapp/wire-ios/issues/2578.

**Comment by kyle-fox** [comment]
Congrats @mikeger and the rest of the team - this update was a massive improvement! 🎉
