### ISSUE TITLE
2018 iPad screen sizes seem unsupported

### ISSUE THREAD

**Issue by jcredmond** [wireapp/wire-ios#3053]
## Checklist (please check before submitting)

* [X] I checked the existing issues, and the issue was not reported before.

## The problem

It doesn't look like Wire supports the new 2018 iPad sizes. On my 2018 12" iPad Pro, there is a black bar at the top of the app, resulting in unused screen space. The app should use all of the space up to the status bar -- the unused blank space looks bad.

## Environment

* Wire version that exhibits the issue: latest
* iOS version used to run Wire: 12.1.1
* iOS device type: 2018 12" iPad Pro

![img_b0b7a6871bf7-1](https://user-images.githubusercontent.com/4458771/50215414-3a95b680-0383-11e9-8aa0-41623115d771.jpeg)

**Comment by jcredmond** [comment]
@billypchan just run wire on one of the 2018 iPads. That's all you need to do. It's broken by default.

**Comment by jcredmond** [comment]
@billypchan unless you're doing something manual with constraints, the fix should be to compile with the iOS 12.1 SDK if you're not already.

**Comment by typfel** [comment]
@jcredmond we hope to release with the iOS 12.1 SDK in the next version. Switching Xcode versions involves some manual work for us that's why it hasn't happened yet.

**Comment by jcredmond** [comment]
The latest version released today (3.26) still has this issue. I thought you'd want to know just in case you actually did build with 12.1.

**Comment by jcredmond** [comment]
This seems to be fixed with the last couple of releases.

**Comment by alexaubry** [comment]
Yes, iOS 3.28 has support for the new iPad models. Thanks for your patience!
