### ISSUE TITLE
Deleting all messages in a group chat  removes it from the conversation list

### ISSUE THREAD

**Issue by abjbhat** [wireapp/wire-ios#3146]
## Checklist (please check before submitting)

I checked the existing issues, and the issue was not reported before.

## The problem

If you try to delete all messages in a group chat, the group is removed from the conversation list. This doesn't remove you from the group though.

## Environment

* Wire version that exhibits the issue:
* Last Wire version that did not exhibit the issue (if applicable): Unknown
* iOS version used to run Wire: 12.1.3
* iOS device type: iPhone or iPad
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): Wifi and LTE
* Exact date, time and timezone (only for the crash issues): not applicable

## Details

1. Navigate the details view of a group chat.
2. Press/tap on the three horizontal dots in the lower right corner of the view
3. Select "Delete" from the menu that pops up.
4. The app then takes you the conversation list view 
5. The group is removed from the conversation list view
6. Now you can't send messages to the group.
7. If the user has other devices, on the other devices, an empty group chat with no title and no chat content appears. This was tested on the latest Windows desktop and iPad clients.
8. If another participant of the group sends you a message, the group will reappear.

The intention of the user was not to delete and exit the group. It was to merely clear the contents of the conversation. Therefore, the delete option works as delete and leave.

**Comment by billypchan** [comment]
Hi @abjbhat, thanks for the reporting. We have a fix for the empty group issue in the release.
