### ISSUE TITLE
When tapping an old search result in history, Wire stops responding

### ISSUE THREAD

**Issue by Dexwell** [wireapp/wire-ios#3156]
## Checklist (please check before submitting)

* [X] I checked the existing issues, and the issue was not reported before.

## The problem

When searching my (large) chat history and tapping a result from e.g. May 2018, the modal closes and then the app stops responding until I force close it.

## Environment

* Wire version that exhibits the issue: All latest versions, for a while now
* Last Wire version that did not exhibit the issue (if applicable): Not sure, before Direct Replies though
* iOS version used to run Wire: 12.1.2
* iOS device type: iPhone XS
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): LTE, Wi-Fi

**Comment by billypchan** [comment]
We had a lot of fixes and improvements and I can not reproduce this issue and I close this issue.
