### ISSUE TITLE
Delivery status inconsistency between iOS and desktop

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#316]
I sent a message on the Wire desktop V2.10.2652 and the delivery status of the message was "Delivered".
When I seen on the iOS version (V2.18), it says : "Sent".

Expected: same delivery satus between devices.

When I send a media on iOS version, it says "Delivered". On the desktop one, the status is not even updated. Only the previous message says "Delivered".

**Comment by KoalaBoomka** [comment]
Hi, @IpsmLorem! For me it works fine between Wire 2.10.2652 on macOS and iOS Wire 2.18.2669

**Comment by KoalaBoomka** [comment]
Maybe, you had some additional conditions: phone was offline when you communicated from desktop? Or desktop was sleeping when you send message from a phone?

**Comment by IpsmLorem** [comment]
My iPhone was just locked in front of me. Opening the deviced shoudl haved updated the status of messages (or even background refreshed them)

**Comment by KoalaBoomka** [comment]
Works fine on the test devices with the described conditions.

**Comment by IpsmLorem** [comment]
I will try to post a way to reproduce it, if that happend again.

**Comment by KoalaBoomka** [comment]
Thanks!

**Comment by IpsmLorem** [comment]
It happends often.
This time I experienced a messaged sent from desktop which was displayed as delivered on iOS but not on the Wire desktop. 
* On iOS:
![ios](https://cloud.githubusercontent.com/assets/1250795/19830191/bd614f0a-9df2-11e6-9e21-61b0d2779e4d.png)
* On Desktop/Web:
![desktop](https://cloud.githubusercontent.com/assets/1250795/19830192/bd6475b8-9df2-11e6-8e9c-34afbb93d0c1.png)
