### ISSUE TITLE
Feature: Ability to open links in Firefox Focus (Firefox Klar)

### ISSUE THREAD

**Issue by rm-rf-home** [wireapp/wire-ios#3182]
## Checklist (please check before submitting)

* [X] I checked the existing issues, and the issue was not reported before.

## The problem

It's brilliant that opening Links in Firefox, Brave and SnowHaze is already supported. As I use Firefox Klar as my primary browser on iOS (called Firefox Focus in non-German speaking countries), it would be nice to be able to choose this browser for opening links in Wire.

## Environment

* Wire version that exhibits the issue: 3.26 (3150)
* iOS version used to run Wire: 12.1.4 (16D57)
* iOS device type: iPhone 7
* Installed Browser: Firefox Klar 8.0 from German App Store

## Details

Under "Options - Browser" a list of browsers is supported already for opening links. Firefox Focus (Firefox Klar) support is not yet implemented.

It looks like the "Focus iOS open in client"-reference by Mozilla is empty: https://github.com/mozilla-mobile/focus-ios-open-in-client

## Screenshots

![img_2013](https://user-images.githubusercontent.com/36776420/52535556-b985ea80-2d47-11e9-9408-5cab8e946248.jpeg)
![img_2014](https://user-images.githubusercontent.com/36776420/52535557-bbe84480-2d47-11e9-86cb-b30243d33fd4.jpeg)

**Comment by billypchan** [comment]
Hi @rm-rf-home, thanks for your suggestion. We will discuss with our team to updated our browser support list.

**Comment by rm-rf-home** [comment]
Hello @billypchan, 

cool thanks. I saw in another implementation, that "Firefox Focus" and "Firefox Klar" were implemented separately because of the different names, even though it's practically the same browser - https://support.mozilla.org/en-US/kb/difference-between-firefox-focus-and-firefox-klar

In order to open wire.com in Firefox Focus or Firefox Klar on an iOS device the following internal link tags can be used:
- firefox-focus://open-url?url=https://wire.com/
- firefox-klar://open-url?url=https://wire.com/
