### ISSUE TITLE
Header 'WireSyncEngine-Swift.h' not found

### ISSUE THREAD

**Issue by michaeldong** [wireapp/wire-ios#3227]
## Checklist (please check before submitting)

Checked, not found same isssue!

## The problem

Can't run project  branch of  'develop'

## Environment

Xcode Version 10.1 (10B61)
Toolchain: Swift 4.2.1 Release 2018-10-30 (a)

## Details

error:
Header 'WireSyncEngine-Swift.h' not found
Could not build module 'WireSyncEngine'
Umbrella header 'WireRequestStrategy.h' not found

ReadMe said support Xcode10.1 , but.....may be not ?

## Screenshots

![image](https://user-images.githubusercontent.com/1925773/53623369-da02df80-3c37-11e9-833b-b6c82ee9d1d8.png)

**Comment by alexaubry** [comment]
Hello! Did you run `./setup.sh` before trying to build the project?

**Comment by michaeldong** [comment]
Now it's works.
