### ISSUE TITLE
Messages written with Markdown have display problems.

### ISSUE THREAD

**Issue by 353243186** [wireapp/wire-ios#3237]
## Checklist (please check before submitting)

* [ ] I checked the existing issues, and the issue was not reported before.

## The problem

When I write a Chinese message in Markdown, the word spacing for the newline is too small.

## Environment

* Wire version that exhibits the issue:3.24-3.29
* Last Wire version that did not exhibit the issue (if applicable):
* iOS version used to run Wire:12.1.4
* iOS device type: iPhone XS  Max
* Mobile network type (EDGE/LTE/Wi-Fi/Offline):Wi-Fi
* Exact date, time and timezone (only for the crash issues): 

## Details

When I write a Chinese message in Markdown, the word spacing for the newline is too small.

## Screenshots

<img width="387" alt="wx20190308-182913 2x" src="https://user-images.githubusercontent.com/13417472/54023519-1b633400-41d0-11e9-9f3f-3eb80ecee7c2.png">

**Comment by 353243186** [comment]
<img width="391" alt="wx20190308-184728 2x" src="https://user-images.githubusercontent.com/13417472/54024416-b52be080-41d2-11e9-93fb-84cfa3eb0028.png">

**Comment by billypchan** [comment]
Hi @353243186, thanks for your report and we will check this issue.

**Comment by billypchan** [comment]
fixed in https://github.com/wireapp/wire-ios/pull/3481
