### ISSUE TITLE
Upgrade to XCode 10.2 and Swift 5

### ISSUE THREAD

**Issue by crystalztl** [wireapp/wire-ios#3292]
## Checklist (please check before submitting)

* [x] I checked the existing issues, and the issue was not reported before.

## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Wire).
Tell us what you were trying to do and what happened instead.

## Environment

* Wire version that exhibits the issue:
* Last Wire version that did not exhibit the issue (if applicable):
* iOS version used to run Wire:
* iOS device type: 
* Mobile network type (EDGE/LTE/Wi-Fi/Offline):
* Exact date, time and timezone (only for the crash issues): 

## Details

Describe the steps necessary to reproduce the problem in more details. The detailed description
will help us to fix the issue faster.

## Calling Debug logs (only for calling issues)

0. You have to have the iOS email client set up.
1. Reproduce the issue.
2. Go to Settings -> Advanced -> Calling Debug Report.
3. Send the report.

## Screenshots

Please attach screenshots if you consider them as helpful to understand/reproduce the issue.

**Comment by crystalztl** [comment]
Any Plan?

**Comment by billypchan** [comment]
Hi @crystalztl thanks for your comment and we are working on that.

**Comment by billypchan** [comment]
It is merged to the develop branch.
