### ISSUE TITLE
Static and bigger sending button on iOS

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#332]
It would be easier to have a static all height long sending button (like a box) on iOS.
When writing a a several lines message, the button is moving up and the thumb fails to reach it.
![cap](https://cloud.githubusercontent.com/assets/1250795/19656485/7fa20928-9a20-11e6-9307-146bdf4671a1.png)

**Comment by KoalaBoomka** [comment]
@IpsmLorem,
thanks for the suggestions. This is really nice to have it pinned to the bottom of the input field from the usability point of view.

**Comment by jenskasemets** [comment]
Hello, @IpsmLorem,

This change was now in yesterday's release: 2.26
