### ISSUE TITLE
iPad version doesn't support the dark theme

### ISSUE THREAD

**Issue by jcredmond** [wireapp/wire-ios#3325]
iPhone and Desktop both support the dark theme. iPad does not.

**Comment by billypchan** [comment]
Hi @jcredmond, dark theme for iPad feature is already done(https://github.com/wireapp/wire-ios/pull/3357). Stay turn for next release!

**Comment by jcredmond** [comment]
What version and where should the setting be? 3.34 released today doesn’t have it.
