### ISSUE TITLE
Incorrect time display for message edition

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#333]
When editing a message, the timestamp is incorrect on iOS.

The tooltip on Wire desktop display "Edited on 19:30" for exemple and on iOS it displays "Edited on 16:23" which is the creation time.

**Comment by KoalaBoomka** [comment]
hi, @IpsmLorem! 
We really appreciate your collaborative spirit. This is a known issue. We will fix it in the future according to our priorities.

**Comment by KoalaBoomka** [comment]
This issue is fixed in 2.23
