### ISSUE TITLE
Feature: further picture editing before sending

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#335]
Right now, one can draw on a picture before sending. It would be interesting to be able to write some text (with emoji) on top of it too.
For exemple, people would be able to draw an arrow to focus the recipient attention and add some text to the arrow to give some explanation.

**Comment by david-wire** [comment]
Hello, thanks for the suggestion. We are actually working on that, so please stay tuned!

**Comment by cwmke** [comment]
Did this ever get implemented for IOS? I know it works on Android but I don't see the option on IOS.

**Comment by mikeger** [comment]
Hey @cwmke ! It is possible on the iOS client, on the picture confirmation screen you have 2 buttons on the bottom: with emoji and sketch icons. You can press any of them to apply emojis or sketch. Editing persists, so you can add both.

**Comment by cwmke** [comment]
Thanks for the response @mikeger but the part I was thinking of is mentioned below. The text bubble is present on Android but not IOS as far as I can tell. I used it quite a bit on Android so I'm wondering if this is or will be added later on?

`It would be interesting to be able to write some text (with emoji) on top of it too.`

**Comment by mikeger** [comment]
Hey @cwmke ! Sorry to say that, but unfortunately this is not something we have on our immediate timeline. You can get around with it by using the third-party app and copy-paste feature. Thanks for using Wire!
