### ISSUE TITLE
Timed messages doesn't "sync" accros devices

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#336]
Step to reproduce:
* send a 1day timed message from Wire iOS 5.4.0 to another recipient (with two devices)

Expected: the other sender device (Wire desktop 2.10.2653 on Windows x64) shoudl display the sent message. It doesn't.
The same thing happen if the message is sent from desktop, it is not displayed on the iOS device.

**Comment by KoalaBoomka** [comment]
hi, @IpsmLorem !
Congratulations! You discovered part of the ephemeral messages feature. Wire doesn't send your timed messages to the other own devices. Isn't it beautiful?

**Comment by IpsmLorem** [comment]
Well, I don't know if it's a good or bad news. I should wrap my mind arount that ! 
But all recipients devices receive them, right ?
Like that:
![wire](https://cloud.githubusercontent.com/assets/1250795/19720040/c1fa400e-9b6c-11e6-81cf-09c946e27b52.png)

Was the point to have the timed message with the few possible copy stored on device ?

**Comment by KoalaBoomka** [comment]
This is how we designed it. Thank you for your feedback.

**Comment by IpsmLorem** [comment]
Good to know this is a feature and not a bug ;)

**Comment by IpsmLorem** [comment]
I think, with longer retention policy, a full synced would have their meaning though.
This way, users would have both a tidy storage and the possibilty of followed up conversations.
