### ISSUE TITLE
Feature: be able to select prefered language

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#337]
It would be interesting to be able to chose their prefered language, even if it's not the system default iOS one.

**Comment by david-wire** [comment]
Hi, no plans to do that at the moment, but thanks for the suggestion.

**Comment by jenskasemets** [comment]
Hi @IpsmLorem, as @david-wire mentioned above, we don't have plans to introduce such option. Apple suggests not to do it, and always use language and region setting set for the device by user. I'm closing this issue right now, but feel free to comment here with exact scenario why it would be needed.
