### ISSUE TITLE
Build failing - unable to find script

### ISSUE THREAD

**Issue by jhowlin** [wireapp/wire-ios#34]
I am getting a build error: /Users/jhowlin/Library/Developer/Xcode/DerivedData/Wire-iOS-ecdpwnfcaxnytafmddffiuirmvlg/Build/Intermediates/Wire-iOS.build/Debug-iphonesimulator/Wire-iOS.build/Script-8795A5D21D34D1A50024101B.sh: line 2: /Users/jhowlin/Documents/xcode: No such file or directory

Suggestions?

**Comment by mikeger** [comment]
Hey @jhowlin thanks for reporting the issue! Please give the more detailed Xcode log along with your Xcode version. In particular, can you say what's the build step name where this script is executed, or alternatively when you see this error, read the contents of failing script and send it to us?

**Comment by jhowlin** [comment]
Thanks. It looks like the EmbedBuildInfo script. Here's what it looks like: #!/bin/sh
${SRCROOT}/Scripts/embedBuildInfo --output ${SRCROOT}/Wire-iOS/ComponentsVersions.plist

It looks like it compiles everything ok, just fails here during the linking phase.

[log.txt](https://github.com/wireapp/wire-ios/files/389278/log.txt)

**Comment by mikeger** [comment]
It works for me and on [Travis](https://travis-ci.org/wireapp/wire-ios), I am guessing that you are having some corner-case permission error. I would advise to try to re-checkout and run ./setup.sh again.
In the worst case you can disable this one, it's not mandatory for the build. It's purpose is to include the components version information into the application, but it can also run without.
Hope it helps.

**Comment by jhowlin** [comment]
I went ahead and disabled it, as well as the 'strip bit code' and 'copy extra audio notifications' scripts. Not sure why it was having problems. Anyway, building and running now. Thanks!
