### ISSUE TITLE
Wire permanently frozen with no escape :-(

### ISSUE THREAD

**Issue by midnightmagic** [wireapp/wire-ios#3424]
## Checklist (please check before submitting)

* [ x ] I checked the existing issues, and the issue was not reported before.

## The problem

Attempting to upload an animated GIF as a file, from my filestore which is 3.2MB has completely frozen my Wire app in the "uploading..." state and there is no way to escape.

## Environment

* Wire version that exhibits the issue:
Current Wire in the Apple Store as of yesterday

* Last Wire version that did not exhibit the issue (if applicable):
No idea. I haven't tested anything earlier because I'm hoping that a bugfix will save my iOS conversation history.

* iOS version used to run Wire:
* iOS device type: 
* Mobile network type (EDGE/LTE/Wi-Fi/Offline):
* Exact date, time and timezone (only for the crash issues): 

# Details

When in conversation with someone, it is possible to upload a file on iOS from the file store. If the file is 3.2MB and is itself an animated GIF format (I'm guessing here) it's possible to get Wire in a state where it is just continually uploading forever, and no buttons are at all responsive on the Wire screen. Rebooting the phone doesn't help. Restarting the app doesn't help. Updating the app to the latest version doesn't help. I don't want to delete the app and reinstall because I don't want to lose my conversation history.

## Calling Debug logs (only for calling issues)

0. You have to have the iOS email client set up.
1. Reproduce the issue.
2. Go to Settings -> Advanced -> Calling Debug Report.
3. Send the report.

**Comment by billypchan** [comment]
Hi @midnightmagic, thank you for your report. I can reproduce this issue and we will fix it soon.

**Comment by midnightmagic** [comment]
That is because you are awesome. Thank you kindly.

**Comment by billypchan** [comment]
fixed in https://github.com/wireapp/wire-ios-data-model/pull/732
