### ISSUE TITLE
Trojan Malware found

### ISSUE THREAD

**Issue by bayareahank** [wireapp/wire-ios#343]
After downloading and installing wire-ios on my Mac, I started to experience browser hijacking, the famous satisfaction-survey.org malware. Then I downloaded Kaspersky total security and run against my mac, which is a pretty clean dev box, such a Trojan found: 

wire-ios/Carthage/Checkouts/wire-ios-data-model/Source/Model/Message/ZMMessage.m  
Trojan.BAT.FormatD.I

Whether my browser hijacking is definitely from wire-ios, I am not 100% sure, as I also downloaded a few other open source swift projects and the dependent tools. Yet this warning from Kaspersky is true. 

Hope you guys can investigate it.

**Comment by marcoconti83** [comment]
Hi @bayareahank, thanks for checking out our source code!
The file detected by your antivirus is part of the source code for the iOS version. The code is not executable as is, you need to compile it with XCode. Even after you do that, the resulting app will only run on an iPhone or iPad device (well, you can also run in in the XCode simulator, but that's only if you are actively developing or testing it, and it will have limited access to your system). It is not possible to run that code on the Mac.

As such, I am positive that our iOS source code has nothing to do with the browser hijacking on the Mac.  So it's either a false positive, or a more complex situation. 

Here is my suggestion:
- Check the original source file [here](https://github.com/wireapp/wire-ios-data-model/blob/develop/Source/Model/Message/ZMMessage.m), this is the original source file that is used to compile our application, and compare it with the local file on your Mac that is flagged by your antivirus. They should have the same content.
   - If the files have the same content, it's a false positive. Please send a report to the vendor of your antivirus by attaching the file and the detection message. They will then review their detection algorithm to avoid this kind of situations in the future.
   - If the files don't have the same content, then something must have tampered with the version on your computer. I would look for the differences on your local version to understand if something injected malicious code in it (this might give you an hint of what kind of malware did that), then run a full scan of your Mac to figure out if you have any malware/virus that might be responsible for it.

Hope this helps!
