### ISSUE TITLE
When try to compile wire ios Xcode, An invalid value 'group.' was provided for the parameter 'identifier'.

### ISSUE THREAD

**Issue by jsdev2018** [wireapp/wire-ios#3474]
When try to compile in code.  When automatic manage profile in Xcode Version 9.3 (9E145).  

Get: 

An invalid value 'group.' was provided for the parameter 'identifier'.

Provisioning profile "iOS Team Provisioning Profile: *" doesn't include the aps-environment,
com.apple.developer.associated-domains,
com.apple.developer.icloud-container-development-container-identifiers,
com.apple.developer.icloud-container-identifiers,
com.apple.developer.icloud-services,
com.apple.developer.ubiquity-container-identifiers,
com.apple.developer.ubiquity-kvstore-identifier,
and com.apple.security.application-groups entitlements.

**Comment by billypchan** [comment]
Hi @jsdev2018, our project supports Xcode 10.2.1 and would you try updating Xcode?

**Comment by jsdev2018** [comment]
Got it!
