### ISSUE TITLE
Feature: adding more time policies for timed messages

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#351]
When your messages are not so sensitive but still want to enforce a message cleaning policy on your recipients devices, a one week policy could be useful for timed messages.

Would be even more usefull if Wire full synced time messages (i.e. #336 )

**Comment by 0ki** [comment]
Timed messages are not suitable for enforcing anything. Wire should be more honest about that with their users.

**Comment by raphaelrobert** [comment]
@IpsmLorem: Thanks for the suggestion. It is something we considered initially, but we decided to keep it the maximum of 1 day. Depending on the demand we might reconsider.

@0ki: This is true, it is a question of common sense. We are confident that users know that.

**Comment by 0ki** [comment]
I am sure that you are mistaken, @raphaelrobert. It is not a question of common sense, but rather a question of being intimate enough with technology to understand the technological implications.

There you go → #392

**Comment by raphaelrobert** [comment]
Agreed, not every user is familiar with all the technical implications. What I meant was that even if the remote deletion was actually guaranteed to work, users would still understand the risk that the recipient takes a picture of the screen (simply with a camera for example). That's what I meant with common sense.

**Comment by IpsmLorem** [comment]
@raphaelrobert 1 week policy is veryuseful to still have long conversation and keep history clean

**Comment by AJolly** [comment]
I'd support this.  Wickr supports up to a week.

**Comment by marcoconti83** [comment]
We added timing options for messages up to one week. You can find this in any recent version of the app.

**Comment by 0ki** [comment]
4 weeks.
