### ISSUE TITLE
Cannot archive one of my discussion on iOS

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#352]
One of my discussion cannot be archived on iOS. When I archive it, it disappears from live discussions but is not listed in archived one.
When I look at the desktop/web app, the discussion is still listed as lived one.
Back on iOS, when I go to "contact icon", select the contact and tap on "Open", the discussion is displayed back on live discussion.

When I archive it on web app/desktop one: the discussion is removed on both version of lived discussions and is correctly listed in archived one.

**Comment by KoalaBoomka** [comment]
Hi, @IpsmLorem! Thanks for reporting an issue.

**Comment by jenskasemets** [comment]
@IpsmLorem we made a small change possibly also related to this bug, please try to reproduce and let us know if this still happens or not.

**Comment by jenskasemets** [comment]
Hello, @IpsmLorem,

I'm closing this issue now, please re-open if happens again.
