### ISSUE TITLE
Wire doesn't open under iOS 13 dev beta 3

### ISSUE THREAD

**Issue by DigitalJEM** [wireapp/wire-ios#3525]
## Checklist (please check before submitting)

* [X] I checked the existing issues, and the issue was not reported before.

## The problem

The App opens and then force closes/crashes. I tap the icon on the screen, sometimes the app will crash/force close at the wire logo screen, other times it will make it to my message history and then crash there.

I started noticing this issue after upgrading to iOS 13 beta, before joining the Wire testflight. I do not recall the version I was running prior to 3.38 (3871). But the same issue was present before joining testflight (I had hopes that the testflight version would fix)

## Environment

* Wire version that exhibits the issue: 3.38 (3871)
* Last Wire version that did not exhibit the issue (if applicable):
* iOS version used to run Wire: 13 beta 3
* iOS device type: XS MAX
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): LTE / Wi-Fi
* Exact date, time and timezone (only for the crash issues): 7/9/19 @ 02:38 PST

## Details

To reproduce this issue, attempt to open the app in iOS 13 developer beta 3 (not public beta 3).

I have attempted to make sure the app is fully closed (swipe up from switcher) before relaunching and app still crashes/force closes.

## Calling Debug logs (only for calling issues)

0. You have to have the iOS email client set up.
1. Reproduce the issue.
2. Go to Settings -> Advanced -> Calling Debug Report.
3. Send the report.

I'm not able to get into the app to send the report. I can screen record the issue happening and email it to you if you provide somewhere for me to send it.

## Screenshots

Please attach screenshots if you consider them as helpful to understand/reproduce the issue.

**Comment by billypchan** [comment]
Hi @DigitalJEM, thanks for reporting this issue. We found this is an iOS 13 beta specific issue and will investigate it.

**Comment by feld** [comment]
This is fixed as of yesterday. It just suddenly started working and I received a bunch of backed up push notifications. I suspect there was a TLS issue between iOS and Wire's servers and someone changed the CA or cipher suites and now it's back.

**Comment by DigitalJEM** [comment]
I sadly do not have the same results.

After seeing Mark Felder's message I had hope. I resintalled Wire from the
testflight app. Logged in. Got a "too many devices" prompt. Deleted one of
my devices so I could use it on this device. Got to the contacts/groups
screen, tapped on a group and the app crashed instantly.

**Comment by happydude** [comment]
@DigitalJEM I noticed test flight has 3.38 for me vs 3.39 in the regular app store.

**Comment by DigitalJEM** [comment]
Thank you for the tip Jason. It appears that even 3.39 from the standard
AppStore is experiencing the same issue.

**Comment by billypchan** [comment]
I use Wire v3.40 with iOS 13 beta 5 and it is fine.

**Comment by DigitalJEM** [comment]
I just got prompted to install beta 5 today. I did so, and now Wire works
perfectly fine. It’s great to be back.

**Comment by DigitalJEM** [comment]
I spoke too soon. The app doesn't crash anymore (after installing beta 5).
However, now everytime I leave Wire (switch to another app) when I return
to Wire I am taken back to a login screen. And then walked through new
install setup flow.

**Comment by Skycoder42** [comment]
This might be related to #3641

**Comment by DigitalJEM** [comment]
Sorry, I must have forgot to send an update. My issue was resolved with the
update to iOS 13 beta 6. Now on iOS 13.1 and everything still working fine.
