### ISSUE TITLE
Liking messages doesn't reflect in UI on first launch or returning from background.

### ISSUE THREAD

**Issue by kyle-fox** [wireapp/wire-ios#3561]
## Checklist (please check before submitting)

* [ X ] I checked the existing issues, and the issue was not reported before.

## The problem

When opening the app at all, attempting to like a message in the viewable message area is not reflected in the UI, either through double tapping the message or tapping the heart. If you scroll the message offscreen and back onscreen, the like displays on the message as expected.

## Environment

* Wire version that exhibits the issue: 3.40
* iOS version used to run Wire: 12.4
* iOS device type: iPhone XS Max

## Details

- Open Wire
- Like any Message

Expected: Heart turns red.
Actual: Nothing happens.

- Scroll message offscreen.
- Scroll message onscreen.
- Heart is red, indicating like did register.

Can create a video if necessary!

**Comment by billypchan** [comment]
Hi @kyle-fox, thanks for your report. Would you provide more info, such as is it a newly created account? Is it a newly created conversation?

**Comment by kyle-fox** [comment]
@billypchan Account and the group conversation of 11 people are both a few years old. The group’s history on this device hasn’t been cleared in almost 2 years, with many thousands of messages, likes, images, links, etc. Not sure if this might be related to the DB write performance upgrades from a few months back. 

It’s not consistently reproducible at the moment, but it has been happening every day for a few versions of Wire now. I’ll try to nail down some more specific conditions for reproducing. Testing right now, the messages are now new, so they’ve been loaded already. The group is fairly active, so I believe another condition might be that this is happening for messages that have just been added to the UI after opening the app. 

Apologies for the close/reopen - hit the wrong button on my phone 🤦🏻‍♂️
