### ISSUE TITLE
App crashes when preparing the picture

### ISSUE THREAD

**Issue by orangesunny** [wireapp/wire-ios#3564]
iPad pro 11”
iOS 12.3.1
Steps to reproduce:
- Open the picture in the picture shared in the conversation
- Click sent icon below the picture
app crashes :(

**Comment by orangesunny** [comment]
sorry for the autocorrect in the issue name. There should be “resharing”

**Comment by billypchan** [comment]
hi @orangesunny, thanks for your report, I tried with a normal small image and it seems fine. Would you provide more information, such as the size/format of the image? Is it a 1-to-1 conversation or group conversation?

**Comment by billypchan** [comment]
I can not reproduce and close this issue.
