### ISSUE TITLE
Creating account by phone number or adding phone number to account crashes on iOS 12.4 

### ISSUE THREAD

**Issue by starrfish** [wireapp/wire-ios#3565]
## Checklist (please check before submitting)

* [ x] I checked the existing issues, and the issue was not reported before.

## The problem

When attempting to create a new Wire account by phone number, it crashes when entering the 6th digit of your phone number. Once your account is created by email, attempting to add your phone number still crashes the app completely when you reach the 6th digit. This has been confirmed on more than one device. 

## Environment

* Wire version 3.40
* Last Wire version that did not exhibit the issue (if applicable): N/A
* iOS version used to run Wire: 12.4 (16G77) NOT 12.5
* iOS device type: iPhone XS Max
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): WiFi & LTE
* Exact date, time and timezone (only for the crash issues): 8/4/19 9:15pm EDT 

## Details

Select to create a new account. Select phone number. Enter the first 6 digits of your phone number. On the 6th it completely crashes and returns to the home screen. The issue also occurs when attempting to add your phone number through account settings after your account has been created.

**Comment by billypchan** [comment]
Hi @starrfish, thanks for your report. We had started investigation for it.

**Comment by starrfish** [comment]
Wanted to add that if your phone number is available to select from auto fill text, selecting your number rather than typing leads to an immediate crash.

**Comment by whoyawn** [comment]
Attempting to sign in via phone number also crashes on the 6th digit. I'm on an XR on 12.4 using the app from the app store.

**Comment by billypchan** [comment]
resolved in next release.
