### ISSUE TITLE
Privacy and searching on Giphy

### ISSUE THREAD

**Issue by mat1th** [wireapp/wire-ios#361]
Hello, 
Today Signal has announced a privacy friendly Giphy search, So the search queries could not be saved by Giphy. See [signal blog](https://whispersystems.org/blog/giphy-experiment/). Would it't be a good idea to also implement this privacy feature? 

Thanks!

**Comment by marcoconti83** [comment]
Hi @mat1th , thanks for getting in touch. We will consider your suggestion.

**Comment by oscalation** [comment]
this is a great suggestion. Please consider

**Comment by jamestomasino** [comment]
Since Facebook has bought Giphy it's a high likilhood they intend to use tracking data from that source. Having a private alternative or implementing a private search & use for Wire is more important than ever. Can we raise the priority on this issue?

**Comment by jamestomasino** [comment]
This issue is being more directly addressed in the [main wire repo](https://github.com/wireapp/wire/issues/347):

**Comment by mat1th** [comment]
Because it is addressed in https://github.com/wireapp/wire/issues/347 I will close this issue.
