### ISSUE TITLE
Feature: Alternative signup / verification options

### ISSUE THREAD

**Issue by EgbertW** [wireapp/wire-ios#372]
A friend with a Chinese SIM-card tried to activate Wire while a stay in Europe, but was unable to do so because the SMS with the validation code never arrived. SMS messages hardly seem to be transferred into China, so a different solution would be helpful. Telegram for example offers a phone call as an alternative.

She then tried to create a account with an e-mail address using app.wire.com on her iPhone, but this webpage only shows a message that the Web App is unavailable on her platform. The iPhone app could be updated to support registration with an e-mail address instead of a phone number so avoid this hassle.

**Comment by MadEgg** [comment]
Small update: she has returned from China, but the SMS message doesn't arrive there either. I'm guessing that may be a separate 'bug report' but I'm not sure where to report that. Activation using SMS in China doesn't work.

Using the app.wire.com web app on a laptop she managed to do so, but this is a bit cumbersome.

**Comment by 0ki** [comment]
I think that it would be great if mobile app on iPhone had an option to register without providing a phone number. iPads have that.

BTW, how would and iPod user register?

**Comment by alexaubry** [comment]
Wire 3.27 will support registering by e-mail on all iOS devices. Thanks for the input!
