### ISSUE TITLE
Better sync with bad network situation

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#374]
Something went wrong with bad mobile network on iOS. 
I sent two pictures from my iPhone to a recipient. He received them both correctly and the two messages were stated as delivered on the screen.
But on my desktop computer at home, only the second one was sent to my Wire desktop device and no clue of the first one was displayed at all.

I think the ACK of all sent messages (specialy their own devices) should be improved to fix this issue.

**Comment by marcoconti83** [comment]
There is now a "delivered" status for each sent message. This will let you know if the receiver got the message.
