### ISSUE TITLE
Automatically enable Dark Theme when in Dark Mode

### ISSUE THREAD

**Issue by sirnacnud** [wireapp/wire-ios#3771]
## Checklist (please check before submitting)

* [ x] I checked the existing issues, and the issue was not reported before.

## The problem

On iOS 13 the Dark Theme should be automatically enabled/disabled depending on whether the device is currently in dark mode.

As I have it on my device now, Dark Mode is enabled automatically at sunset and I don't want to have to manually toggle the Dark Theme every time in the app.

**Comment by billypchan** [comment]
@sirnacnud Thanks for your suggestion. We added this to our task list.

**Comment by billypchan** [comment]
Working in progress now:
https://github.com/wireapp/wire-ios/pull/4374
