### ISSUE TITLE
Keyboard appears when try to send an attachment 

### ISSUE THREAD

**Issue by daviddlaiton** [wireapp/wire-ios#3842]
Wire 3.45. iPhone 11 Pro Max (Simulator) with iOS 13.2.2. 

Hi. I was doing some testing on Wire's iOS app and every time I run the app from Xcode and try to send an attachment the keyboard appears without reason. Here is a GIF showing that happens to me:

![WireBug](https://user-images.githubusercontent.com/22827454/69829866-d95f9f80-11ef-11ea-969d-08da7d4be065.gif)

This shows app when I tried to send an image or the current location.

**Comment by billypchan** [comment]
Hi @daviddlaiton, I can not reproduce this issue with iPhone 11 device. Which Xcode version you are working with? Currently Wire project supports Xcode 10.3.

**Comment by daviddlaiton** [comment]
Hi @billypchan, I running on Xcode 11.2.1. I didn't know about the support of Xcode 10.3. But apparently it is the only issue I have found so far.

**Comment by billypchan** [comment]
fixed.
