### ISSUE TITLE
Upgrade to Xcode 11

### ISSUE THREAD

**Issue by crystalztl** [wireapp/wire-ios#3846]
Need to upgrade Xcode 11

**Comment by johnxnguyen** [comment]
Hi @crystalztl 👋 , just letting you know this is currently in progress.

**Comment by zj299792458** [comment]
Has it been finished yet? ❤️

**Comment by johnxnguyen** [comment]
Hi @zj299792458 , we're ready to migrate to Xcode 11 / Swift 5.1 but unfortunately blocked from doing so until an issue regarding new restrictions on VOIP push notifications is resolved. It's an issue that affects all apps built with Xcode 11 and running on iOS 13. We expect it to be resolve in the coming weeks.

**Comment by purkylin** [comment]
What's the status?

**Comment by johnxnguyen** [comment]
@purkylin the Xcode 11 PRs are being merged today.

**Comment by johnxnguyen** [comment]
Hi all, just letting you now that https://github.com/wireapp/wire-ios/pull/3925 is merged. Thanks for your patience.
