### ISSUE TITLE
Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1.3 compiler issue

### ISSUE THREAD

**Issue by CGSHarshad110** [wireapp/wire-ios#3860]
WireDataModel in Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1.3 compiler issue my xcode version is 11.3 but all time this error arrived

**Comment by CGSHarshad110** [comment]
please  give resolution for above error

**Comment by billypchan** [comment]
Hi @CGSHarshad110 Please build the project with Xcode 10.3.

**Comment by CGSHarshad110** [comment]
hi @billypchan i tried in build  xcode 10.3 but below error.

[1/2] Compiling Swift Module 'update_stylekit' (1 sources)
[2/2] Linking ./.build/x86_64-apple-macosx/debug/update_stylekit
This copy of libswiftCore.dylib requires an OS version prior to 10.14.4.

my Mac os version is 10.14.6  and  10.15

**Comment by johnxnguyen** [comment]
@CGSHarshad110 this is a known issue with Catalina. A workaround is to update the following run script phases:

1. In **Build Phases** of the **Wire-iOS** target, change the **Update Licenses File** script to `swift run -Xswiftc "-target" -Xswiftc "x86_64-apple-macosx10.14" --package-path Scripts/update_licenses/`

2. In **Build Phases** of the **WireCommonComponents** target changes the **[CodeGen] Update StyleKit Icons** script to `swift run -Xswiftc "-target" -Xswiftc "x86_64-apple-macosx10.14" --package-path Scripts/update_stylekit/`

Once we migrate the project to Xcode 11 this workaround should no longer be needed.

**Comment by CGSHarshad110** [comment]
hi @johnxnguyen and @billypchan  
now working Xcode 10.3 
but one issue more arrived , when i run in any device that time crash my app.

issue 
objc[1150]: Class MSPLCrashReportMachExceptionInfo is implemented in both /private/var/containers/Bundle/Application/88CA0C3D-1B7A-49CB-A463-30423EAE73A8/Wire.app/Frameworks/WireCommonComponents.framework/WireCommonComponents (0x1047abb38) and /var/containers/Bundle/Application/88CA0C3D-1B7A-49CB-A463-30423EAE73A8/Wire.app/Wire (0x101ce7e38). One of the two will be used. Which one is undefined.
[31mwcall: get_members: invalid wuser=0x00000000
[;m


kindly help for this

**Comment by evchibo** [comment]
> @CGSHarshad110 this is a known issue with Catalina. A workaround is to update the following run script phases:
> 
> 1. In **Build Phases** of the **Wire-iOS** target, change the **Update Licenses File** script to `swift run -Xswiftc "-target" -Xswiftc "x86_64-apple-macosx10.14" --package-path Scripts/update_licenses/`
> 2. In **Build Phases** of the **WireCommonComponents** target changes the **[CodeGen] Update StyleKit Icons** script to `swift run -Xswiftc "-target" -Xswiftc "x86_64-apple-macosx10.14" --package-path Scripts/update_stylekit/`
> 
> Once we migrate the project to Xcode 11 this workaround should no longer be needed.

Now My project can build successfully on Catalina 10.15.3 with xcode 10.2.1. Testing to see how the app works on various simulator devices and real devices

**Comment by billypchan** [comment]
Project updated for Xcode 11.
