### ISSUE TITLE
Incoming calls do not cause a vibration when phone is set to silent

### ISSUE THREAD

**Issue by rbieb** [wireapp/wire-ios#387]
Prerequisites:
- Phone is set to silent
- Incoming call occurs

What happens: 
- Nothing. I don't hear a sound (as it should be) but I don't get some kind of vibration alarm either

Probem:
- I don't even know someone tried to call me

How to fix:
- Make the iphone always vibrate when a call happens, even if the phone is set to silent.

**Comment by mikeger** [comment]
Hey @rbieb ! Thanks for the feedback, it is much appreciated. I am happy to announce that soon we are going to have the CallKit support, which means that the calls are going to have the full screen takeover screen even when the phone is locked. Moreover, it is going to vibrate and in general look the same way as a regular (GSM) call in iOS.

**Comment by 0ki** [comment]
Great. What about Spotlight search support for contacts and/or conversations? Does it come with CallKit or is it a separate feature?

**Comment by mikeger** [comment]
External content indexing does not come with CallKit, it was available since iOS 9 via extension.

**Comment by jenskasemets** [comment]
CallKit support is now included in current latest release: 2.23, it fixes initial problem mention in this issue
