### ISSUE TITLE
Bug: selecting picture shouldn't require microphone access

### ISSUE THREAD

**Issue by MadEgg** [wireapp/wire-ios#390]
When you click the attach image button, you are first of all requested camera access. Probably due to the live camera view. Awkward but understandable.

However, when you then tap the button in the lower right corner to select an image using iOS's native picture interface, it fails without microphone access. This permission should not be required for selecting an image or video from the photos app.

**Comment by mikeger** [comment]
Hey @MadEgg ! Thanks for the feedback, it is really cool to have the "community" feeling when people come back with more comments and issues. 

The issue you are facing is definitely something we should fix, I would verify it (I always have all permissions for our app :) ) and assign the priority. Generally it should not be hard to fix it.

**Comment by MadEgg** [comment]
I can imagine you have as a developer. But the app first needs to request the permission before you can give it - the moment it requested microphone access was quite weird in this case. If I would've used it for a voice message or a call first, I wouldn't even have noticed this I suppose. I didn't block it intentionally, it just didn't ask for the permission before.

I can reproduce it by revoking permission to the microphone and attempting to open the photo's again, so indeed it shouldn't be hard to find.

**Comment by mikeger** [comment]
@MadEgg should be resolved in https://github.com/wireapp/wire-ios/pull/407

**Comment by jenskasemets** [comment]
Fix for this issue is now included in release 2.23
