### ISSUE TITLE
Liking a message causes app to jump to most recent message

### ISSUE THREAD

**Issue by kyle-fox** [wireapp/wire-ios#3955]
## Checklist (please check before submitting)

* [X] I checked the existing issues, and the issue was not reported before.

## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Wire).
Tell us what you were trying to do and what happened instead.

Liking an older message causes an unexpected jump to the most recent message.

## Environment

* Wire version that exhibits the issue: 3.50
* Last Wire version that did not exhibit the issue (if applicable): 3.49 (Can't confirm this, but I believe this is new behavior.)
* iOS version used to run Wire: 13.3
* iOS device type: iPhone 11 Pro, iPad Pro 11 inch
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): Wi-Fi, LTE

## Details

Describe the steps necessary to reproduce the problem in more details. The detailed description
will help us to fix the issue faster.

- Scroll up so most recent message is well off-screen, maybe 50-100 messages.
- Like a message
- After ~1 second, app will jump to most recent message.

**Comment by billypchan** [comment]
Hi @kyle-fox, thanks for your report. I tested on my devices but I can not reproduce them. Is it always reproducible?

**Comment by kyle-fox** [comment]
Yes always reproducible on both my devices.

**Comment by kyle-fox** [comment]
No longer reproducible on 3.51 🎉
