### ISSUE TITLE
Markdown not parsed on iOS

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#396]
When receiving antiquoted sentences on iOS, the antiquotes symbols are displayed intead of being interpreted as markdown tags.

**Comment by MadEgg** [comment]
Didn't even know this was a possibility, but just noticed that markdown is indeed parsed and interpreted in the web-app / desktop app. But in iOS the markdown is shown without affecting mark up. Nice feature to have!

**Comment by mikeger** [comment]
Hey @MadEgg , @IpsmLorem ! We are finally getting there, the issue is going to be solved with https://github.com/wireapp/wire-ios/pull/1133

**Comment by mikeger** [comment]
Markdown support is included in the current version.
