### ISSUE TITLE
adjustable text size

### ISSUE THREAD

**Issue by Be-ing** [wireapp/wire-ios#399]
I got my mom to communicate with me using Wire, but she says the text is too small for her comfort. It would be helpful to add an option to adjust the size of text in Wire.

**Comment by david-wire** [comment]
Hello, thanks for the feedback. This is indeed something we are considering, but we currently do not have any additional details to share at this stage. Thanks for taking the time to send us your thoughts.

**Comment by MathiasGmeiner** [comment]
I have the same issue with my mum and dad. Under some light conditions they can barely read the messages.
It's better on the Samsung Galaxy of my mum, but it's bad for my dad on his iPhone 5S.

**Comment by marcoconti83** [comment]
Have you tried switching between light and dark theme, to see if it makes things better under those light conditions?

**Comment by MathiasGmeiner** [comment]
Ah, thanks I will tell them!

**Comment by mikeger** [comment]
@Be-ing @MathiasGmeiner https://github.com/wireapp/wire-ios/pull/650
