### ISSUE TITLE
Feature: browse through media sent in a conversation

### ISSUE THREAD

**Issue by MadEgg** [wireapp/wire-ios#412]
When opening a picture or video in a conversation, it would be useful if you can swipe left / right to the previous / next picture or video. This makes it much easier to find a picture or video shared a while back.

**Comment by david-wire** [comment]
Hello, that is an interesting point. We don't have any immediate plans to do that at the moment, but thanks for raising it.

**Comment by jenskasemets** [comment]
Hi @MadEgg , swiping between images when opened from conversation is now possible in release 2.30.
