### ISSUE TITLE
Feature: Searching through messages

### ISSUE THREAD

**Issue by MadEgg** [wireapp/wire-ios#415]
Now that my conversations on Wire are starting to grow after several weeks of use, I'm starting to miss a feature I've been using regularly in other messengers: searching through messages. Of course, only the messages stored locally on the device could be searched. 

Sometimes after several days or weeks I want to find something that's been discussed before, and rather find it by searching for a few keywords then having to scroll back through lots of messages in between. Especially when you don't know exactly when it was discussed.

It would be great to have a feature to find messages using keywords!

**Comment by jenskasemets** [comment]
Hi @MadEgg , search in conversation is now available in release 2.30. Enjoy!
