### ISSUE TITLE
Twitter Link Rich Previews Not Working

### ISSUE THREAD

**Issue by kyle-fox** [wireapp/wire-ios#4150]
## Checklist (please check before submitting)

* [ x ] I checked the existing issues, and the issue was not reported before.

## The problem

Twitter links no longer expand into their rich previews. Should be able to replicate with any Twitter link, either pasted or shared through the share extension. This used to happen intermittently, but it stopped working entirely a few months ago and hasn't returned. Other links still expand as expected, as far as I can tell.

## Environment

* Wire version that exhibits the issue: 3.53
* Last Wire version that did not exhibit the issue (if applicable): Unknown
* iOS version used to run Wire: 13.3.1
* iOS device type: Multiple - links do not expand for anyone in the group.

## Details

Describe the steps necessary to reproduce the problem in more details. The detailed description
will help us to fix the issue faster.

Paste Twitter link into the chat, or share a tweet using the share sheet.

Expected: Link expands to rich preview.
Actual: Remains text link.

**Comment by billypchan** [comment]
@kyle-fox Thanks for reporting, it is fixed.

**Comment by kyle-fox** [comment]
@billypchan Thanks for following up! I see the fix was released, but I'm still not seeing it in practice. Would it require all users in a group be on the latest version of the Wire iOS client?
