### ISSUE TITLE
run setup.sh, some error

### ISSUE THREAD

**Issue by Zkim** [wireapp/wire-ios#4166]
Failed to write to /Users/username/myProject/wire-ios/Carthage/Build/iOS/ProtocolBuffers.framework: Error Domain=NSCocoaErrorDomain Code=260 "The file “ProtocolBuffers.framework” couldn’t be opened because there is no such file." UserInfo={NSURL=file:///Users/username
/myProject/wire-ios/Carthage/Checkouts/protobuf-objc/src/runtime/Build/ArchiveIntermediates/ProtocolBuffers%20Framework/BuildProductsPath/Release-iphoneos/ProtocolBuffers.framework, NSFilePath=/Users/username
/myProject/wire-ios/Carthage/Checkouts/protobuf-objc/src/runtime/Build/ArchiveIntermediates/ProtocolBuffers Framework/BuildProductsPath/Release-iphoneos/ProtocolBuffers.framework, NSUnderlyingError=0x7fd4cff29530 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

## Environment

carthage version 0.34.0
xcode version 10.3
branch release/3.54

**Comment by billypchan** [comment]
@Zkim did you tried update the branch and clean the project?

**Comment by Zkim** [comment]
I tried to switch branches clean carthage cache and clean the project。
rm -rf ~/Library/Caches/carthage

**Comment by Zkim** [comment]
run carthage update --platform iOS Stuck here “Cloning wire-ios-message-strategy”

**Comment by Zkim** [comment]
@billypchan  I fix it . open the file ProtocolBuffers.xcodeproj , go to menu File > Project Settings, under Derived Data section, select Advanced..., change the Build Location from Legacy to Xcode Default.
