### ISSUE TITLE
Cannot delete / edit a timed message

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#421]
It would be nice to be able to edit/delete a timed message like any other one.
A delete would trigger early the end of life (if removed from everyone) or just localy.
An edit would reset the life span

**Comment by IpsmLorem** [comment]
The delete feature is even more important when something like #435 happend, to remove persistent shadowed expired timed mesages.

**Comment by KoalaBoomka** [comment]
Thanks for the suggestion and point of view, @IpsmLorem

**Comment by marcoconti83** [comment]
You can now delete timed message you sent from your own devices, or for everyone.
