### ISSUE TITLE
Picture editing are not applied on picture from copy/paste

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#422]
* Copy a picture from your picture roll
* Paste it into a Wire concersation
* click on the smiley icon
* add a smiley
* click on the drawing icon
* draw something
* Click ok

Expected: sending of the edited picture
Real behavior: the original picture is sent without any modification

**Comment by KoalaBoomka** [comment]
Hi, @IpsmLorem ! Thanks for reporting an issue. We will prioritize it

**Comment by mikeger** [comment]
@IpsmLorem should be fixed in https://github.com/wireapp/wire-ios/pull/723

**Comment by jenskasemets** [comment]
This issue is now fixed in release 2.30
