### ISSUE TITLE
Sent/Delivered status not displayed for timed message

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#424]
* send a message
* tap on it
* the UI displays the sent time and status (sent/delivered)
* send a timed message
* tap on it: No status is displayed.

**Comment by jenskasemets** [comment]
Hi, this is by design, because you will be notified by message getting deleted once other side received your message

**Comment by IpsmLorem** [comment]
Thank you for your answer.
Somehow related to #435
