### ISSUE TITLE
Reaching Wire support via Wire messenger

### ISSUE THREAD

**Issue by herrpoerner** [wireapp/wire-ios#427]
Wire support should be reachable via Wire messenger, not only via e-mail.

**Comment by david-wire** [comment]
Hello, thanks for the suggestion. This is not planned at this stage, but thanks for taking the time to send us your comments.

**Comment by dabcoder** [comment]
On a side note, you can open an issue here for general comments (not related to any specific client / repository) here: https://github.com/wireapp/wire.

**Comment by david-wire** [comment]
On a side note, you can open an issue for general comments (not related to any client / specific repository) here: https://github.com/wireapp/wire.
