### ISSUE TITLE
Message reply

### ISSUE THREAD

**Issue by herrpoerner** [wireapp/wire-ios#428]
Especially in group chats, it would be nice to have a "Reply" function, where the original message would be quoted above the reply.

The same goes for message forwarding.

**Comment by IpsmLorem** [comment]
#205

**Comment by awltr** [comment]
This feature is really essential for us. We are currently moving a 22 participant group from Whatsapp to Wire and we are missing this function quite a lot.

**Comment by alexaubry** [comment]
Message replies are available now, so I'm gonna close this issue.
