### ISSUE TITLE
Emphasise new messages in conversations

### ISSUE THREAD

**Issue by herrpoerner** [wireapp/wire-ios#429]
New messages should be emphasised in conversations, i. e. by bold text or a colored background. An optical divider (like a red line) between old and new messages would help, too.

**Comment by david-wire** [comment]
Thanks for your comment. We also do not have any immediate plans to do this but we will keep it in mind.

**Comment by jenskasemets** [comment]
@herrpoerner thank you for your feedback, there's actually a small subtle divider — colored dot and timestamp before new messages.
