### ISSUE TITLE
Deactivating notifications for group chats / Mentions in group chats

### ISSUE THREAD

**Issue by herrpoerner** [wireapp/wire-ios#431]
Notifications for specific group chats should be mutable. If implemented then how about a mention function, where users, who have muted notifications for a group chat get a notification if they are mentioned personally?

**Comment by 0ki** [comment]
Group chats are already mutable. Same as 1:1 chats.

**Comment by jenskasemets** [comment]
Hi herrpoerner, 

As 0ki already mentioned, all conversations can be muted, either from swiping right on the conversation name in the conversation list or under conversation details in the conversation (tap on conversation name at the top).
