### ISSUE TITLE
Feature Request: Setting to enable camera automatically when receiving video call

### ISSUE THREAD

**Issue by vanitasvitae** [wireapp/wire-ios#4317]
## Checklist (please check before submitting)

* [x] I checked the existing issues, and the issue was not reported before.

## The problem

My grandparents are using wire to stay in touch with us during the pandemic. When we call them via Wire, they pick up the call, but the camera is deactivated on their end and has to be enabled manually.
While this should be pretty straight forward, it still presents a hurdle for them as it are additional steps that need to be remembered.
It would be nice to expose some option in the settings for enabling the camera automatically when receiving a video call.

## Environment

* Wire version that exhibits the issue: 3.5.7
* iOS version used to run Wire: 12.3.1
* iOS device type: iPad Pro
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): wifi

**Comment by billypchan** [comment]
Hi @vanitasvitae, you can start a video call directly by taping the video icon on top right of the conversation.

**Comment by vanitasvitae** [comment]
I know how to start a video call. This issue is about having a setting to automatically enable the camera when *receiving* a call.
