### ISSUE TITLE
Bulk deleting of messages

### ISSUE THREAD

**Issue by herrpoerner** [wireapp/wire-ios#433]
Marking multiple messages to delete them. How about by long-pressing messages? Liking messages could be implemented by double-tapping a message.

**Comment by jenskasemets** [comment]
Hi herrpoerner,

Double-tapping on any message is actually liking them, have a try.

Long-pressing on any message is opening action menu where you should have an option to delete a message. 

PS. Some of the actions are not available for timed messages.

To bulk delete messages you can clean history of any conversation by:
- swipe right on conversation name in the conversation list and tap on "Delete"
- inside the conversation, tap on conversation name, then "•••" and then "Delete"
