### ISSUE TITLE
Cannot edit picture when taken with full screen preview

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#434]
* tap on camera icon
* enlarge the cam to display a full screen preview
* take a picture
* the picture is sent without beeing able to edit it

Expected: be able to add drawing or smiley like when the camera is in small preview mode.

**Comment by KoalaBoomka** [comment]
@IpsmLorem, thanks for reporting this UX concern. We are going to take a look at it and see what could we do.

**Comment by billypchan** [comment]
This issue is fixed.
