### ISSUE TITLE
GIFY needs to be removed from the entire product line

### ISSUE THREAD

**Issue by cardassian-tailor** [wireapp/wire-ios#4356]
https://www.theverge.com/2020/5/15/21259965/facebook-giphy-gif-acquisition-buy-instagram-integration-cost

conversations need to occur for replacing GIFY with something else, soon.

**Comment by mHatsune** [comment]
https://github.com/wireapp/wire/issues/347 https://github.com/wireapp/wire-webapp/issues/5571

**Comment by marek-lach** [comment]
At least disable it by default in Preferences.
