### ISSUE TITLE
Feature: hide mobile information when displaying full screen picture

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#437]
When displaying a full screen picture, it would be better to hide mobile information (carrier, time, batery level, ...) to achieve a real full screen experience.

**Comment by david-wire** [comment]
Hello, thanks for the feedback. We appreciate the time you took the send us your comments. No plans to do this at the moment though.

**Comment by jenskasemets** [comment]
@david-wire this is actually a bug we should fix, I will follow up on this once fixed

**Comment by 0ki** [comment]
@jenskasemets while at it, could you make sure that non-fullscreen views do not hide mobile information? e.g. the user (friend) list on small devices.

**Comment by jenskasemets** [comment]
@0ki Why you would like to see status bar on small devices for conversation list? This would reduce real estate even more for actual content and would make it more difficult to use.

**Comment by 0ki** [comment]
Having to think about which mode to enter or leave to get the time, battery or network connection type is what makes a phone more difficult to use.

**Comment by jenskasemets** [comment]
Design/layout for full screen pictures have changed and with new approach showing status bar is not a bug anymore (release 2.30).
