### ISSUE TITLE
Emojis rendering inside code blocks

### ISSUE THREAD

**Issue by Siguza** [wireapp/wire-ios#4372]
## Checklist (please check before submitting)

* [x] I checked the existing issues, and the issue was not reported before.

## The problem

Send the following message:

    `:(`
    ```
    :(
    ```

On desktop, this renders like this:

![Screenshot 2020-05-23 at 21 09 19](https://user-images.githubusercontent.com/1659374/82738677-bbf03600-9d39-11ea-8774-2e968634a4ca.png)

Whereas in the iOS app, it renders like this:

![Untitled](https://user-images.githubusercontent.com/1659374/82738688-e0e4a900-9d39-11ea-96fa-2a047becca04.png)

## Environment

* Wire version that exhibits the issue: 3.58 at the time of writing
* Last Wire version that did not exhibit the issue (if applicable): None that I recall
* iOS version used to run Wire: At least 13.3, 13.4, 13.5
* iOS device type: iPhone SE (2016), iPhone 7, iPhone SE (2020)
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): Irrelevant
* Exact date, time and timezone (only for the crash issues): Irrelevant

## Details

Literally just send the above message and view it in an iOS client. Doesn't matter where it was sent from, even works when typing it out on iOS itself.

I guess this is at least partially related to #772, however even once that feature was implemented I'd still consider this a bug. On desktop you can turn emoji conversion on or off, but even when turned on, text inside code blocks does not get replaced with emojis - I'd expect the iOS client to exhibit the same behaviour.

**Comment by billypchan** [comment]
Thanks @Siguza, we added your suggestion to our tasks.

**Comment by billypchan** [comment]
fixed in https://github.com/wireapp/wire-ios/pull/4381
