### ISSUE TITLE
Red badge remains after all messages have been viewed. 

### ISSUE THREAD

**Issue by nathan-dunn** [wireapp/wire-ios#4377]
## Checklist (please check before submitting)

* [ ] I checked the existing issues, and the issue was not reported before.

## The problem

Briefly describe the issue you are experiencing (or the feature you want to see added to Wire).
Tell us what you were trying to do and what happened instead.

## Environment

* Wire version that exhibits the issue:
* Last Wire version that did not exhibit the issue (if applicable):
* iOS version used to run Wire:
* iOS device type: 
* Mobile network type (EDGE/LTE/Wi-Fi/Offline):
* Exact date, time and timezone (only for the crash issues): 

## Details

Describe the steps necessary to reproduce the problem in more details. The detailed description
will help us to fix the issue faster.

## Calling Debug logs (only for calling issues)

0. You have to have the iOS email client set up.
1. Reproduce the issue.
2. Go to Settings -> Advanced -> Calling Debug Report.
3. Send the report.

## Screenshots

Please attach screenshots if you consider them as helpful to understand/reproduce the issue.

**Comment by typfel** [comment]
I can confirm this bug, we'll look into it.
