### ISSUE TITLE
Push Notifications (Build from Source)

### ISSUE THREAD

**Issue by evchibo** [wireapp/wire-ios#4386]
#Is there any roadmap to allowing notifications working from an application build from source?

**Comment by typfel** [comment]
What’s your use case? Push notifications are tied to our app store team id on the server side so it’s not easy to have pushes if you are not also running your own server.

**Comment by evchibo** [comment]
> What’s your use case? Push notifications are tied to our app store team id on the server side so it’s not easy to have pushes if you are not also running your own server.

I managed to ru my own server

**Comment by smaroff92** [comment]
> I managed to run my own server. So basically want to use it on my own server too
Hello! Did you manage to launch push notifications on your server?

**Comment by MaxwellSun** [comment]
> > What’s your use case? Push notifications are tied to our app store team id on the server side so it’s not easy to have pushes if you are not also running your own server.
> 
> I managed to run my own server. So basically want to use it on my own server too

Hello, Do you mean that you have built your own server and it is running normally?
change ios backend url, then self build iOS client can message in private server?
