### ISSUE TITLE
Incorrect behavior for takeover screen on verified conversation degradation

### ISSUE THREAD

**Issue by marcoconti83** [wireapp/wire-ios#440]
As reported here https://github.com/wireapp/wire-webapp/issues/208 by @IpsmLorem:

- User B as a web app
- User A validates B web app
- User B log off and destroy is local data
- User B log in and a new session (key etc.) is made
- User A send a message on iOS and Wire displays "User B begin to use a new device. Are you sure you still want to send your message ? [Display device / Send anyway]"
- User A does NOT click on anything
- User B as already received the sent message even if A didn't want to

**Comment by david-wire** [comment]
@IpsmLorem I am struggling to reproduce this behavior where:
- "User A does NOT click on anything" and 
- "User B as already received the sent message even if A didn't want to". 
When tested the takeover screen says active until the user decides to dismiss it, 'show device' or 'send anyway'. Do you get this 100% of the time. Are there any steps that need to be performed between those 2?

**Comment by IpsmLorem** [comment]
I tried only one time and the takeover screen was displayed on the sender part and the receiver did receive the message, even if the sender did chose between the two options.

**Comment by KoalaBoomka** [comment]
Cannot reproduce with the given steps. If user B has a new device and A wanted to send something and didn't choose any option - message is not sent.

**Comment by IpsmLorem** [comment]
I will reopen if I can reproduce.
