### ISSUE TITLE
Cannot make audio calls on iPad

### ISSUE THREAD

**Issue by jensrossbach** [wireapp/wire-ios#444]
When I try to start an audio call on my iPad, I get a notification that Wire needs access to the microphone. When I press OK, the dialog disappears and nothing more happens. When I press on the settings button, I'm redirected to the settings screen where I can grant access to several resources for Wire. But there is no setting to grant microphone access. When I check the settings for other audio apps (e.g. Skype), I can see this microphone setting. But it's missing for Wire. So I have no chance to make an audio call.

The same happens for video calls, with the difference that here the call is actually started after pressing OK in the notification dialog, however the audio from iPad to the callee is missing.

Tested with newest release 2.23 (but happened also with older releases).

**Comment by KoalaBoomka** [comment]
hi @jensrossbach! Thanks for contacting us. We really appreciate your report. 
Could you please provide your iPad model and iOS version?

**Comment by jensrossbach** [comment]
Hi @KoalaBoomka, I have an IPad Air 2 with iOS 10.1.1 installed.

I have an assumption, maybe this helps for analysis / reproducing the problem. I had restrictions active, one of them to disallow the change of the microphone access. However after removing this restriction, the problem was still present. Can it be that Wire registers the need for microphone access at iOS only at installation time? At the time I installed Wire on my iPad, the restriction was most probably active.

**Comment by KoalaBoomka** [comment]
@jensrossbach, I see. Did you try to kill the app after you took restriction off?

**Comment by jensrossbach** [comment]
@KoalaBoomka indeed killing the app seemed to solve the issue. Now Wire gained microphone access (also the setting for mic access is now present) and audio calls work. Thanks for the hint.
Maybe for future improvement Wire could inform the user about the restriction so that it's clear what needs to be done.

**Comment by KoalaBoomka** [comment]
hi @jensrossbach,
I'm afraid that iOS doesn't provide the information to the developers about these kind of the restrictions.
