### ISSUE TITLE
App Crash when push notification received on iOS 13.5.1

### ISSUE THREAD

**Issue by ujeshpatel** [wireapp/wire-ios#4447]
## Checklist (please check before submitting)
I guess this all is related - #4334 #3641 

## The problem
We set up our own server and implemented Push notification, 
it's work perfect on iOS 12.4. but in iOS 13.5.1 it's not working. when a notification comes app crashed. I attached the Crash log here for review. 

## Environment

* iOS version used to run Wire: 13.5.1 
* iOS device type: iPhone 7  
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): All
* XCode - 11.4 

Crash Logs [Crash on notification.zip](https://github.com/wireapp/wire-ios/files/4862208/Crash.on.notification.zip)

Looking forward to seeing the solution.

**Comment by johnxnguyen** [comment]
Hi @ujeshpatel , indeed the crash you are experiencing is due to the restrictions, whereby all VOIP pushes must be reported to CallKit. Wire has been excepted from these restriction through an entitlement, however it is not intended to be a permanent solution. We are developing a long term solution to no long rely on VOIP pushes, but I'm afraid I can't say when it will be production ready. Unfortunately, until we migrate away from VOIP pushes, you will continue to experience the crash without the entitlement.

**Comment by ujeshpatel** [comment]
@johnxnguyen Thanks for a quick reply,  
Can you please elaborate on which entitlement needs to be added in order to have it working.  Please review the attached screenshot of the development environment.  
![Screenshot 2020-07-02 at 4 32 55 PM](https://user-images.githubusercontent.com/8926186/86351372-ccbd9100-bc81-11ea-85ac-26591e80033f.png)

and here is production environment entitlement 
![Screenshot 2020-07-02 at 4 35 03 PM](https://user-images.githubusercontent.com/8926186/86351519-0098b680-bc82-11ea-8024-fbf9e45e75d0.png)

**Comment by johnxnguyen** [comment]
The entitlement is not a standard entitlement and is only granted by Apple in a case by case basis. You can see in our project settings there is an entry for “unrestricted-voip”. 

If I understand correctly, you are tying to build the app to communicate with your own server, correct?

**Comment by ujeshpatel** [comment]
If I understand correctly, you are trying to build the app to communicate with your own server, correct?
> Yes, correct

**Comment by johnxnguyen** [comment]
Do you need to build the app locally? You can use our public app from the App Store and configure it to point to your custom backend. I'm not 100% certain that this will solve your issue, but I think it's worth a try.

**Comment by johnxnguyen** [comment]
If you want to go this way, just let me know and I can provide a list of steps to follow.

**Comment by ujeshpatel** [comment]
Do you need to build the app locally?  > Yes, I set up a project locally and upload it on a test flight for testing. 

Yes, Let's try to configure the public app with our server. Please share steps

**Comment by johnxnguyen** [comment]
You can follow this [guide](https://github.com/wireapp/wire-docs/blob/a099fd05a478c665059e3546c90d2fd226b1277c/src/how-to/associate/deeplink.rst) to configure the app with a deep link.

**Comment by ujeshpatel** [comment]
thanks, will check

**Comment by lucifer662607004** [comment]
> The entitlement is not a standard entitlement and is only granted by Apple on a case by case basis. You can see in our project settings there is an entry for “unrestricted-voip”.
> 
> If I understand correctly, you are trying to build the app to communicate with your own server, correct?

Hi,
Just curious, how did you grant such “unrestricted-voip” entitlement from Apple? Did you argue with apple during the review or there is a way to apply for it? Thank you.

**Comment by johnxnguyen** [comment]
> Just curious, how did you grant such “unrestricted-voip” entitlement from Apple? Did you argue with apple during the review or there is a way to apply for it? Thank you.

@lucifer662607004 The entitlement is a temporary solution to give existing apps some time to migrate away from using voip notifications in this way. I don't believe there's a way to apply for it, I think Apple will only give you the entitlement if you make the case that you need it while migrating to normal APNS remote pushes.
