### ISSUE TITLE
Profile Cache key is nil

### ISSUE THREAD

**Issue by ujeshpatel** [wireapp/wire-ios#4458]
## The problem

Not able to download profile images for each user 

## Environment

- iOS version used to run Wire: 13.5.1
- iOS device type: iPhone 7
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): All
- XCode - 11.4
- Server - own custom server from wire server repo

## Details

Profile pics are not loading for the user because of 2 cache key is not generated smallProfileImageCacheKey and mediumProfileImageCacheKey. both keys are depending on previewProfileAssetIdentifier and completeProfileAssetIdentifier variable, while debugging and in comparison of wire iOS app I found both variables are Nil. How can I get value for the cache key?

Thanks in advance for the help

**Comment by billypchan** [comment]
Hi @ujeshpatel, thanks for the report. We are working on this issue.

**Comment by typfel** [comment]
Hi @ujeshpatel,

If `previewProfileAssetIdentifier` and `completeProfileAssetIdentifier` is `nil` then the user profile haven't been correctly download for some reason. 

Are you running your own server on kubernetes or using the docker-compose based demo?

If would helpful for debugging this issue if you could perform the following steps:
1. While running the app with the\ debugger attached, navigate to a 1:1 conversation of a user.
2. Tap on the conversation title to open the user profile (This will trigger the user profile to be downloaded again from the server).
3. Look in the console for the server response and post it here, it should look like this:

```
<---- Response to GET /users?ids=f8d94390-a916-439d-87c9-2e2eaccd0d91 (status 200): <ZMTransportResponse: 0x600001185c20> 200 {
    "Access-Control-Expose-Headers" = "Request-Id, Location";
    Connection = "keep-alive";
    "Content-Encoding" = gzip;
    "Content-Length" = 272;
    "Content-Type" = "application/json";
    Date = "Mon, 13 Jul 2020 08:58:28 GMT";
    "Request-Id" = f53ae82287a32a22c6a4fbf5e5630837;
    Server = nginx;
    "Strict-Transport-Security" = "max-age=31536000; includeSubDomains; preload";
} (
        {
        "accent_id" = 1;
        assets =         (
                        {
                key = "3-1-f7476a82-069e-40bb-95cd-d458701b6e46";
                size = preview;
                type = image;
            },
                        {
                key = "3-1-cff8ea34-ecee-445d-8219-df34210768cd";
                size = complete;
                type = image;
            }
        );
        email = "jacob+avatar1@wire.com";
        handle = jacobavatar;
        id = "f8d94390-a916-439d-87c9-2e2eaccd0d91";
        name = "Jacob Avatar";
        picture =         (
        );
        team = "6e152d9c-2a5c-4d41-b7fd-660980a79771";
    }
)
```
