### ISSUE TITLE
CallKit issues

### ISSUE THREAD

**Issue by jensrossbach** [wireapp/wire-ios#449]
I tested the CallKit support with the release 2.23 but observed some problems:

1. Missed calls are not shown in lock screen and notification center.

2. When I start a video call, after accepting the call on iPhone, video is deactivated by default -> I have to press the video button, then unlock the phone, which redirects me automatically to the Wire app where I see the video picture of the caller (maybe this is by design / a limitation of iOS?).
Then there is a second problem: although video is indicated to be active (the video button is highlighted), it is actually still not (black screen with according notice on caller side). So I first have to deactivate video and activate it again in order to have it actually active.

3. I cannot make a call directly out of the iOS address book (via long press on the blue circular buttons on top of the contact screen); this is for instance offered for WhatsApp and Skype calls.

4. I called my iPhone from my iPad. Before accepting the call on the iPhone side, I hung up on iPad side. But the iPhone didn't stop ringing! After some time, I accepted this "incoming call". What happened was that a new call from iPhone to iPad was initiated. I stopped this on both sides. About 10 minutes later I received a notification on my iPhone about a missed call.

**Comment by 0ki** [comment]
One more CallKit bug.
In call history: Outgoing calls are shown as to my e-mail address "user@host.com" that I registered my account on wire with. They should be of course shown to the person I'm calling to.

**Comment by KoalaBoomka** [comment]
hi, @jensrossbach! We really appreciate your feedback. We'll take a look at your suggestions and found issues.
@0ki, we'll take a look at yours reported issue as well.

**Comment by typfel** [comment]
Version 2.29 which we released today has several fixes for CallKit and more will come in future releases.

**Comment by jenskasemets** [comment]
Hi @jensrossbach , release 2.31 which was released, there are several improvements to CallKit, sadly not yet to all the issues you mentioned above. Hopefully it helps at least littlebit.

**Comment by 0ki** [comment]
This seems actually fixed for me.
