### ISSUE TITLE
iPad - wire-iOS app crashes after deleting conversations

### ISSUE THREAD

**Issue by Leuchti** [wireapp/wire-ios#4504]
## Checklist (please check before submitting)

* [ x ] I checked the existing issues, and the issue was not reported before.

## The problem

The App crashes when I try to delete a conversation via the conversation-menu.
The App does not crash, when i try to delete the conversation via the menu or details of the user.

## Environment

* Wire version that exhibits the issue:

![2020-08-04_11h34_35](https://user-images.githubusercontent.com/69189135/89278523-84a9d980-d646-11ea-9e99-0b114b15c545.png)

* Last Wire version that did not exhibit the issue (if applicable):
none

* iOS version used to run Wire:
13.6

* iOS device type: 
iPad Pro (11 Zoll)

* Mobile network type (EDGE/LTE/Wi-Fi/Offline):
LTE and Wi-Fi

* Exact date, time and timezone (only for the crash issues): 
04.08.2020 - 8:45 am - Central European time zone

## Details

Step 1: Start Wire on iPad
Step 2: Open the menu to the conversation (by pressing long on the conversation)

![20-08-04 11-18-28 0010](https://user-images.githubusercontent.com/69189135/89277003-91c5c900-d644-11ea-8d10-54a4f7638515.png)

Step 3: Delete the conversation

![20-08-04 11-18-28 0010](https://user-images.githubusercontent.com/69189135/89277426-1c0e2d00-d645-11ea-89d6-2cb4dc0cdef0.png)

**After that the App crashed.**

**Note**
The App does not crash, when i try to delete the conversation via the menu or details of the user.

## Calling Debug logs (only for calling issues)

[previous.log](https://github.com/wireapp/wire-ios/files/5021375/previous.log)

## Screenshots

Screenshots have already been inserted.

**Comment by billypchan** [comment]
hi @Leuchti, thanks for your report. We will check this.

**Comment by billypchan** [comment]
will include the fix in next release
