### ISSUE TITLE
Feature request: open received files in other app. 

### ISSUE THREAD

**Issue by mat1th** [wireapp/wire-ios#456]
Thanks for you app! I would like to have a feature to open received all sort of files in an another app. 

For example when you click in the native mail client on a file you can choose with witch app you would like to open it. 

When this feature is in the app it makes much more sense to send files to the iOS wire app.

**Comment by mikeger** [comment]
Hey @mat1th ! Thanks for the suggestion. I think you can actually open the file in other apps, there is a small icon on the bottom left:
![img_6004](https://cloud.githubusercontent.com/assets/715129/20962746/e46a79dc-bc6a-11e6-8cf2-0b3fceffabf3.PNG)

**Comment by mat1th** [comment]
Hello, This is only possible for formats that are supported. So for example I send a .ics (for calendar) or a pixelmator (photoshop alternative) file I can not open It in a other app. 

![screenshot](https://cloud.githubusercontent.com/assets/6486389/20963410/7fe643a8-bc6d-11e6-870f-f035b3881a23.png)

When I click on the file nothing happens.

**Comment by mikeger** [comment]
@mat1th it is not totally obvious, but you can click on the file type icon, then it should open the "Open In" dialogue.

**Comment by mat1th** [comment]
Ohh, I didn't know. Thanks! You could maybe improve the experience with making the whole element clickable.
