### ISSUE TITLE
Voice message record button doesn't work

### ISSUE THREAD

**Issue by 0ki** [wireapp/wire-ios#4567]
## The problem

Pressing the record button does nothing. This affects the most recent wire version regardless of iOS13 subversion.

## Details

1. Open any chat
2. Press microphone button.
3. Press record button.
4. Recording starts.
5. Press on stop button.
6. Press revert button on the left of the screen.
7. Press record button.
8. Recording should start but nothing happens.

**Comment by billypchan** [comment]
hi @0ki thanks for the report. We will add this to our task list.
