### ISSUE TITLE
try run  setup.sh, some error 

### ISSUE THREAD

**Issue by berchan** [wireapp/wire-ios#46]
A shell task (/usr/bin/env unzip -qq -d /var/folders/94/2_z6xnl52fb4g6r5v5j81qdr0000gq/T/carthage-archive.lkp3sF /Users/zhangbc/Library/Caches/org.carthage.CarthageKit/binaries/CocoaLumberjack/2.2.1-wire/1990116-CocoaLumberJack.framework.zip) failed with exit code 9:
[/Users/zhangbc/Library/Caches/org.carthage.CarthageKit/binaries/CocoaLumberjack/2.2.1-wire/1990116-CocoaLumberJack.framework.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /Users/zhangbc/Library/Caches/org.carthage.CarthageKit/binaries/CocoaLumberjack/2.2.1-wire/1990116-CocoaLumberJack.framework.zip or
        /Users/zhangbc/Library/Caches/org.carthage.CarthageKit/binaries/CocoaLumberjack/2.2.1-wire/1990116-CocoaLumberJack.framework.zip.zip, and cannot find /Users/zhangbc/Library/Caches/org.carthage.CarthageKit/binaries/CocoaLumberjack/2.2.1-wire/1990116-CocoaLumberJack.framework.zip.ZIP, period

**Comment by typfel** [comment]
Hi, thanks for reporting this issue. It would help us if you included the whole output log from `setup.sh`. It looks like a carthage dependency was not correctly downloaded. You could try to clean the Carthage cache and re-run the setup script.

**Comment by berchan** [comment]
Hi @typfel

**Comment by berchan** [comment]
Hi @typfel  thanks for your response. I clean the Carthage cache and reinstall it, but it not work. Then i try repeat run the setup script, it works, but i don't why!

**Comment by marcoconti83** [comment]
Sounds like a transient problem with Carthage. We have seen this happening a couple of times, and rerunning 'carthage bootstrap' after clearing the cache seems to always fix the issue. Closing the issue, please reopen if it keeps happening even after clearing the cache and re-running.

**Comment by derosenyelen** [comment]
Hi, i'm having the same issue, but cleaning the cache folder and running carthage bootstrap doesn't fix it for me. any news on this issue?

**Comment by berchan** [comment]
you can clone new one and repeat run ./setup.sh. maybe help!

At 2017-12-17 17:33:19, "Yelen de Rosen" <notifications@github.com> wrote:


Hi, i'm having the same issue, but cleaning the cache folder and running carthage bootstrap doesn't fix it for me. any news on this issue?
