### ISSUE TITLE
Backup/restore: ios-wbu vs ios_wbu (Gmail)

### ISSUE THREAD

**Issue by cmkeever** [wireapp/wire-ios#4609]
## Checklist (please check before submitting)

* [x] I checked the existing issues, and the issue was not reported before.

## The problem

I have a new iphone, I made a conversation backup from old phone, navigated to it on new phone, but it was dim/gray and not interactable.
*** I had to manually rename the file so that extension changed from "ios-wbu" to "ios_wbu", and then it would import the file. ***

## Environment

* Wire version that exhibits the issue: 3.64
* Last Wire version that did not exhibit the issue (if applicable): Unknown
* iOS version used to run Wire: 13.6.1
* iOS device type: phone
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): Wi-Fi/LTE
* Exact date, time and timezone (only for the crash issues): N/A

## Details

Export file had extension "ios-wbu" (with hyphen), but Wire wouldn't recognize it as an importable file until it had extension "ios_wbu" (with underscore).  Both phones had the same versions of app and iOS, so I think you could recreate on a single phone.  Anyway even if each one was self-consistent it should be easy to have restore-from-backup recognize both possible extensions going forward.

## Calling Debug logs (only for calling issues)

N/A

## Screenshots

Not critical for this one.

**Comment by billypchan** [comment]
Hi @cmkeever, thanks for the report. We will take a look at this issue.

**Comment by KaterinaWire** [comment]
Hi @cmkeever , have you used the Gmail app to transfer a backup of conversations from one phone to another?

**Comment by cmkeever** [comment]
Yes.  Looking back at the message from PC browser I see extension "ios-wbu".

**Comment by KaterinaWire** [comment]
@cmkeever Thank you for reporting this issue. After doing some research, we found that the iOS version of the Gmail app changes the underscore with a dash in the attachment file name, and as a result, you got a backup file with the wrong extension on your new phone. You can find more details on this issue on the google support page.
For our side, we'll make sure that Wire can accept both file extensions.

**Comment by cmkeever** [comment]
What a strangely random Gmail bug!  I guess this is a feature request then :)

**Comment by typfel** [comment]
A workaround for this issue was released in https://github.com/wireapp/wire-ios/releases/tag/appstore%2F3.68
