### ISSUE TITLE
Support Swift for Xocde 12, iOS 14

### ISSUE THREAD

**Issue by cgsmihir** [wireapp/wire-ios#4612]
Hello
I integrate wire-ios with my project.
when I run a script.
**`sh ./setup.sh`**

It fails and shows like that.

> **Falling back to building from the source**
> **Skipped installing wire-ios-sync-engine.framework binary due to the error:**
> **"Incompatible Swift version - framework was built with 5.2.2 (swiftlang-1103.0.32.6 clang-1103.0.32.51) and the local version is 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)."**

> **Falling back to building from the source**
> **Building scheme "Cartography-iOS" in Cartography.xcworkspace**
> **Build Failed**

i'm using Xcode 12 (ios 14)

please give resolution for above error.

**Comment by typfel** [comment]
Our project does not yet build with Xcode 12. It's on our todo list but I can't give you a exact date when it will be done.
