### ISSUE TITLE
Implementing Wire for iOS 14

### ISSUE THREAD

**Issue by cgsmihir** [wireapp/wire-ios#4661]
Hello
I Need Implement Wire for iOS 14.
Can you please help with this?

I'm using Xcode 12 and OSX 10.15.6

Thanks.
Mihir

**Comment by billypchan** [comment]
Hi @cgsmihir! We are currently working on Xcode 12 upgrade. Several components need updating and the progress is record in this PR: https://github.com/wireapp/wire-ios/pull/4642. Stay tuned!

**Comment by cgsmihir** [comment]
Hi @billypchan,
Okay, thanks. If possible then please share the estimated date so I can use the latest code of the wire app.

**Comment by hkaklotar** [comment]
when we try to debug mode this error evey time arrived and mobile app every time crash , please help for this 
Xcode 11.7 
mobile os 14.1

<img width="489" alt="Screenshot 2020-10-28 at 2 19 24 PM" src="https://user-images.githubusercontent.com/54879794/97443760-686dbe00-1951-11eb-93fc-07053a5a6d9d.png">

**Comment by hkaklotar** [comment]
hey team ,

Please update on above issue, if possible share timeline of Xcode 12 support

**Comment by hkaklotar** [comment]
hey team ,

Please update on above issue

**Comment by billypchan** [comment]
> when we try to debug mode this error evey time arrived and mobile app every time crash , please help for this
> Xcode 11.7
> mobile os 14.1
> 
> <img alt="Screenshot 2020-10-28 at 2 19 24 PM" width="489" src="https://user-images.githubusercontent.com/54879794/97443760-686dbe00-1951-11eb-93fc-07053a5a6d9d.png">

Hi @hkaklotar, Currently Wire project supports XCode 11.4.1. From the screenshots, it seems related device connection.

**Comment by hkaklotar** [comment]
hi
we try in 11.4.1 but same issue arrived , we can not debugging , please help

**Comment by hkaklotar** [comment]
any upadate for Xcode 12 related ?

**Comment by mihirpipermitwala** [comment]
Hello @billypchan,
Please update on the above issue, if possible share the timeline of Xcode 12 support.

**Comment by billypchan** [comment]
I created a branch which can build Wire for iOS 14:

https://github.com/wireapp/wire-ios/pull/4715
