### ISSUE TITLE
App closes immediately upon logging in

### ISSUE THREAD

**Issue by extra3464** [wireapp/wire-ios#4694]
## Checklist (please check before submitting)

* [X] I checked the existing issues, and the issue was not reported before.

## The problem
The app closes immediately upon trying to log in. 

## Environment

* Wire version that exhibits the issue:  App Store 3.68
* Last Wire version that did not exhibit the issue (if applicable): App store 3.67
* iOS version used to run Wire: 12.4.9
* iOS device type: iphone 6
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): LTE/Wi-fi
* Exact date, time and timezone (only for the crash issues): Multiple times on Nov 5, 2020

## Details

Initially, upon the newest update, the app wouldn't even open. So I deleted and reinstalled. Prompted me to log in, tried to log in, once I entered email and password, app crashes.

**Comment by Tobbypower** [comment]
I can confirm this behavior at iPad Air with iOS 12.4.8.
Open App > Start screen > crash

**Comment by imaddie17** [comment]
Same on iPhone 6 Plus, running iOS 12.4.8. ; the app got updated and now all it does is crash after Start Screen.

**Comment by suhancz** [comment]
iPhone 5 SE same problem. Any known workarounds, please?

**Comment by engelsherz** [comment]
iPhone 6, iOS 12.4.8, version 3.68, same problem. crashes when opening app. Tried restarting iPhone several times, didn't work

**Comment by chrisHRD** [comment]
I can report another instance of this bug. Attempted to open with a fresh install of the Wire App and a reboot of the OS, no effect.
Device: iPad Air
OS: iOS 12.4.8

**Comment by billypchan** [comment]
Thanks for the report.
We discovered a bug related to iOS 12 and working on it now. The next release will this issue.

**Comment by Tobbypower** [comment]
Update at 11.11.2020 solved the problem. Thanks!
