### ISSUE TITLE
Error restoring from backup

### ISSUE THREAD

**Issue by roni75020** [wireapp/wire-ios#4717]
## Checklist (please check before submitting)

* [x ] I checked the existing issues, and the issue was not reported before.

## The problem

When restoring messages on a new phone from backup, a pop-up window appears with the following message:
========
Your session expired.
The application did not communicate with the server for a long period of time, or your session has been remotely invalidated. 
==========

## Environment

* Wire version that exhibits the issue: 3.7.0
* Last Wire version that did not exhibit the issue (if applicable):
* iOS version used to run Wire: 14.2
* iOS device type: iPhone 12 PM
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): LTE/Wi-Fi
* Exact date, time and timezone (only for the crash issues): 

## Details

- Login in by email
- Restore from backup
- Pop-up appears 

## Calling Debug logs (only for calling issues)

0. You have to have the iOS email client set up.
1. Reproduce the issue.
2. Go to Settings -> Advanced -> Calling Debug Report.
3. Send the report.

## Screenshots

Please attach screenshots if you consider them as helpful to understand/reproduce the issue.
![1024-2217](https://user-images.githubusercontent.com/10583986/99426285-31614b80-2904-11eb-95bd-ea4b83763114.png)

**Comment by typfel** [comment]
Thanks for reporting this, we can reproduce and are working on fixing this bug.

**Comment by typfel** [comment]
Fix was released in 3.71
