### ISSUE TITLE
Running 'chore/xcode12_bugsur' branch for xcode 12 on Big Sur showing "LLDB provided no error string"

### ISSUE THREAD

**Issue by mihirpipermitwala** [wireapp/wire-ios#4720]
Hello Wire Team,

**Running on MacOS => 11.0.1 (20B29), 
Xcode => 12.2 (12B45b)**

<img width="669" alt="Screenshot 2020-11-19 at 8 08 53 PM" src="https://user-images.githubusercontent.com/65561886/99680429-0f51ff80-2aa3-11eb-8a8b-138718d4e864.png">

please give a resolution for the above error.

**Comment by mihirpipermitwala** [comment]
Hello Wire Team,
please guide me on this.

**Comment by hkaklotar** [comment]
hello wire team ,
please update for above issue

**Comment by mihirpipermitwala** [comment]
Hello @mikeger,
please could you send a timeline for Xcode 12, macOS Big Sur support?

**Comment by mikeger** [comment]
Hey @mihirpipermitwala , I am not maintaining this project anymore. Best regards, Mike.

**Comment by mihirpipermitwala** [comment]
Sorry, please could you tell me who maintaining this project.

**Comment by hkaklotar** [comment]
hello wire team ,
please update for above issue

**Comment by mihirpipermitwala** [comment]
Hello wire Team, please update for the above issues. we need to start the project asap.

**Comment by typfel** [comment]
The Wire client doesn't yet build on Xcode 12. We will update the build description on https://github.com/wireapp/wire-ios when we merge support for it.

**Comment by billypchan** [comment]
Hi @mihirpipermitwala, We are still updating our project to XCode 12.3. You can check out `chore/xcode12_catalina_disable_crash_tests` of this repo to have a buildable project.
