### ISSUE TITLE
Looking for details regarding ephemeral messagining and Deletion 

### ISSUE THREAD

**Issue by cardassian-tailor** [wireapp/wire-ios#4724]
Can someone point me to the appropriate locations within the code base that deal with ephemeral message deletion. Even better, does a white paper exist on the technology used for such within wire? 

There have been some discussions where this functionality is referred to as a 'cosmetic chat cleanup' feature and not so much true ephemeral messaging. 

Does the deletion of messages rely on good faith between the participating parties? 

Is there any technology that makes the messages unreadable on the participating parties devices, or is it more of just a GUI deletion where the message is still there on the end users device but just not being displayed? 

How does the aspect of any user sent data can be deleted at any time work? Do users devices constantly check some shared key to see if a revocation has occurred? Or, does the participating parties send some type of updated state saying please no longer show this message? 

@billypchan

**Comment by cardassian-tailor** [comment]
@billypchan  @typfel  @alexaubry  I know this isn't necessarily a bug but im not sure where else to ask such a question.

**Comment by typfel** [comment]
>There have been some discussions where this functionality is referred to as a 'cosmetic chat cleanup' feature and not so much true ephemeral messaging.

How would true ephemeral messaging work? We do indeed rely on clients to behave nicely since it's the clients in the end who delete the messages from their the local database, which of course they could decide not to do.

>How does the aspect of any user sent data can be deleted at any time work? Do users devices constantly check some shared key to see if a revocation has occurred? Or, does the participating parties send some type of updated state saying please no longer show this message?

Clients notify the sender when they have read the ephemeral message via a status update. The ephemeral message itself contains the date when it expires, which again needs to be respected by the clients.

They way I look ephemeral messages is as an automatic chat history deletion for groups/chats in which you trust everyone. It's a tool a group can agree to use in order to minimise the amount of data left on the devices.

It's not about sending a message to stranger and have guarantees that it will be destroyed in all circumstances.

**Comment by cardassian-tailor** [comment]
> 
> 
> > There have been some discussions where this functionality is referred to as a 'cosmetic chat cleanup' feature and not so much true ephemeral messaging.
> 
> How would true ephemeral messaging work? We do indeed rely on clients to behave nicely since it's the clients in the end who delete the messages from their the local database, which of course they could decide not to do.
> 
> > How does the aspect of any user sent data can be deleted at any time work? Do users devices constantly check some shared key to see if a revocation has occurred? Or, does the participating parties send some type of updated state saying please no longer show this message?
> 
> Clients notify the sender when they have read the ephemeral message via a status update. The ephemeral message itself contains the date when it expires, which again needs to be respected by the clients.
> 
> They way I look ephemeral messages is as an automatic chat history deletion for groups/chats in which you trust everyone. It's a tool a group can agree to use in order to minimize the amount of data left on the devices.
> 
> It's not about sending a message to stranger and have guarantees that it will be destroyed in all circumstances.

to your knowledge - has there been any sizable discussion within Wire regarding functionality like the aforementioned? Any considerations to implement such?
