### ISSUE TITLE
Crash when receiving invalid message

### ISSUE THREAD

**Issue by Fi0x** [wireapp/wire-ios#4737]
## Checklist (please check before submitting)

* [x] I checked the existing issues, and the issue was not reported before.

## The problem

I'm developing a desktop client in java and tried to send a message. When receiving the message on my iPhone 8 the Wire app crashed. Receiving the same message on the webclient on my PC gives me a 204 error. (The message might not have a valid format)

**Edit: I just found out that the android version has a similar problem. It doesn't crash, but stops receiving messages. (Just in case you want to inform the android developers)**

## Environment

* Wire version that exhibits the issue: 3.70(4438)
* Last Wire version that did not exhibit the issue (if applicable): not sure
* iOS version used to run Wire: 14.2
* iOS device type: iPhone 8
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): Wi-Fi
* Exact date, time and timezone (only for the crash issues): 25.11.2020 14:41 UTC+1

## Details

Send a message using [this](https://github.com/Fi0x/SysAdmin/tree/v0.1-iosError) version of our client

## Screenshots
![image](https://user-images.githubusercontent.com/58072122/100235792-21adbc80-2f2d-11eb-9789-c932181b7c30.png)

**Comment by typfel** [comment]
Thanks for the report, we'll look into this.

**Comment by typfel** [comment]
Could you provide some instructions on how to run you client?

**Comment by Fi0x** [comment]
I'm very sorry for the late response.
I only ran that specific version of our client only in Intellij and I'm pretty sure that the jar you could compile won't run due to some write permissions.

**To start the client in Intellij** you need to
1. Download the three .dll files and the Waz-Messages.jar file I provided on [this release](https://github.com/Fi0x/SysAdmin/releases/tag/v0.1-iosError).
2. Clone the repository in Intellij _(The maven installation won't work on this version, so please ignore the errors)_
3. Make sure that in the project structure menu as project SDK a java version 13 is selected _(Others might work as well, but I tested it on version 13)_
4. While you are in the project structure menu of intellij, go to libraries and add the Waz-Messages.jar as a java library
5. Add the 3 .dll files to the bin folder of the SDK you selected in the previous step
6. Add a run configuration that executes the Main class in the project (There is only one)
7. Run the configuration

**Comment by typfel** [comment]
Thanks for the instructions! Unfortunately I don't have access to a windows machine, maybe you could connect to me on Wire (@jacobp) and then we could have a debug session to reproduce and solve this issue.

**Comment by Fi0x** [comment]
> Thanks for the instructions! Unfortunately I don't have access to a windows machine, maybe you could connect to me on Wire (@torleif) and then we could have a debug session to reproduce and solve this issue.

I sent you a contact request

**Comment by typfel** [comment]
> > Thanks for the instructions! Unfortunately I don't have access to a windows machine, maybe you could connect to me on Wire (@torleif) and then we could have a debug session to reproduce and solve this issue.
> 
> I sent you a contact request

Accepted. Sorry for the delay again (Christmas holidays).

**Comment by typfel** [comment]
Fixed by https://github.com/wireapp/wire-ios-request-strategy/pull/269
