### ISSUE TITLE
Cannot install back-up of my conversation on any phone even the one it was saved from

### ISSUE THREAD

**Issue by coffeeshopper** [wireapp/wire-ios#4755]
I cannot load any version of a back up onto my phone. It refuses and says "Something went wrong. Your history could not be restored."

I have tried installing this on my other phone, which is also an iphone 8 with same version. I also would be fine using an older version of the wire ios but I don't know what version I should try. The issues happened after November 17. 
[current.log](https://github.com/wireapp/wire-ios/files/5644330/current.log)
[previous.log](https://github.com/wireapp/wire-ios/files/5644331/previous.log)

I have also attached the two different keys for this phone. I am not sure why I have different keys when it is the same phone, but I don't know how to change them. 

## Environment

* Wire version that exhibits the issue: 3.71 (4441)
* Last Wire version that did not exhibit the issue (if applicable):
* iOS version used to run Wire: 14.2
* iOS device type: iphone 8
* Mobile network type (EDGE/LTE/Wi-Fi/Offline):wifi
* Exact date, time and timezone (only for the crash issues): Started on 11/17/20
happens all the time.

**Comment by typfel** [comment]
Thanks for the report. Do remember on which version of Wire you created the backup?

**Comment by coffeeshopper** [comment]
It was a version installed in the around January 2020. Not sure of the version. I would gladly revert to an older version if you could tell me where I can download them.

**Comment by coffeeshopper** [comment]
I think it was 3.49 but not sure.

**Comment by typfel** [comment]
I attempted to reproduce this and noticed that we show same error message if you attempt to restore a backup created by another account than the one you are currently signed in as. Which account a backup file belongs to can be determined by the handle which is included in the filename.

Is that the case?

**Comment by coffeeshopper** [comment]
No. Same account. Never changed. That said, every time I log in, I get a new identifier code for the phone even though it has not changed.

**Comment by typfel** [comment]
We found a bug with backup imports which might also be the issue that you are having https://github.com/wireapp/wire-ios-data-model/pull/1117

This will probably be public in about 2 weeks.

**Comment by coffeeshopper** [comment]
So what do I do? Just wait? How do I know when to try to load it again?

**Comment by typfel** [comment]
I'm afraid waiting is the only option. I'll post an update it here when the fix is out.

**Comment by coffeeshopper** [comment]
Thanks. I appreciate it.

**Comment by typfel** [comment]
@coffeeshopper the fix was released in the latest update yesterday (3.74).
