### ISSUE TITLE
Dark Mode on iOS hides White on White text entry, disabling signs up.

### ISSUE THREAD

**Issue by brycampbell** [wireapp/wire-ios#4921]
## Checklist (please check before submitting)

* [x] I checked the existing issues, and the issue was not reported before.

## The problem

When signing up for an account using the telephone number, if a user is using an iOS device and has dark mode enabled, the text entry is white on white and is not visible. In order to enter any text, dark mode must be disabled.

## Environment

* Wire version that exhibits the issue: Latest
* Last Wire version that did not exhibit the issue (if applicable):
* iOS version used to run Wire: iOS 14.4
* iOS device type: iPhone
* Mobile network type (EDGE/LTE/Wi-Fi/Offline):
* Exact date, time and timezone (only for the crash issues): 

## Details

Turn the text a colour that is visible in Dark Mode, or ask the user to disable dark mode.

## Calling Debug logs (only for calling issues)

0. You have to have the iOS email client set up.
1. Reproduce the issue.
2. Go to Settings -> Advanced -> Calling Debug Report.
3. Send the report.

## Screenshots

Please attach screenshots if you consider them as helpful to understand/reproduce the issue.

**Comment by johnxnguyen** [comment]
Hi @brycampbell , thanks for opening the issue. Unfortunately I have not been able to reproduce this bug. Could you please do a screen recording to demonstrate the steps you've taken?
