### ISSUE TITLE
New message in archived conversation doesn't activate the conversation

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#494]
How to reproduce:

* archive a conversation
* receive a new message from a recipient from that conversation
* the new message icon is displayed on the app icon on the dashboard
* the conversation is still archived (but with a new message symbok at its side)

Expected: the conversation is bring back from archive

**Comment by KoalaBoomka** [comment]
@IpsmLorem, good afternoon!
Did you mute that conversation? If so, it shouldn't appear in the list

**Comment by IpsmLorem** [comment]
Not it's not muted

**Comment by KoalaBoomka** [comment]
Is it one-to-one or group conversation?

**Comment by IpsmLorem** [comment]
Yes one to one.

**Comment by KoalaBoomka** [comment]
What are the sender and receiver clients?

**Comment by IpsmLorem** [comment]
iOS / Android

**Comment by KoalaBoomka** [comment]
With given steps and additional information it continues working on my test devices.

**Comment by marcoconti83** [comment]
Question: does it appear if you kill and restart the app?

**Comment by IpsmLorem** [comment]
For now it's works again. I think it's a specific context and will be hard to reproduce

**Comment by jenskasemets** [comment]
Possible cause for this issue was fixed on last release.
