### ISSUE TITLE
"Wire pasted from..." alert continuously appearing on start screen

### ISSUE THREAD

**Issue by nicorsm** [wireapp/wire-ios#4958]
## Checklist (please check before submitting)

* [x] I checked the existing issues, and the issue was not reported before.

## The problem

Hey everyone,
what's up? I hope you're well, staying safe and healthy! 😊

Yesterday I have downloaded the Wire iOS app on my iPad. On the very first screen I noticed the app was continuously looking at the pasteboard, causing the system dialog (_"Wire pasted from Safari"_) to appear and disappear on screen.

After logging into the app, the dialog stopped appearing.

## Environment

* Wire version that exhibits the issue: 3.76 (4484)
* Last Wire version that did not exhibit the issue (if applicable):
* iOS version used to run Wire: 14.4
* iOS device type: iPad Air 4
* Mobile network type (EDGE/LTE/Wi-Fi/Offline): Wi-Fi

## Details

1. Copy some text from other apps (Safari, Notes, etc.)
2. Open Wire without being logged in
3. The _"Wire pasted from Safari"_ dialog appears and disappears continuously, even on the login screen.
 
## Screenshots

![ezgif-4-c41cbbc1d254](https://user-images.githubusercontent.com/2906234/108592810-13c2d880-7370-11eb-91ca-4e8face0a695.gif)

**Comment by billypchan** [comment]
Hi @nicorsm, thanks for your report. I can reproduce this issue and I will create a ticket.
