### ISSUE TITLE
Wire crashes on fresh install on iphone 7

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-ios#499]
A friend of mine who's on an iphone 7 just installed wire. Every time he tries to send me a message (I'm the only contact he has) the app crashes on him. I asked for a debug log but I'm not sure if he'll send me one. This is about all the information I have. Hopefully it's easy to reproduce with the latest version.

**Comment by typfel** [comment]
Hi,  Thanks for reporting this!

We are currently trying to fix & reproduce this and it would help us if you could tell us more about the circumstances of the crash.

* What kind of message
* Was this the first message in conversation?
* Does the message remain as unsent after the crash?

**Comment by someoneEsle** [comment]
- text message (he can't ping either though)
- I sent him texts, which he can read, but he can't reply. he's never successfully sent any message
- yes, message remains unsent after the crash

**Comment by someoneEsle** [comment]
My friend literally just send me a message like 30 seconds ago. He reinstalled and it works fine now.

**Comment by someoneEsle** [comment]
Just for reference, there seems to be more people affected: https://twitter.com/interpaul/status/812095195185430528
Their issue also disappeared after reinstalling.

**Comment by marcoconti83** [comment]
Thanks, we will try to gather more details and try to reproduce.

**Comment by dwt** [comment]
I just encountered the same thing on my fathers iPhone 5s (iOS 10.2)

**Comment by dwt** [comment]
Reinstallation was a working workaround

**Comment by Calefornia** [comment]
iPhone SE, just installed Wire like 20 minutes ago.

crashes repeatedly while trying to chat with Anna, the experimental chat bot. I have no other contacts and can't send anything to her. audio, text, picture, or any type of message will crash.

**Comment by teller** [comment]
There's a new version out on AppStore now that might fix the issue.

**Comment by typfel** [comment]
This is issue is confirmed to be fixed in the latest version.
