### ISSUE TITLE
Messages not being fetched while app is closed

### ISSUE THREAD

**Issue by moonejon** [wireapp/wire-ios#5073]
This happens on both my iPad and iPhone. I'll have the app closed and occasionally, I just won't get notified at all about messages. Then, when I open the app, it just sits and fetches all the messages that have occurred since I last opened the app.

**Comment by johnxnguyen** [comment]
Hi @rocbr , could you elaborate on the issue you're experiencing? Are you not receiving notifications for new messages while the app is in the background?

**Comment by rocbr** [comment]
When the app is not open it is not sending push notifications that there are new messages. It takes hours to push me alerts that there are new messages.

I have already reviewed all background refresh settings. All other similar apps are working perfectly except Wire.

I have to open the app if I want to check for new messages. 

I'm using iPhone 11, IOS 15.5

**Comment by rocbr** [comment]
@johnxnguyen 
I have two connected devices: phone and web.
App version: 3.103

**Comment by rocbr** [comment]
@johnxnguyen 

Looks better now after reinstalling the app.

Thanks

**Comment by johnxnguyen** [comment]
@rocbr glad to hear it. Let me know if you run into problems again with notifications!
