### ISSUE TITLE
Multiple audio problems

### ISSUE THREAD

**Issue by rbieb** [wireapp/wire-ios#522]
The ios version has some audio problems as of right now (I believe they were caused by the update that brought callkit support).

- When someone calls me, my phone no longer rings (I just see the message that someone tried to call me, after the fact)

- When I call someone, I don't hear anything (no beeping) until the call actually starts and someone starts talking to me. There is no ringing sound, and no sound to indicate that the actual call has started.

**Comment by jenskasemets** [comment]
Hi @rbieb,

Thank you for your feedback.

Just to clarify first point: do you have CallKit enabled or disabled?

2nd issue is known and there's gonna be fix in upcoming releases.

**Comment by rbieb** [comment]
Callkit is definitely enabled. Glad to hear you already have a fix for the second problem.

**Comment by jenskasemets** [comment]
@rbieb please re-test these issues with latest release 2.26 where we potentially fixed them.

**Comment by rbieb** [comment]
@jenskasemets 

All seems to work fine now, thanks!

**Comment by jenskasemets** [comment]
@rbieb thank you for the feedback and initial report! We fixed these issues on last release, good to get confirmation for it as well.
