### ISSUE TITLE
Can't import zmessaging

### ISSUE THREAD

**Issue by heyken** [wireapp/wire-ios#526]
Hey there, I've tried building the app, but It was appeared error, 
#import <zmessaging/zmessaging.h> <- file not found
probably, the errors hint at Carthage update.

iMac:Wire leesanggyu$ sh setup.sh
ℹ️  Carthage bootstrap. This might take a while...
*** Downloading AFNetworking.framework binary at "2.6.3-iOS8"
*** Downloading Cartography.framework binary at "Swift 3"
*** Downloading Classy.framework binary at "iOS 10 Fonts support"
*** Downloading CocoaLumberjack.framework binary at "Swift 3"
*** Downloading FormatterKit.framework binary at "1.8.1"
*** Downloading HockeySDK-iOS.framework binary at "4.1.3"
*** Downloading ios-snapshot-test-case.framework binary at "2.1.3-swift3"
*** Downloading libPhoneNumber-iOS.framework binary at "0.8.12"
*** Downloading ocmock.framework binary at "v3.1.3"
*** Downloading onepassword-app-extension.framework binary at "framework/1.8.2"
*** Downloading ono.framework binary at "1.3.0: Merge pull request #1 from wireapp/feature/extension-only-api"
*** Downloading PINCache.framework binary at "Extension API compatible"
*** Downloading protobuf-objc.framework binary at "1.9.12: Extension only API"
*** Downloading TSMarkdownParser.framework binary at "1.0.17"
*** Downloading TTTAttributedLabel.framework binary at "2.0.0"
*** Downloading VIMNetworking.framework binary at "v6.0.2-wire-carthage-2"
*** Downloading wire-ios-canvas.framework binary at "2.0.6: Spider-Woman VS. Vision"
*** Downloading wire-ios-link-preview.framework binary at "4.0.2: The motivating synergized mole"
*** Downloading wire-ios-system.framework binary at "16.0.7: Vahagn the spiritual earth elemental from Hückeswagen"
*** Downloading wire-ios-cryptobox.framework binary at "5.0.1: You should never handle in La Paz"
*** Downloading wire-ios-utilities.framework binary at "13.0.1: It smells like a present joke"
*** Downloading wire-ios-images.framework binary at "7.0.0: The One with Rachel's Other Sister"
*** Downloading wire-ios-protos.framework binary at "9.1.0: Please spread the rambunctious water buffalo"
*** Downloading wire-ios-transport.framework binary at "17.0.0: Arctic warbler"
*** Downloading wire-ios-data-model.framework binary at "34.1.0: What would Henriette Avram do?"
*** Downloading wire-ios-request-strategy.framework binary at "14.0.0: A giant abstracted manatee was spotted near Adelsheim"
*** Downloading wire-ios-message-strategy.framework binary at "12.0.0: deers really love eating olive oil"
*** Downloading wire-ios-sync-engine.framework binary at "62.6.0: Brake"
A shell task (/usr/bin/env unzip -qq -d /var/folders/fx/hzfz1y5s06x3zg5ykmc3x3z00000gn/T/carthage-archive.J44ld3 /Users/leesanggyu/Library/Caches/org.carthage.CarthageKit/binaries/wire-ios-sync-engine/62.6.0/2896243-zmessaging.framework.zip) failed with exit code 9:
[/Users/leesanggyu/Library/Caches/org.carthage.CarthageKit/binaries/wire-ios-sync-engine/62.6.0/2896243-zmessaging.framework.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /Users/leesanggyu/Library/Caches/org.carthage.CarthageKit/binaries/wire-ios-sync-engine/62.6.0/2896243-zmessaging.framework.zip or
        /Users/leesanggyu/Library/Caches/org.carthage.CarthageKit/binaries/wire-ios-sync-engine/62.6.0/2896243-zmessaging.framework.zip.zip, and cannot find /Users/leesanggyu/Library/Caches/org.carthage.CarthageKit/binaries/wire-ios-sync-engine/62.6.0/2896243-zmessaging.framework.zip.ZIP, period.

iMac:Wire leesanggyu$

**Comment by marcoconti83** [comment]
Hi @heyken ,
thanks for checking out our code! It is indeed a problem with how dependencies are fetched using Carthage.

May I ask you to  try to wipe your global carthage cache:

`rm -fr /Users/leesanggyu/Library/Caches/org.carthage.CarthageKit/`

and your project carthage folder:

`(from the project folder) rm -fr Carthage`

and then try to run `setup.sh` again? 

It sounds like you have a corrupted zip file, however if I try to download it from GitHub again, it looks fine. Let us know if deleting the cache fixes it!

**Comment by heyken** [comment]
Well, sorry about that can't resolve issue.
I tried that command a lot of times.
my information : 

macOS Sierra : v10.12
xcode 8.1 
ruby 2.3.0p0
cocoapods-1.1.1


iMac:Wire leesanggyu$ rm -fr /Users/leesanggyu/Library/Caches/org.carthage.CarthageKit/
iMac:Wire leesanggyu$ rm -fr Carthage
iMac:Wire leesanggyu$ sh setup.sh
ℹ️  Carthage bootstrap. This might take a while...
*** Cloning AFNetworking
*** Cloning Cartography
*** Cloning Classy
*** Cloning CocoaLumberjack
*** Cloning FormatterKit
*** Cloning HockeySDK-iOS
*** Cloning PINCache
*** Cloning TSMarkdownParser
*** Cloning TTTAttributedLabel
*** Cloning VIMNetworking
*** Cloning ZipArchive
*** Cloning ios-snapshot-test-case
*** Cloning libPhoneNumber-iOS
*** Cloning ocmock
*** Cloning onepassword-app-extension
*** Cloning ono
*** Cloning protobuf-objc
*** Cloning wire-ios-canvas
*** Cloning wire-ios-system
*** Cloning wire-ios-ziphy
*** Cloning wire-ios-cryptobox
*** Cloning wire-ios-link-preview
*** Cloning wire-ios-utilities
*** Cloning wire-ios-images
*** Cloning wire-ios-transport
*** Cloning wire-ios-protos
*** Cloning wire-ios-data-model
*** Cloning wire-ios-request-strategy
*** Cloning wire-ios-message-strategy
*** Cloning wire-ios-sync-engine
*** Downloading AFNetworking.framework binary at "2.6.3-iOS8"
*** Downloading Cartography.framework binary at "Swift 3"
*** Downloading Classy.framework binary at "iOS 10 Fonts support"
*** Downloading CocoaLumberjack.framework binary at "Swift 3"
*** Downloading FormatterKit.framework binary at "1.8.1"
*** Downloading HockeySDK-iOS.framework binary at "4.1.3"
*** Downloading ios-snapshot-test-case.framework binary at "2.1.3-swift3"
*** Downloading libPhoneNumber-iOS.framework binary at "0.8.12"
*** Downloading ocmock.framework binary at "v3.1.3"
*** Downloading onepassword-app-extension.framework binary at "framework/1.8.2"
*** Downloading ono.framework binary at "1.3.0: Merge pull request #1 from wireapp/feature/extension-only-api"
*** Downloading PINCache.framework binary at "Extension API compatible"
*** Downloading protobuf-objc.framework binary at "1.9.12: Extension only API"
*** Downloading TSMarkdownParser.framework binary at "1.0.17"
*** Downloading TTTAttributedLabel.framework binary at "2.0.0"
*** Downloading VIMNetworking.framework binary at "v6.0.2-wire-carthage-2"
*** Downloading wire-ios-canvas.framework binary at "2.0.6: Spider-Woman VS. Vision"
*** Downloading wire-ios-link-preview.framework binary at "4.0.2: The motivating synergized mole"
*** Downloading wire-ios-system.framework binary at "16.0.7: Vahagn the spiritual earth elemental from Hückeswagen"
*** Downloading wire-ios-cryptobox.framework binary at "5.0.1: You should never handle in La Paz"
*** Downloading wire-ios-utilities.framework binary at "13.0.1: It smells like a present joke"
*** Downloading wire-ios-images.framework binary at "7.0.0: The One with Rachel's Other Sister"
*** Downloading wire-ios-protos.framework binary at "9.1.0: Please spread the rambunctious water buffalo"
*** Downloading wire-ios-transport.framework binary at "17.0.0: Arctic warbler"
*** Downloading wire-ios-data-model.framework binary at "34.1.0: What would Henriette Avram do?"
*** Downloading wire-ios-request-strategy.framework binary at "14.0.0: A giant abstracted manatee was spotted near Adelsheim"
*** Downloading wire-ios-message-strategy.framework binary at "12.0.2: sheeps really love eating oyster"
*** Downloading wire-ios-sync-engine.framework binary at "62.6.3: Oelsnitz Erzgeb."
*** Downloading wire-ios-ziphy.framework binary at "6.0.0: From Brazzaville to Rosario"
*** Downloading ZipArchive.framework binary at "1.6.1-swift3"
*** xcodebuild output can be found in /var/folders/fx/hzfz1y5s06x3zg5ykmc3x3z00000gn/T/carthage-xcodebuild.wfPHWJ.log

ℹ️  Check that bundler is installed... (requires SUDO)
Password:
Fetching: bundler-1.13.7.gem (100%)
Successfully installed bundler-1.13.7
Parsing documentation for bundler-1.13.7
Installing ri documentation for bundler-1.13.7
Done installing documentation for bundler after 5 seconds
1 gem installed

ℹ️  Pod install. This might take a while...
Fetching gem metadata from https://rubygems.org/...............
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Installing i18n 0.7.0
Installing json 1.8.1 with native extensions
Installing minitest 5.9.0
Installing thread_safe 0.3.5
Installing public_suffix 2.0.4
Installing mini_portile2 2.1.0
Installing pkg-config 1.1.7
Installing claide 1.0.0
Installing colored 1.2
Installing nap 1.0.0
Installing open4 1.3.4
Installing fuzzy_match 2.0.4
Installing cocoapods-deintegrate 1.0.0
Installing cocoapods-downloader 1.0.0
Installing cocoapods-search 1.0.0
Installing cocoapods-stats 1.0.0
Installing netrc 0.7.8
Installing cocoapods-try 1.0.0
Installing escape 0.0.4
Installing fourflusher 0.3.2
Installing molinillo 0.4.5
Installing multipart-post 2.0.0
Installing git 1.3.0
Installing kramdown 1.13.0
Installing unicode-display_width 1.1.1
Installing mustache 0.99.8
Installing rouge 1.11.1
Using bundler 1.13.7
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/leesanggyu/.gem/ruby/2.3.0/gems/json-1.8.1/ext/json/ext/generator
/Users/leesanggyu/.rvm/rubies/ruby-2.3.0/bin/ruby -r ./siteconf20161230-26082-qjor0v.rb extconf.rb
creating Makefile

current directory: /Users/leesanggyu/.gem/ruby/2.3.0/gems/json-1.8.1/ext/json/ext/generator
make "DESTDIR=" clean

current directory: /Users/leesanggyu/.gem/ruby/2.3.0/gems/json-1.8.1/ext/json/ext/generator
make "DESTDIR="
compiling generator.c
In file included from generator.c:1:
./../fbuffer/fbuffer.h:175:47: error: too few arguments provided to function-like macro invocation
    VALUE result = rb_str_new(FBUFFER_PAIR(fb));
                                              ^
/Users/leesanggyu/.rvm/rubies/ruby-2.3.0/include/ruby-2.3.0/ruby/intern.h:797:9: note: macro 'rb_str_new' defined here
#define rb_str_new(str, len) __extension__ (    \
        ^
In file included from generator.c:1:
./../fbuffer/fbuffer.h:175:11: warning: incompatible pointer to integer conversion initializing 'VALUE' (aka 'unsigned long') with an expression of type 'VALUE (const char *, long)' (aka
'unsigned long (const char *, long)') [-Wint-conversion]
    VALUE result = rb_str_new(FBUFFER_PAIR(fb));
          ^        ~~~~~~~~~~
1 warning and 1 error generated.
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/leesanggyu/.gem/ruby/2.3.0/gems/json-1.8.1 for inspection.
Results logged to /Users/leesanggyu/.gem/ruby/2.3.0/extensions/x86_64-darwin-15/2.3.0/json-1.8.1/gem_make.out

An error occurred while installing json (1.8.1), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.1'` succeeds before bundling.

ℹ️  Downloading AVS library...
ℹ️  Using wire open source iOS binary
ℹ️  Downloading https://api.github.com/repos/wireapp/avs-ios-binaries/releases/tags/2.9.71...
Redirected to https://api.github.com/repos/wireapp/avs-ios-binaries/releases/assets/2857461...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100  184M  100  184M    0     0  1362k      0  0:02:18  0:02:18 --:--:-- 2051k
✅  Done downloading!
ℹ️  Installing in ./Libraries/wire-avs-ios...
x include/
x include/AVSAudioEffect.h
x include/AVSCapturer.h
x include/AVSFlowManager.h
x include/AVSMedia.h
x include/AVSMediaManager+Client.h
x include/AVSMediaManager.h
x include/AVSMediaProtocols.h
x include/AVSVideoConverter.h
x include/AVSVideoPreview.h
x include/AVSVideoView.h
x include/AVSVideoViewOSX.h
x lib/
x lib/libavsobjc.a
x lib/libavsobjc.stripped.a
x version.buildinfo
✅  Done

ℹ️  Downloading additional assets...
No access to assets

✅  Wire project was set up, you can now open Wire-iOS.xcworkspace
iMac:Wire leesanggyu$ carthage update --platform iOS --no-use-binaries
*** Fetching ocmock
*** Fetching wire-ios-canvas
*** Fetching FormatterKit
*** Fetching wire-ios-sync-engine
*** Fetching TSMarkdownParser
*** Fetching wire-ios-ziphy
*** Fetching wire-ios-message-strategy
*** Fetching wire-ios-request-strategy
*** Fetching wire-ios-data-model
*** Fetching wire-ios-link-preview
*** Fetching wire-ios-transport
*** Fetching PINCache
*** Fetching wire-ios-protos
*** Fetching wire-ios-cryptobox
*** Fetching ono
*** Fetching wire-ios-utilities
*** Fetching wire-ios-images
*** Fetching protobuf-objc
*** Fetching wire-ios-system
*** Checking out AFNetworking at "2.6.3-iOS8"
*** Checking out Cartography at "z0.6.1-swift3"
*** Checking out Classy at "v0.2.6"
*** Checking out CocoaLumberjack at "2.4.0-swift3"
*** Checking out FormatterKit at "1.8.1"
*** Checking out HockeySDK-iOS at "4.1.3"
*** Checking out ios-snapshot-test-case at "2.1.3-swift3"
*** Checking out libPhoneNumber-iOS at "0.8.12"
*** Checking out ocmock at "v3.1.3"
*** Checking out onepassword-app-extension at "framework/1.8.2"
*** Checking out ono at "1.3.0"
*** Checking out PINCache at "2.3.1"
*** Checking out protobuf-objc at "1.9.12"
*** Checking out TSMarkdownParser at "1.0.17"
*** Checking out TTTAttributedLabel at "2.0.0"
*** Checking out VIMNetworking at "v6.0.2-wire-carthage-2"
*** Checking out wire-ios-canvas at "2.0.6"
*** Checking out wire-ios-link-preview at "4.0.2"
*** Checking out wire-ios-system at "16.0.7"
*** Checking out wire-ios-cryptobox at "5.0.1"
*** Checking out wire-ios-utilities at "13.0.1"
*** Checking out wire-ios-images at "7.0.0"
*** Checking out wire-ios-protos at "9.1.0"
*** Checking out wire-ios-transport at "17.0.0"
*** Checking out wire-ios-data-model at "34.1.0"
*** Checking out wire-ios-request-strategy at "14.0.0"
*** Checking out wire-ios-message-strategy at "12.0.2"
*** Checking out wire-ios-sync-engine at "62.6.3"
*** Checking out wire-ios-ziphy at "6.0.0"
*** Checking out ZipArchive at "1.6.1-swift3"
*** xcodebuild output can be found in /var/folders/fx/hzfz1y5s06x3zg5ykmc3x3z00000gn/T/carthage-xcodebuild.Vasdel.log
*** Building scheme "AFNetworking" in AFNetworking.xcworkspace
*** Building scheme "Cartography-iOS" in Cartography.xcodeproj
*** Building scheme "Classy" in Classy.xcworkspace
*** Building scheme "CocoaLumberjackSwift-iOS" in Lumberjack.xcworkspace
*** Building scheme "CocoaLumberjack" in Lumberjack.xcworkspace
*** Building scheme "CocoaLumberjack-iOS" in Lumberjack.xcworkspace
*** Building scheme "CocoaLumberjackSwift" in Lumberjack.xcworkspace
*** Building scheme "FormatterKit-iOS" in FormatterKit.xcworkspace
*** Building scheme "HockeySDK Framework" in HockeySDK.xcodeproj
*** Building scheme "FBSnapshotTestCase iOS" in FBSnapshotTestCase.xcworkspace
*** Building scheme "libPhoneNumber-iOS" in libPhoneNumber.xcodeproj
*** Building scheme "OCMock iOS" in OCMock.xcodeproj
*** Building scheme "OnePasswordExtension" in 1Password Extension Demos.xcworkspace
*** Building scheme "Ono iOS" in Ono.xcworkspace
*** Building scheme "iOS" in PINCache.xcodeproj
*** Building scheme "ProtocolBuffers Framework" in ProtocolBuffers.xcodeproj
*** Building scheme "MarkdownParser" in TSMarkdownParser.xcodeproj
*** Building scheme "TTTAttributedLabel" in TTTAttributedLabel.xcodeproj
*** Building scheme "VIMNetworkingFramework" in VIMNetworking.xcworkspace
** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution Check\ Pods\ Manifest.lock /Users/leesanggyu/Library/Developer/Xcode/DerivedData/VIMNetworking-amgizonjraqaiuduimqsnhasabdq/Build/Intermediates/VIMNetworkingFramework.build/Release-iphoneos/VIMNetworkingFramework.build/Script-BBCA0BBBE8FFE626CD6221D5.sh
(1 failure)
/Users/leesanggyu/Documents/Project/Wire/Carthage/Checkouts/Classy/Classy/Additions/UIColor+CASAdditions.m:18:38: warning: format specifies type 'unsigned long *' but the argument has type 'NSUInteger *' (aka 'unsigned int *') [-Wformat]
/Users/leesanggyu/Documents/Project/Wire/Carthage/Checkouts/Classy/Classy/Additions/UIColor+CASAdditions.m:18:38: warning: format specifies type 'unsigned long *' but the argument has type 'NSUInteger *' (aka 'unsigned int *') [-Wformat]
<module-includes>:1:1: warning: umbrella header for module 'CocoaLumberjack' does not include header '/Users/leesanggyu/Documents/Project/Wire/Carthage/Checkouts/CocoaLumberjack/Classes/CLI/CLIColor.h'
<module-includes>:1:1: warning: umbrella header for module 'CocoaLumberjack' does not include header '/Users/leesanggyu/Documents/Project/Wire/Carthage/Checkouts/CocoaLumberjack/Classes/CLI/CLIColor.h'
<module-includes>:1:1: warning: umbrella header for module 'CocoaLumberjack' does not include header '/Users/leesanggyu/Documents/Project/Wire/Carthage/Checkouts/CocoaLumberjack/Classes/CLI/CLIColor.h'
<module-includes>:1:1: warning: umbrella header for module 'CocoaLumberjack' does not include header '/Users/leesanggyu/Documents/Project/Wire/Carthage/Checkouts/CocoaLumberjack/Classes/CLI/CLIColor.h'
warning: /var/folders/g9/mxr37xcs33g38q39zkf76xb00000gp/C/com.apple.DeveloperTools/7.2-7C68/Xcode/SharedPrecompiledHeaders/OCMockLib-Prefix-aguhwhqcwfsriffwgjqlwwuendhr/OCMockLib-Prefix.pch.pch: No such file or directory
warning: /var/folders/g9/mxr37xcs33g38q39zkf76xb00000gp/C/com.apple.DeveloperTools/7.2-7C68/Xcode/SharedPrecompiledHeaders/OCMockLib-Prefix-efhbsnkhmearojbasgiitukrjnoo/OCMockLib-Prefix.pch.pch: No such file or directory
warning: /var/folders/g9/mxr37xcs33g38q39zkf76xb00000gp/C/com.apple.DeveloperTools/7.2-7C68/Xcode/SharedPrecompiledHeaders/OCMockLib-Prefix-efeadqrgtnidxwbadwtohuxejrdb/OCMockLib-Prefix.pch.pch: No such file or directory
warning: /var/folders/g9/mxr37xcs33g38q39zkf76xb00000gp/C/com.apple.DeveloperTools/7.2-7C68/Xcode/SharedPrecompiledHeaders/OCMockLib-Prefix-bxixbexkmoooetbthjtvimnkelbz/OCMockLib-Prefix.pch.pch: No such file or directory
/Users/leesanggyu/Documents/Project/Wire/Carthage/Checkouts/ono/Source/ONOXMLDocument.m:395:23: warning: 'enumerateElementsWithCSS:block:' is deprecated [-Wdeprecated-declarations]
/Users/leesanggyu/Documents/Project/Wire/Carthage/Checkouts/ono/Source/ONOXMLDocument.m:395:23: warning: 'enumerateElementsWithCSS:block:' is deprecated [-Wdeprecated-declarations]
ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.1.sdk/Developer/Library/Frameworks'
ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.1.sdk/Developer/Library/Frameworks'
/Users/leesanggyu/Documents/Project/Wire/Carthage/Checkouts/ono/Source/ONOXMLDocument.m:395:23: warning: 'enumerateElementsWithCSS:block:' is deprecated [-Wdeprecated-declarations]
/Users/leesanggyu/Documents/Project/Wire/Carthage/Checkouts/ono/Source/ONOXMLDocument.m:395:23: warning: 'enumerateElementsWithCSS:block:' is deprecated [-Wdeprecated-declarations]
ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk/Developer/Library/Frameworks'
ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk/Developer/Library/Frameworks'
ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.1.sdk/Developer/Library/Frameworks'
ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.1.sdk/Developer/Library/Frameworks'
ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk/Developer/Library/Frameworks'
ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk/Developer/Library/Frameworks'
/Users/leesanggyu/Documents/Project/Wire/Carthage/Checkouts/TTTAttributedLabel/TTTAttributedLabel/TTTAttributedLabel.m:176:22: warning: 'kCTParagraphStyleSpecifierLineSpacing' is deprecated: first deprecated in iOS 6.0 [-Wdeprecated-declarations]
/Users/leesanggyu/Documents/Project/Wire/Carthage/Checkouts/TTTAttributedLabel/TTTAttributedLabel/TTTAttributedLabel.m:176:22: warning: 'kCTParagraphStyleSpecifierLineSpacing' is deprecated: first deprecated in iOS 6.0 [-Wdeprecated-declarations]
/Users/leesanggyu/Documents/Project/Wire/Carthage/Checkouts/TTTAttributedLabel/TTTAttributedLabel/TTTAttributedLabel.m:176:22: warning: 'kCTParagraphStyleSpecifierLineSpacing' is deprecated: first deprecated in iOS 6.0 [-Wdeprecated-declarations]
/Users/leesanggyu/Documents/Project/Wire/Carthage/Checkouts/TTTAttributedLabel/TTTAttributedLabel/TTTAttributedLabel.m:176:22: warning: 'kCTParagraphStyleSpecifierLineSpacing' is deprecated: first deprecated in iOS 6.0 [-Wdeprecated-declarations]
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/leesanggyu/Documents/Project/Wire/Carthage/Checkouts/VIMNetworking/VIMNetworking.xcworkspace -scheme VIMNetworkingFramework -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution Check\ Pods\ Manifest.lock /Users/leesanggyu/Library/Developer/Xcode/DerivedData/VIMNetworking-amgizonjraqaiuduimqsnhasabdq/Build/Intermediates/VIMNetworkingFramework.build/Release-iphoneos/VIMNetworkingFramework.build/Script-BBCA0BBBE8FFE626CD6221D5.sh
(1 failure)

**Comment by marcoconti83** [comment]
Thanks for the logs.
From your logs, it seems that the carthage step in`setup.sh` is not working fine, no need to manually run carthage. The problem is now with Cocoapods though. 

Can you please try to manually run `pod install` in the project folder? If that works, give `setup.sh` another try.

**Comment by heyken** [comment]
Thanks a lot, I resolved issue. 
It couldn't parse ruby script , because of json version.
It might uninstall all, and reinstall.

Thanks again. 
Hope great Wire!

**Comment by jenskasemets** [comment]
Thank you for the feedback
