### ISSUE TITLE
Group-Video-Call

### ISSUE THREAD

**Issue by ThisIsBenny** [wireapp/wire-ios#529]
Please add a Video-Function to Groups, which make it possible to video-chat with multiple friends.
Example-Apps:
* Houseparty-App
* Facebook-Messenger

I hope it is possible with WebRTC (or the Protocol which Wire use for Calls).

**Comment by jspittka** [comment]
Thanks for the feature request. This is on our roadmap but no specific estimate on timing yet.

**Comment by njfox** [comment]
Has there been any progress on this issue? We are considering switching to Wire but we rely heavily on group video chats. It would be nice to know if this feature was going to be available in the foreseeable future or if we need to look at other options for now.

**Comment by helenakos** [comment]
@njfox It's planned for the forseeable future, specifically Q4 of 2017. 

If you would like to give more of your feedback directly and join our pilot tester program please drop me your email at helena@wire.com and I'll get you in touch with my colleague from the business development team.

**Comment by feimgrk** [comment]
I see that you are working on paid plans (teams) and you have announced that group video calls will be implemented. Been waiting for this since beginning of 2016 so I'm really happy you are implementing this.
I was wondering whether group video calls will be available for free users as well or if it will be exclusively for team users?

**Comment by helenakos** [comment]
@feimgrk Hi, in the first phase group video calls will be available for team users. It is not excluded that it may be also for free users, but can not promise it at this stage.

**Comment by cyb3rwr3ck** [comment]
@helenakos 
Is there any update on this? If group video calling is enabled in teams we would for sure replace webex with it - so its a killer-feature for us.

**Comment by mikeger** [comment]
We are looking into implementing this feature, please stay tuned.

**Comment by marcoconti83** [comment]
Group video calling is now available for teams.

**Comment by dkout** [comment]
Is there any update on whether this will be offered for free-tier users as well?
