### ISSUE TITLE
setup.sh is failing

### ISSUE THREAD

**Issue by suntzu** [wireapp/wire-ios#53]
setup.sh is failing. Here are the logs

> Bundle complete! 2 Gemfile dependencies, 27 gems now installed.
> Use `bundle show [gemname]` to see where a bundled gem is installed.
> Analyzing dependencies
> Pre-downloading: `AFNetworking` from `https://github.com/wireapp/AFNetworking`, tag `2.6.3`
> Pre-downloading: `ARCollectionViewMasonryLayout` from `https://github.com/wireapp/ARCollectionViewMasonryLayout`, tag `2.3.0`
> Pre-downloading: `FLAnimatedImage` from `https://github.com/wireapp/FLAnimatedImage`, tag `1.0.12`
> Pre-downloading: `MTAnimation` from `https://github.com/wireapp/MTAnimation`, tag `1.2.2-wire`
> Pre-downloading: `NSObject-ObjectMap` from `https://github.com/wireapp/NSObject-ObjectMap`, tag `v2.3.1`
> Pre-downloading: `PureLayout` from `https://github.com/wireapp/PureLayout`, tag `v3.0.0`
> Pre-downloading: `RBBAnimation` from `https://github.com/wireapp/RBBAnimation`, commit `7dd8d9a3cf610be5f7c1e4459692d555d70704c7`
> Pre-downloading: `SCSiriWaveformView` from `https://github.com/wireapp/SCSiriWaveformView`, tag `v1.0.3`
> Pre-downloading: `VIMNetworking` from `https://github.com/wireapp/VIMNetworking`, tag `6.0.0`
> [!] Unable to find a specification for `GoogleAPIClient/YouTube (= 1.0.4)`
>

**Comment by marcoconti83** [comment]
Hi @suntzu , thanks for reporting this issue.
As mentioned in the [README](https://github.com/wireapp/wire-ios/blob/develop/README.md):
>  If you did not have CocoaPods version >= 1.0.0 installed before this script will fail and you will need to run bundle exec pod repo update manually before running it again.

Just run `bundle exec pod repo update` to fix it.
