### ISSUE TITLE
Wire Startup Failure

### ISSUE THREAD

**Issue by MadEgg** [wireapp/wire-ios#530]
Sorry to have no technical details whatsoever, but one of my contacts that uses Wire on a iPhone 6 Plus occasionally has problems where the Wire splash screen shows for a couple of seconds and then the phone goes back to the home screen. Hitting the Wire button again shows the exact same behaviour. Usually a couple of hours later, Wire manages to start again.

Probably too vague to do anything with this report, but I'm reporting in nonetheless, just to make sure it's known to the developers.

**Comment by jenskasemets** [comment]
Hi @MadEgg ,

This sounds like a crash on app start, we are really interested to get these crash logs.

Please see a guide how to send these crash reports to us in such case:
https://support.wire.com/hc/en-us/articles/207717735-How-can-I-report-a-crash-on-an-iOS-device-

If user have sending crash logs enabled, we can also receive these crash logs automatically. For that would be useful to launch app multiple times (crash log is sent only if it crashed on previous launch) and then send us information with:
— Exact timestamp when crash occured
— Device model
— iOS version
— App version

**Comment by MadEgg** [comment]
I'm pretty sure her technical knowledge is insufficient to extract the crash log using iTunes the way described on the link you provided, but I have asked her to enable the diagnostic & usage reporting in Wire if she hasn't already, so I'm hoping that if it happens again you should get the crash logs.

To be sure, this is not about the "Error reporting" part in Wire settings where you can send a report manually? It seems to me that that feature is mainly for debugging problems with phone calls, right?

**Comment by jenskasemets** [comment]
Correct, "Error reporting" is mostly for calling issue.

**Comment by MadEgg** [comment]
Thanks. I just got confirmation that this setting was already enabled, so you should have received crash reports about this issue recently. I'm going to assume that this will be fixed at some point, so I'll close this issue because it doesn't contain any additional information about the cause of the problem.

**Comment by jenskasemets** [comment]
@MadEgg 
Please provide the information what I was listing in previous comment, without that information it's difficult to find exact crash logs

**Comment by MadEgg** [comment]
Oh sorry, I didn't realize you needed that information - aren't you investigating all reported crash logs? There's no specific need to give this one any preference over others - it happens but right now it's working again.

Time when it occurred: 27 december 2016 - 22:27 CET (around that time, no exact time unfortunately)
Model: iPhone 6 plus
iOS version: 10.0.2
Wire version: 2.25
