### ISSUE TITLE
Crashed with old conversation

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#533]
I experienced some crash:

I went to the archived discussions. Saw that one was with a yellow warning icon. 
Opened it. It was with two recipients. Saw that some timed pictures sent was never read and some was not even sent. 
I taped on retry and Wire crashed. Each timed I launched the app, it crashed. Even after removing from the active app.
Workaround: disabled network (air plane mode) and start up the app. It worked.
I Cleared all message in it and re enabled the network.

**Comment by jenskasemets** [comment]
@IpsmLorem 
Please provide:
— Exact timestamp when crash occured
— Device model
— iOS version
— App version

**Comment by basine** [comment]
@IpsmLorem Thank you for your crash report, can you please check if you were still a member of the conversation, or if you previously had left / were removed from the conversation?

**Comment by IpsmLorem** [comment]
* Timestamps (UTC): 2017-01-02 08:05:02.23+1, 08:05:10.65+1, 08:05:21.98+1, 05:05:33.86+1, 08:06:14.40+1, 08:08:46.45+1 (and more)
* Device: iPhone5,2
* iOS: 10.2
* Wire 2.26

**Comment by jenskasemets** [comment]
This crash was fixed in release 2.29
