### ISSUE TITLE
Archived conversation doesn't show up when receiving new message

### ISSUE THREAD

**Issue by IpsmLorem** [wireapp/wire-ios#534]
Received a message for an archived conversation.

Expected: conversation unarchived
What's happend: New message didn't trigger unarchiving conversation

**Comment by jenskasemets** [comment]
Is this conversation muted?

**Comment by IpsmLorem** [comment]
Not muted.

**Comment by IpsmLorem** [comment]
I've seen other unsynched archived state issue. Like conversation archived on web app and not on iOS. When trying to archive it on iOS, it displays the choice to remove it from archive.

**Comment by jenskasemets** [comment]
This bug should be now fixed in release 2.33
