### ISSUE TITLE
New issues with callkit

### ISSUE THREAD

**Issue by rbieb** [wireapp/wire-ios#554]
Just noticed the following problems:
- Calls on speakerphone are very quiet, even when on max volume
- The ringing tone starts too late, not right when actually initiating the call
- The "call accepted" tone does not seem to work as intended

To further explain the issues, this was a call I just had:
I started the call, but did not hear the ringing. I left the app, and still heard nothing. After a few seconds I reopened the app, heard the ringing and found out that the call had actually been going on for 6 seconds already. The ringing stopped about half a second later.

**Comment by jenskasemets** [comment]
Hi @rbieb ,

These issues should be now fixed with the calling fixes introduced in latest releases. I'm closing this ticket now, feel free to comment (reopen) if you still have the issues mentioned above.
