### ISSUE TITLE
Wire 3.99 from App Store is still built with Xcode 12.4?

### ISSUE THREAD

**Issue by lucifer662607004** [wireapp/wire-ios#5658]
I downloaded Wire IPA bundle from App Store with IPATool and I accidentally found the bundle is built with Xcode 12.4. AFAIK Xcode 12 is already forbidden in App Store. 

I'm just wondering why the release is built with Xcode 12 while the README file specifically indicates Xcode 13.1.

Thanks

**Comment by johnxnguyen** [comment]
Hey @lucifer662607004 , building with Xcode 13 requires that we utilize the notification service extension using standard APNS push tokens. This work has only been in internal testing but is slated for the next release (3.100) will be built with Xcode 13.1. I hope this answers your question!

**Comment by lucifer662607004** [comment]
> Hey @lucifer662607004 , building with Xcode 13 requires that we utilize the notification service extension using standard APNS push tokens. This work has only been in internal testing but is slated for the next release (3.100) will be built with Xcode 13.1. I hope this answers your question!

Thank you so much for the explanation!
