### ISSUE TITLE
Screen turns off while recording

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-ios#566]
iPhone 5, iOS 10.2
- tap mic to record a message, and start recording
- record for >1 minute (or whatever your screen's timeout is)
- wire stops recording and the audio message is lost

p.s.: friend who reported this bug complains that he can't tap-and-hold the mic icon like on the android version

**Comment by KoalaBoomka** [comment]
hello @someoneEsle! 
Thanks for contacting us, we appreciate your report.
And we will prioritize this issue.

About the second issue what you mentioned, it works fine on the test device with keyboard up or down.

**Comment by billypchan** [comment]
This issue is fixed in the coming release. Thanks!
