### ISSUE TITLE
Module zmessaging  not found.

### ISSUE THREAD

**Issue by anappleapp** [wireapp/wire-ios#567]
Hi, 

i have the issue to run the project, i installed the pod then when i run the project i get the error say that.-Module zmessaging  not found.

Any help appreciate.
![schermata 2017-01-13 alle 10 34 11](https://cloud.githubusercontent.com/assets/11163232/21925069/13b46fd0-d97c-11e6-8029-95df0482ebd9.png)

**Comment by marcoconti83** [comment]
Hi @anappleapp , did you run the setup script? If yes, can you paste the output here?
Thanks

**Comment by anappleapp** [comment]
@marcoconti83 , 
thanks for reply, What you mean run the setup script?

**Comment by marcoconti83** [comment]
In the [README](https://github.com/wireapp/wire-ios#how-to-build-locally) you can find instructions on how to build the client.

**Comment by marcoconti83** [comment]
Closing this for now, let me know if it still doesn't work.
