### ISSUE TITLE
Opening YouTube links behavior

### ISSUE THREAD

**Issue by tschoof** [wireapp/wire-ios#569]
Hi!

I'd very much like an "Open with" option (or to be it the standard behavior) to open YouTube links in the YouTube App, since the website version is kinda quirky and doesn't feel nice.

The more I think about it, an "Open with" would be weird, since there's really no alternative app. But the "Open in YT App" banner that Safari usually shows isn't displayed in Wire either, so I think the current situation isn't ideal.

**Comment by jenskasemets** [comment]
Hi @tschoof ,

When you tap on Youtube link above the preview, it will open actually Youtube app, but only if you have it installed on your device. When you tap on play button on preview, then we show embedded player, which as you noted, is actually normal Youtube web. Sadly we can not embed Youtube app.
