### ISSUE TITLE
Request: Please make an app for the Apple Watch

### ISSUE THREAD

**Issue by rbieb** [wireapp/wire-ios#583]
Having real support for the apple watch would be great. Some features that would be nice:
- Being able to send both voice messages and transcribed messages
- Be able to start conversations with anyone of my contacts
- See message history
- Would be cool if we could set up a few predefined answers ourselves
- Be able to start a call and accept incoming calls if possible
- play received voice messages

**Comment by malicioustoker** [comment]
Any progress?

**Comment by mikeger** [comment]
This is not on our timeline in the foreseeable future, therefore I am going to close this ticket. Sorry and thanks for the suggestion!
