### ISSUE TITLE
Colours broken in dark theme

### ISSUE THREAD

**Issue by k88hudson** [wireapp/wire-ios#5964]
## The problem

Colours for various buttons and the background in edit mode appear to be broken for the dark theme: 

![IMG_6147](https://user-images.githubusercontent.com/1455535/203595106-afadf72c-4de6-4388-afa3-c5005b6d0234.jpg)

![IMG_6145](https://user-images.githubusercontent.com/1455535/203595117-e4dae304-531c-4428-a7af-c8aecc810568.jpg)

## Environment
Version 3.107
iOS 16.1 iPhone 13 mini

**Comment by agisilaos** [comment]
That issue has been fixed with #5966
