### ISSUE TITLE
Some Copyright headers not updated

### ISSUE THREAD

**Issue by stigi** [wireapp/wire-ios#6]
Just stumbled across this while browsing. You were probably intending to update those copyright headers as well: 

https://github.com/wireapp/wire-ios/search?utf8=✓&q=Zeta+Project+Germany%22&type=Code

**Comment by marcoconti83** [comment]
Thanks for reporting this, @stigi !
Fixed with https://github.com/wireapp/wire-ios/commit/dc652b10a88eadb85af5010b346c95afa29d167a
