### ISSUE TITLE
Image not received on iOS participants of a conversation

### ISSUE THREAD

**Issue by MadEgg** [wireapp/wire-ios#618]
In a conversation with 4 participants on iOS and 1 participant on Android, images sent from the Android phone are sometimes not received on the iOS devices. A dark gray loading frame appears with the alternating dots in the center to indicate loading, but it they never load.

However, besides my iPhone, I also have a Wire Desktop (for Linux) client attached to my account, and that one receives the images just fine.

This happens sometimes, not always. Sometimes the pictures are transmitted correctly. I've never seen it happen the other way around.

**Comment by jenskasemets** [comment]
Thank @MadEgg for the report,

This is known bug on Android side and will be addressed soon. I will close this ticket as there's nothing to be fixed on iOS side.

**Comment by MadEgg** [comment]
Great, thanks!

Any issue report on GitHub on wire-android about this issue? If so, which one? (because I'd like to subscribe to that one). If not, thanks for the update and we'll probably notice the fix :)

**Comment by jenskasemets** [comment]
Not on public Github, it's tracked on our internal issue tracking.
