### ISSUE TITLE
Feature Request: Open Media Collection directly by tapping on media

### ISSUE THREAD

**Issue by MadEgg** [wireapp/wire-ios#636]
The new media collection feature is very nice! However, I would really like to open the media collection browser directly when opening an image or video full screen, so that I can full-screen an image and then swipe left / right to browse the images, without manually having to open the media collection.

**Comment by mikeger** [comment]
@MadEgg implemented in https://github.com/wireapp/wire-ios/pull/651

**Comment by MadEgg** [comment]
That was quick! Awesome, thanks!
