### ISSUE TITLE
Right-to-Left languages visual bug

### ISSUE THREAD

**Issue by pyed** [wireapp/wire-ios#64]
if you start writing in a right-to-left language, your first couple of letters will be covered under the GIF icon, it looks like this:

<img width="369" alt="screen shot 2016-08-02 at 4 21 24 am" src="https://cloud.githubusercontent.com/assets/1909519/17313906/9bddad44-5868-11e6-933f-a9b22622c083.png">

it should look like this:

<img width="376" alt="screen shot 2016-08-02 at 4 21 50 am" src="https://cloud.githubusercontent.com/assets/1909519/17313912/abc6977a-5868-11e6-8c8c-bc73148610dd.png">

**Comment by mikeger** [comment]
Hey @pyed thanks for getting in touch! We really appreciate your bug report and my colleague @mykola-mokhnach would verify, confirm and prioritise the issue you reported. Please consider reporting any other issues you see with RTL/LTR switching and/or arabic language in our app.

**Comment by mikeger** [comment]
@pyed the bug should be fixed in https://github.com/wireapp/wire-ios/commit/b48fc1ced6df30ba5131a3f4268379f2f7c7f162 please confirm

**Comment by pyed** [comment]
I can confirm that the bug is fixed, thank you
