### ISSUE TITLE
Notifications while chat open

### ISSUE THREAD

**Issue by idamcevski** [wireapp/wire-ios#682]
Hi there,

Seems that even when a chat window is open in the desktop app, every new line received pops up a notification on every other device signed in. Really like Wire so far, this just looks like a fairly annoying bug.

Cheers!

**Comment by jenskasemets** [comment]
Hi @idamcevski,

Thank you for your report. Just to clarify how this works for Wire (and actually to many other similar apps) — notifications are not sent to mobile device(s) if your desktop app is active (foreground) and message is sent to a conversation which is selected (active).

Please let us know if you have any other questions. If not, then I will close this ticket.

**Comment by idamcevski** [comment]
Hi, I understand, that's how I expexcted it to work too. But, when line received in active chat window on desktop, mobile notifications are still received anyway.

Thanks for looking into the issue, hope this helps.

**Comment by jenskasemets** [comment]
Hi again,

Can you please clarify your iOS and desktop app version numbers.
What kind of message you receive?
Does the notification disappear from mobile's screen after some time?

**Comment by idamcevski** [comment]
Hi there,

Desktop app ver. 2.11.2712
iOS app ver. 2.29.2772

Notifications are for the new chat lines received and I am not sure if they expire after some time or not.
Thanks.

**Comment by jenskasemets** [comment]
@idamcevski it should be easy to confirm if message disappears from the screen or not. To understand what exactly happens, it crucial for us to know exact scenario.

Here's steps for testing:
1. Have 2 devices logged in on same account (desktop and iOS)
1. Lock screen for iOS device
1. Bring desktop app to foreground and select a conversation where you will receive messages
1. Receive messages from other side to this given conversation

As a result of these steps you should not see push notification on iOS lock screen. If they still appear, then they should almost instantly also disappear as they are marked as read on your second device (desktop) and should be removed from iOS' lock screen.
If you clients don't act like this, please let me know and we can debug it further.

**Comment by idamcevski** [comment]
I perfectly understand the scenario, just tested it once again and it seems to be working as expected.
It would seem that the updates since 12 days ago took care of the issue.

Thank you for taking the time to look into it.

**Comment by someoneEsle** [comment]
Hi @jenskasemets , could you please reopen? A friend of mine has exactly this issue. Although he has the chat open on his pc, his iphone keeps ringing with every message. Notifications do go away, but it is still annoying.
Environment:
web app 2.13.2741
iOS 10.3.1
iphone 5

**Comment by RonnieOnRails** [comment]
we do not want notifications to go away but to not display at all
