### ISSUE TITLE
In-chat camera view stuck to portrait

### ISSUE THREAD

**Issue by idamcevski** [wireapp/wire-ios#697]
The in-chat camera view returns to portrait rotation when the phone rotated in landscape position.

**Comment by victorray84** [comment]
Hi, I want to work on this issue. Can anybody assign the issue to me?

**Comment by mikeger** [comment]
@victorray84 thanks for your willingness to contribute. Feel free to ask any questions on the code structure either here or via email to mike -at- wire.com. 

`CameraKeyboardViewController` and `CameraCell` are the main responsible for the camera UI elements. `CameraCell` uses `CameraController` for rendering the camera stream.

**Comment by mikeger** [comment]
@victorray84 the bug was fixed in https://github.com/wireapp/wire-ios/pull/791

**Comment by victorray84** [comment]
@mikeger I had been on this issue from yesterday. Anyway I look into other bugs. Thanks for notifying me.

**Comment by jenskasemets** [comment]
This issue is now fixed in release 2.32
