### ISSUE TITLE
"Like" actionable notification

### ISSUE THREAD

**Issue by tschoof** [wireapp/wire-ios#722]
Hi! 
A feature I like with FB Messenger is the "thumbs up"-reply from the notification. Just as a "Yes, I've seen the message and I'm down" quick reply. The heart-like is unique to Wire, so maybe that would be an option? 
Would also soothe the pain of not having a separate Watch app.

**Comment by jenskasemets** [comment]
Hi @tschoof , this is now possible in release 2.31
