### ISSUE TITLE
Voice messages are not audible

### ISSUE THREAD

**Issue by rbieb** [wireapp/wire-ios#725]
iOS is not playing voice messages properly. This is a recent issue which has only been happening since  two or three weeks maybe.

When I play a voice message on ios the file is being played but there is just no sound. When I play the same file on the desktop version all is fine.

**Comment by anatoli26** [comment]
Could it be that it is played to the ear speaker, not the loudspeaker? It was happening to me too. Putting the phone to the ear and off a couple of times fixed the problem. But this is something that should be checked by devs, though I know other apps (e.g. Signal) on both iOS and Android happen to have this problem too, but there are also apps that don't have this problem (Telegram, wapp).

**Comment by daehn** [comment]
This issue is being addressed in https://github.com/wireapp/wire-ios/pull/769
