### ISSUE TITLE
Bug: The Description in a preview of a .ics file is not completely shown.

### ISSUE THREAD

**Issue by mat1th** [wireapp/wire-ios#741]
I send often .ics files to myself or other persons. But there is a problem with preview of this files. There is no ability to open the Description. When I send the file trough iMessage I can see the full description. So It's not an issue with the ics file. 
I've attached an ics file for testing.

**Comment by mat1th** [comment]
My device information is: iOS 10, 
Wire version: 2.29 (2772)

**Comment by jenskasemets** [comment]
Hi @mat1th ,

By "description" you mean actually "Notes" section? Can't you scroll down whole view?

**Comment by mat1th** [comment]
Yes I mean the 'Notes' section. I can not scroll down. On other apps I can click on 'Show all notes' And there is also an arrow (>) in the table field. In wire there is the button 'Show all Notes but the arrow isn't there. See the attached screenshot for more info. 

![wire](https://cloud.githubusercontent.com/assets/6486389/23230641/0bb180e6-f945-11e6-8777-3da9b6a7b6f9.png)

**Comment by mat1th** [comment]
@jenskasemets can you reproduce my issue?

**Comment by jenskasemets** [comment]
Hi @mat1th, yes we can reproduce it, but only on iOS 10.0, not with iOS 10.2

**Comment by mat1th** [comment]
@jenskasemets That's strange, I'm using iOS 10.2.1 (not a Beta) on an 5s. I've send the ics file using the Desktop (macOS) app to my phone and when I've opened it I've the same issue as described.

**Comment by jenskasemets** [comment]
If you try to scroll the view, does it scroll? We are using system preview viewer and for some reason it doesn't just look like it's scrollable for .ics files (but actually is), but is for others.

**Comment by mat1th** [comment]
@jenskasemets Yes the view is scrollable.

**Comment by mat1th** [comment]
This is a screencast of what I'm seeing
[screencast.mov.zip](https://github.com/wireapp/wire-ios/files/838394/screencast.mov.zip)

**Comment by mat1th** [comment]
This is still a issue on iOS 11.

**Comment by billypchan** [comment]
checked on iOS 12 and the issue does not occur.
