### ISSUE TITLE
support for bluetooth headsets?

### ISSUE THREAD

**Issue by jdiercks** [wireapp/wire-ios#751]
Wire on iOS doesn't appear to support bluetooth headsets for voice/video calls. Am I missing something? Thanks.

**Comment by jenskasemets** [comment]
Hi @jdiercks thank you for your report, we have some known bugs with Bluetooth headsets. I'll let you know once these are fixed so you can confirm if it starts working.

**Comment by jdiercks** [comment]
seems to be working in latest beta released today - thanks!

**Comment by jenskasemets** [comment]
Thank you @jdiercks for testing. I'm glad to hear it works now, please let us know if you still experience any issues with Bluetooth headset.
