### ISSUE TITLE
Friend on iOS can't hear forwarded audio

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-ios#754]
I'm on Android, the following happened to me:
- friend A (on Android) sent me a voice message
- I forwarded the voice message to friend B (who is on iOS)
- friend B cannot play the message (message appears to be 0 seconds long)
- I opened the desktop app on my computer, saved the voice message from A, sent it as file to B
- friend B still can't play the message

friend B has an iPhone 5SE, iOS 10.2.1

**Comment by mikeger** [comment]
Hey @someoneEsle , thanks for reporting the issue! This seems like a codec / mime type issue. Can you forward the *sample* audio message that would not work to play in this case? Please make sure not to forward any private messages here.

**Comment by someoneEsle** [comment]
github does not support this file type and won't let me upload it. It's .m4a

**Comment by avently** [comment]
@someoneElse you can archive that file in zip and then upload.

**Comment by avently** [comment]
Here is my sample from Android. This sound doesn't work on iOS. As well as others...I have the latest version from GitHub's commits built myself (on Android). 
[recording.zip](https://github.com/wireapp/wire-ios/files/863105/recording.zip)

**Comment by jenskasemets** [comment]
@someoneEsle , please can you try to reproduce this issue with latest release (2.34), we fixed one possible cause for this scenario.

**Comment by someoneEsle** [comment]
works
