### ISSUE TITLE
Select multiple photos/videos to upload

### ISSUE THREAD

**Issue by anatoli26** [wireapp/wire-ios#755]
Subj. Now I should select one-by-one every photo/video to upload. Other messengers permit to select up to 32 media items in a single operation.

**Comment by jenskasemets** [comment]
Hi @anatoli26 , thank you for your feature request. This has been already requested in #342 , closing as duplicate.

**Comment by anatoli26** [comment]
:) searched for "multiple", haven't found anything...

**Comment by jenskasemets** [comment]
Check #342 , it uses keyword "several" instead.
