### ISSUE TITLE
UI: unread messages counter on the "back to contacts list" button

### ISSUE THREAD

**Issue by anatoli26** [wireapp/wire-ios#756]
Showing unread messages counter as a badge on the "back to contacts list" button (the top left arrow when in "chat with a contact" window) would give a hint that there are unread messages with other contacts.

Now I should click this button to open the contacts list so I can see if there are new messages for some contacts.

**Comment by mikeger** [comment]
Thanks for the suggestion @anatoli26 . Our team found this idea interesting, initial implementation can be found here https://github.com/wireapp/wire-ios/pull/767

**Comment by jenskasemets** [comment]
Hi @anatoli26, thank you for this nice small improvement suggestion. It's now available in release 2.32.

**Comment by anatoli26** [comment]
Jens, thank you guys for taking into account and implementing so quickly the suggestions from the community!
