### ISSUE TITLE
No option to delete photos

### ISSUE THREAD

**Issue by anatoli26** [wireapp/wire-ios#774]
Subj. Text messages and videos can all be deleted (you get the menu with a force-touch press), but not photos. This works well on Wire-desktop, so it's a limitation of Wire-iOS UI.

Could be related to #760.

**Comment by jenskasemets** [comment]
Hi @anatoli26 , this was fixed now in release 2.31

**Comment by anatoli26** [comment]
Great, thanks! I've already seen it in the latest update, works as intended!
