### ISSUE TITLE
Mentioning someone by their username doesn't trigger anything

### ISSUE THREAD

**Issue by EgbertW** [wireapp/wire-ios#781]
A while back, usernames were introduced in Wire. I can see these usernames on my contacts, like @MadEgg or something.

I was under the impression that when I now mention someone using @ and their username, they would get an additional notification of this mentioning, but it seems that actually nothing happens. I would expect the person I'm targeting to get a message like 'MadEgg mentioned you in XXX'.

Is this supposed to work at all, or is the username just a name without a function?

**Comment by jenskasemets** [comment]
Hi @MadEgg , currently usernames are used only for identifying users and help to find new connections. Add support for mentions is on our roadmap, but no exact timeline yet.

**Comment by WildYorkies** [comment]
@jenskasemets are there plans to share the roadmap? Would keep people from making duplicate requests :smile_cat:

**Comment by jenskasemets** [comment]
@WildYorkies a lot of upcoming features are covered on Github issues for this and other repositories, feel free to go through them ;) 
Or just post your request, we’ll comment if it is duplicate, no worries.

**Comment by cardassian-tailor** [comment]
Hello, 

Just checking to see if this is coming anytime soon. This is probably the feature that I most desperately need to obtain better communication within my groups.

**Comment by cardassian-tailor** [comment]
@vytis @mikeger 
question. with mentions now here i have a concern for the search feature within conversations. 

Searching for @mikeger should return all messages sent by mike, and not return only the mention items. Has the design team thought about this any, all comments welcome.

**Comment by cardassian-tailor** [comment]
for better clarity let me give an example. I'm in a group chat with 200 people, along with Mikeger. Mike sent a very important message, but I dont recall what that message was. To search for it, I want to see all messages within this group chat that was sent by Mike. The most logical search filter, IMO, would be @mikeger  . 

If I understand correctly, this will currently return only the _mentions_ sent to Mike, and not all messages sent by Mike. 

In my opinion, there needs to be some way to differentiate between searching for mentions, and searching for all messages sent by a specific user. 

Hope that helps clarify.

**Comment by cardassian-tailor** [comment]
Mentioning now present on two other wire platforms (desktop and web) which is causing some confusion. Any plans to push the iOS development branch to production today ?

**Comment by cardassian-tailor** [comment]
https://github.com/wireapp/wire-ios/commit/65cf4c62073c0facaab8e4d71b0d045e9de3a44f

**Comment by marcoconti83** [comment]
Mentions are now available on iOS too. @cardassian-tailor I hear you suggestion about the search, could you please open a separate issue for that suggestion? 
I would like to keep this issue about mentions in the chat and as this has been rolled out to iOS now, I will close this one.
