### ISSUE TITLE
replying to a single message

### ISSUE THREAD

**Issue by kopurando** [wireapp/wire-ios#793]
Switching to Wire from Telegram, one important feature is missing -- responding to a particular message. It can be useful in busy conversations, esp. group chats. The feature is self-descriptive really, for more inspiration, please see the screenshot below.

![image](https://cloud.githubusercontent.com/assets/6130979/23586259/1b8542a0-01c4-11e7-8dce-04c8925fdd46.png)

Thanks for your hard work!

**Comment by jenskasemets** [comment]
Hi @kopurando , thank you for your feedback. This feature has been already requested in #428
