### ISSUE TITLE
Pasted gifs do not animate in conversation

### ISSUE THREAD

**Issue by kyle-fox** [wireapp/wire-ios#836]
From what I recall, this started happening after 2.31. 

If you use the Giphy picker in the app, the gifs animate as expected, but pasting from the Giphy app or any other source shows the animation in the preview pane, before sending, but results in a static image of the gif's first frame in the conversation.

**Comment by kyle-fox** [comment]
Reopening - the issue seems to be back, still in 2.33.

**Comment by Riite** [comment]
The ssue also seems to affect _some_ gifs added with the Giphy picker. Confirmed on iPad/iPhone with iOS 10.3.1, Wire version 2.33. The same gifs also seem to load very slowly, if at all (screenshot attached).
![img_3435](https://cloud.githubusercontent.com/assets/17384536/25039482/757072b4-210c-11e7-9cf2-ea6bfaa7dfd2.jpg)

**Comment by AndreaVEH** [comment]
The chosen gif from Giphy picker still doesn't animate in the conversation.

Version 2.41(2874), iOS 10.3.3

**Comment by Lkopo** [comment]
Still an issue. It's pretty annoying that many GIFs are not sent correctly.

**Comment by billypchan** [comment]
This issue is fixed in wireapp/wire-ios-images#30 and the fixed will be included in coming release. Thanks!

**Comment by billypchan** [comment]
fix included in v3.40

**Comment by kyle-fox** [comment]
@billypchan Pasting works! I assume the GIPHY search will work as well. 👍 However, sending the same gifs through the share extension still sends as a static image, but that's probably worthy of a separate issue

**Comment by billypchan** [comment]
@kyle-fox thanks for the report, we are looking at the issue.
