### ISSUE TITLE
Tint of the input text field failed to toggle state

### ISSUE THREAD

**Issue by AndreaVEH** [wireapp/wire-ios#839]
Once entering the edit mode, the input text field and function bar below change their tints to brown-like color. But after leaving the edit mode, whether submitting or cancelling the change, the tints of the input text field and function bar still keep brown-like, don't toggle to the normal state.

Version 2.32 (2795)

**Comment by MadEgg** [comment]
I was about to report the same issue.

Addition: leaving the conversation to go to the conversation list, and then going back to the same conversation does not switch the color back, but switching to another conversation does switch the color back. Even when you go back to the original conversation where you edit a message.

**Comment by jenskasemets** [comment]
This bug is now fixed in release 2.33
