### ISSUE TITLE
push notifications are duplicated

### ISSUE THREAD

**Issue by ilyasubkhankulov** [wireapp/wire-ios#880]
For group chat rooms, push notifications work well but are duplicated / re-sent hours or days after the initial message.

Wire Version 2.32
iOS version: 10.2.1

may also happen with 1-1 chats but i don't use wire for that as much and haven't seen it.

**Comment by jenskasemets** [comment]
Hi @ilyasubkhankulov , thank you for the report.

This is first time we hear about such issue, would like to get more information when and how it happens.

Could you please try to reproduce it and then write down exact steps (who, when, from which device and in which order did what). And if possible, send some example screenshots about this issue to me directly (@jens).

**Comment by ilyasubkhankulov** [comment]
below i've added 5 screenshots of push notifications i received. the messages that i assume these notifications correspond to have already been read.
its hard to tell from the screenshot but there are about 15-25 notifications that all came in at the same time.

![img_4742](https://cloud.githubusercontent.com/assets/6537686/24832691/30e13f3a-1c83-11e7-93a7-0104790cf506.PNG)
![img_4745](https://cloud.githubusercontent.com/assets/6537686/24832690/30e127ac-1c83-11e7-945d-67720d9a63c1.PNG)
![img_4746](https://cloud.githubusercontent.com/assets/6537686/24832694/30e530b8-1c83-11e7-8ae4-bb6e42e285d5.PNG)
![img_4744](https://cloud.githubusercontent.com/assets/6537686/24832692/30e24c4a-1c83-11e7-93a2-a94de6f24bb9.PNG)
![img_4743](https://cloud.githubusercontent.com/assets/6537686/24832693/30e432d0-1c83-11e7-96e7-ce3daecd3bbc.PNG)

**Comment by malicioustoker** [comment]
This can probably be closed - not an issue anymore.

**Comment by mikeger** [comment]
This should not be happening any more.
