### ISSUE TITLE
Wire-Swift.h  not found

### ISSUE THREAD

**Issue by lycaste** [wireapp/wire-ios#9]
I git clone the project from  https://github.com/wireapp/wire-ios ,then i run ./setup.sh.
but i cannt build the project ,because " Wire-Swift.h"  not found
xcode version:7.3
cocopods and carthage is the lastest version

**Comment by lycaste** [comment]
it is too strange. xcode can recognize the header file now.
but  another error:
ld: file is universal (5 slices) but does not contain a(n) x86_64 slice: 
/Users/yh/wire-avs-ios/lib/libavsobjc.a file
'/Users/yh/wire-ios/Libraries/wire-avs-ios/lib/libavsobjc.' for architecture x86_64

**Comment by mikeger** [comment]
Hey @lycaste! Thanks for reporting the issue. I suggest that it can happen that the build process was interrupted by accident while `tar` was unpacking the avs library. Please try to remove `Libraries` folder in the root directory (`rm -rf wire-ios/Libraries`) and run `./setup.sh` script again.

**Comment by lycaste** [comment]
sorry to trouble you...its ok now ... @~@
