### ISSUE TITLE
wget is a needed to build the app on macOS

### ISSUE THREAD

**Issue by anuhanovic** [wireapp/wire-ios#904]
Please update the README.MD to include wget as dependency. (brew install wget)
(Or update the shell script to use curl instead of wget)
Thanks!

    export arch=arm64
    export variant=normal
    /bin/sh -c /Users/baseline/Library/Caches/org.carthage.CarthageKit/DerivedData/wire-ios-cryptobox/8.0.2/Build/Intermediates/Cryptobox.build/Release-iphoneos/Cryptobox-ios.build/Script-0928E2621BA078750057232E.sh
/Users/baseline/Library/Caches/org.carthage.CarthageKit/DerivedData/wire-ios-cryptobox/8.0.2/Build/Intermediates/Cryptobox.build/Release-iphoneos/Cryptobox-ios.build/Script-0928E2621BA078750057232E.sh: line 4: hash: wget: not found
Command /bin/sh failed with exit code 1

** BUILD FAILED **

The following build commands failed:
	PhaseScriptExecution Check\ for\ dependencies\  /Users/baseline/Library/Caches/org.carthage.CarthageKit/DerivedData/wire-ios-cryptobox/8.0.2/Build/Intermediates/Cryptobox.build/Release-iphoneos/Cryptobox-ios.build/Script-0928E2621BA078750057232E.sh
(1 failure)
baselinsMacBook:~ baseline$

**Comment by marcoconti83** [comment]
Hi @anuhanovic , thanks for pointing this out!
We added it to the list of requirements, see https://github.com/wireapp/wire-ios/commit/484935dbe652d724b8121293a62528554adf8ce1
