### ISSUE TITLE
Build fails on latest Xcode

### ISSUE THREAD

**Issue by anuhanovic** [wireapp/wire-ios#909]
Dear Devs,
I'm just guessing the source of the problem here, but I'm willing to work with you to figure this out.
What I think is that after Carthage fails to use binary the compilation fails because it's still using $PODS_ROOT variable instead of the replacement $SRCROOT.
Obviously, when I run 'pod install' as asked, it runs fine but error stays the same.
Here are the errors and the log.

Carthage bootstrap doesn't install most binaries due to "version mismatch" (which Carthage should allow for backwards compatibility, but that's another issue/bug):
```
*** Skipped installing Cartography.framework binary due to the error:
	"Incompatible Swift version - framework was built with 3.0.2 and the local version is 3.1."


*** Building scheme "VIMNetworkingFramework" in VIMNetworking.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/baseline/Desktop/2017/github/wire-ios/Carthage/Checkouts/VIMNetworking/VIMNetworking.xcworkspace -scheme VIMNetworkingFramework -configuration Release -derivedDataPath /Users/baseline/Library/Caches/org.carthage.CarthageKit/DerivedData/VIMNetworking/v6.0.2-wire-swift3.0.2 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/wy/hy23j0d94s95gdwy2s1gdw380000gn/T/carthage-xcodebuild.GNM6gT.log
```

and here's the tail of that log file:

```
PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock /Users/baseline/Library/Caches/org.carthage.CarthageKit/DerivedData/VIMNetworking/v6.0.2-wire-swift3.0.2/Build/Intermediates/VIMNetworkingFramework.build/Release-iphoneos/VIMNetworkingFramework.build/Script-BBCA0BBBE8FFE626CD6221D5.sh
    cd /Users/baseline/Desktop/2017/github/wire-ios/Carthage/Checkouts/VIMNetworking/VIMNetworkingFramework
    /bin/sh -c /Users/baseline/Library/Caches/org.carthage.CarthageKit/DerivedData/VIMNetworking/v6.0.2-wire-swift3.0.2/Build/Intermediates/VIMNetworkingFramework.build/Release-iphoneos/VIMNetworkingFramework.build/Script-BBCA0BBBE8FFE626CD6221D5.sh
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock /Users/baseline/Library/Caches/org.carthage.CarthageKit/DerivedData/VIMNetworking/v6.0.2-wire-swift3.0.2/Build/Intermediates/VIMNetworkingFramework.build/Release-iphoneos/VIMNetworkingFramework.build/Script-BBCA0BBBE8FFE626CD6221D5.sh
(1 failure)

```
Thank you!

**Comment by mat1th** [comment]
They are working on it see https://github.com/wireapp/wire-ios/issues/899

**Comment by marcoconti83** [comment]
Hi @anuhanovic ,
thanks for reaching out. We are currently in the process of migrating to Swift 3.1 (Xcode 8.3). Some dependency frameworks are already ported, but we still have a couple to go. We think we will be done by tomorrow, and that would fix your build issue. 
We will keep you posted on the progress!

**Comment by anuhanovic** [comment]
Matthias and Marco, 
I saw #899, but respectfully I think what might happen is binary builds will be matched up to Swift 3.1, and my build will succeed until next time things are out of sync and it going to skip binaries and tries to compile. I think the root problem needs to be addressed (aka $PODS_ROOT).
Thanks!

**Comment by marcoconti83** [comment]
@anuhanovic we are looking into it, thanks for the suggestion!

**Comment by vytis** [comment]
@anuhanovic we have made most of the migration (few warnings still left) and it should compile fine with Xcode 8.3. Could you check now? Just to be sure remove `Carthage` folder before running the setup script.

**Comment by anuhanovic** [comment]
Thank you all. After I deleted the entire wire-ios local directory, and re-git-cloned it, the error went away. Now I can open Xcode and it fails to compile on the first line of:
wire-ios/WireExtensionComponents/Views/UserImageView.h
Saying WireDataModel not found.
Any ideas?
Would you be interested in setting up a CI solution?
Thanks.

**Comment by typfel** [comment]
"WireDataModel not found" sounds like the dependencies are missing. Did you run the setup script successfully after re-cloning the repo?

**Comment by anuhanovic** [comment]
Yes. No errors.

On Apr 7, 2017 3:39 AM, "Jacob Persson" <notifications@github.com> wrote:

"WireDataModel not found" sounds like the dependencies are missing. Did you
run the setup script successfully after re-cloning the repo?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/wireapp/wire-ios/issues/909#issuecomment-292465034>,
or mute
the thread

**Comment by marcoconti83** [comment]
@anuhanovic, we would need to check which version of the framework your `setup` is picking up.

Could you please:
- go to the checkout folder
- `rm -fr Carthage/`
- `git pull`
- `./setup.sh`
- copy-paste here the output of the setup script?

**Comment by anuhanovic** [comment]
Thanks for investigating. I'm happy to help.
When I open Xcode after running setup.sh, initially it gives me a bunch of warning about wire-ios/Pods directory missing, then when I try running it I get the initial error.
Thanks.

baselinsMacBook:wire-ios baseline$ ./setup.sh
ℹ️  Carthage bootstrap. This might take a while...
*** Downloading AFNetworking.framework binary at "2.6.3-iOS8"
*** Downloading avs-ios-binaries.framework binary at "Version 3.3.93"
*** Downloading Cartography.framework binary at "Swift 3.1"
*** Downloading Classy.framework binary at "Swift 3.0.2"
*** Downloading CocoaLumberjack.framework binary at "Xcode 8.3, Swift 3.1"
*** Downloading FLAnimatedImage.framework binary at "1.0.12-wire"
*** Downloading FormatterKit.framework binary at "Swift 3.0.2"
*** Downloading HockeySDK-iOS.framework binary at "Swift 3.0.2"
*** Downloading ios-snapshot-test-case.framework binary at "Swift 3.1"
*** Downloading libPhoneNumber-iOS.framework binary at "Swift 3.1"
*** Downloading ocmock.framework binary at "Swift 3.0.2"
*** Downloading onepassword-app-extension.framework binary at "Swift 3.0.2"
*** Downloading ono.framework binary at "Swift 3.1"
*** Downloading PINCache.framework binary at "Swift 3.1"
*** Downloading protobuf-objc.framework binary at "1.9.13"
*** Downloading TSMarkdownParser.framework binary at "Swift 3.0.2"
*** Downloading TTTAttributedLabel.framework binary at "Swift 3.0.2"
*** Downloading VIMNetworking.framework binary at "Swift 3.0.2"
*** Downloading wire-ios-canvas.framework binary at "3.0.0: Zatara VS. Perun"
*** Downloading wire-ios-link-preview.framework binary at "5.0.0: The dynamic high level mouse"
*** Downloading wire-ios-protos.framework binary at "11.0.0: Please carry the flaky bat"
*** Downloading wire-ios-system.framework binary at "17.0.0: Clytia the cold grimlock from Frohburg"
*** Downloading wire-ios-cryptobox.framework binary at "9.0.0: You should never help in Taiyuan"
*** Downloading wire-ios-utilities.framework binary at "16.0.0: It smells like a thirsty permission"
*** Downloading wire-ios-images.framework binary at "9.0.0: The One with the Flashback"
*** Downloading wire-ios-transport.framework binary at "19.0.0: Okinawa rail"
*** Downloading wire-ios-data-model.framework binary at "51.0.0: What would Danese Cooper do?"
*** Downloading wire-ios-request-strategy.framework binary at "32.0.0: A giant delicious crab was spotted near Esslingen am Neckar"
*** Downloading wire-ios-message-strategy.framework binary at "32.0.1: water buffalos really love eating tomato"
*** Downloading wire-ios-share-engine.framework binary at "26.0.0: I'd like a cooing flour tortillas and mustard seed burger without dill, please"
*** Downloading wire-ios-sync-engine.framework binary at "80.0.0: Vöhrenbach"
*** Downloading wire-ios-ziphy.framework binary at "6.3.0: From Bishkek to Yangzhou"
*** Downloading ZipArchive.framework binary at "Swift 3.1"
*** xcodebuild output can be found in /var/folders/wy/hy23j0d94s95gdwy2s1gdw380000gn/T/carthage-xcodebuild.vW9Qdr.log

ℹ️  Downloading AVS library...
ℹ️  No custom AVS binary specified

ℹ️  Check that bundler is installed... (requires SUDO)

ℹ️  Pod install. This might take a while...
Fetching gem metadata from https://rubygems.org/.............
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
nokogiri-1.7.0.1 requires ruby version >= 2.1.0, which is incompatible with the current version, ruby 2.0.0p648

ℹ️  Downloading additional assets...
No access to assets

✅  Wire project was set up, you can now open Wire-iOS.xcworkspace
baselinsMacBook:wire-ios baseline$

**Comment by marcoconti83** [comment]
Great, thanks for following up! It seems that now the issue with Carthage (and `WireDataModel`) should be resolved, but there's a problem at a later stage.
It seems that you are running a version of ruby that is not supported. On our [README](https://github.com/wireapp/wire-ios/blob/develop/README.md) we suggest Ruby 2.2.5. 
From the logs you posted, it looks like you are running Ruby 2.0.0. 
If updating is an option for you, try that.

**Comment by mikeger** [comment]
Hey @anuhanovic ! Do you still observe the issue after updating the Ruby?

**Comment by jenskasemets** [comment]
I will close this ticket for now.
@anuhanovic , please let us know if you still have issues and then we can reopen this ticket.

**Comment by hprobotic** [comment]
Hi guys
Please reopen this ticket
I have problem when run ./setup.sh
Can't build native extension norkori

**Comment by mikeger** [comment]
Hey @hprobotic ! The nokogiri compilation is a known issue on Ruby: https://stackoverflow.com/questions/24251494/nokogiri-gem-installation-error

I would suggest to solve the problem with installing a different ruby version or by just installing cocoapods and carthage manually and doing 

```
pod install
carthage bootstrap --platform ios
```
manually, too.

Hope this helps!

**Comment by hprobotic** [comment]
Thanks @mikeger 
I resolved this problem when remove 
`gem 'second_curtain', '~> 0.2'` from gemfile. Thanks a lot

**Comment by SV8** [comment]
Assets not found.

./Scripts/download-assets.sh
No access to assets

And I did check repos under https://github.com/wireapp. No repo named "wire-ios-build-assets" out there.
