### ISSUE TITLE
Option to have dark theme turn on at sunset, and turn off at sunrise

### ISSUE THREAD

**Issue by balupton** [wireapp/wire-ios#920]
This is how I anticipated the setting to work, was surprised when it didn't.

**Comment by wangkesen** [comment]
Like with sunset/sunrise right? I think that would be awesome as well. ^ _ ^

**Comment by RosemaryOrchard** [comment]
Many apps (e.g. Drafts, OmniFocus, Tweetbot) change automatically based on screen brightness - this solution works very well for me and would potentially be another implementation method.

**Comment by billypchan** [comment]
We are working on integrating iOS 13 appearance feature. Thanks for the long waiting!
