### ISSUE TITLE
Send button does not autocorrect last word

### ISSUE THREAD

**Issue by taylorzane** [wireapp/wire-ios#938]
Pressing the send button should confirm the last suggested autocorrect, just as "Return" or "Space" does.

This behavior is present in the iOS Messages app, so I'd imagine most people would expect the same behavior in the Wire iOS app.

I can reproduce this behavior on an 
  - iPhone 6 (10.3.2) running Wire 2.33 (2811)
  - iPhone 7 Plus (10.2.1) running Wire 2.33 (2811)

**Comment by vorobievalex** [comment]
Not reproducible with the latest version of Wire at iPhone 7 and iPad and iOS 10.3.1 or 11.0.1.
Send button or Cmd+Enter sends text with the last suggested autocorrect.

**Comment by taylorzane** [comment]
I can confirm on iPhone X iOS 11.2 (15C114) that this is resolved. This must have been resolved in a commit and not mentioned, or perhaps within the operating system itself.

Closing.
