### ISSUE TITLE
Outdated version bug

### ISSUE THREAD

**Issue by bry48** [wireapp/wire-ios#977]
Seemingly wire on IOS does not currently have an update out, the most recent version being 2.34. Although I'm on the current version wire still says my version is outdated and i cant see some messages as wire thinks my version is outdated.

**Comment by jenskasemets** [comment]
Hi @bry48 , when you updated to latest version?

We started to show this message yesterday to users not on latest version, might be that in some cases it's shown also for users who just updated and script showing this message haven't got information about update yet.

Please force quit Wire app (double tap on device home button, swipe up on app selector), wait few minutes before relaunching application and let us know if you see that message again.

**Comment by bry48** [comment]
It seems to have stopped after a couple days, thanks for the help.

**Comment by jenskasemets** [comment]
We found reason for this issue and fixed it now. I'm closing this ticket, please add a comment if happens again.
