### ISSUE TITLE
Some updates on issue #621

### ISSUE THREAD

**Issue by AndreaVEH** [wireapp/wire-ios#978]
Several days ago I updated some problems on the closed issue [#621](https://github.com/wireapp/wire-ios/issues/621), but it seemed the issue still closed. I think maybe the issue is too old, so that there's no notification alarm for it.

**Comment by jenskasemets** [comment]
Closing as duplicate issue.

**Comment by daehn** [comment]
Hello @AndreaVEH I responded to #621 and will close this ticket here instead.
