### ISSUE TITLE
Saving images from collection browser closes it

### ISSUE THREAD

**Issue by EgbertW** [wireapp/wire-ios#990]
When you save an image from the collection browser, this closes the collection browser. This is quite annoying when you are trying to save a series of images this way - you have to open the collection browser again for every image, and you have to swipe past all the images you have already saved to continue.

It would be great if the collection browser would stay open when saving the image / media.

**Comment by mikeger** [comment]
Hey @MadEgg ! Thanks for the suggestion, we would schedule the fix for the issue.
