### ISSUE TITLE
Custom Device Name

### ISSUE THREAD

**Issue by BennySamir** [wireapp/wire-ios#994]
Hello,

It would be nice to have the possability to change the device namen. This make it easier to See which "Wire for Windows" is the private PC and which the work PC.

Thanks

**Comment by mikeger** [comment]
Hey @BennySamir ! Thanks for the suggestion, the function to rename the devices could be useful indeed. Can you repost it to https://github.com/wireapp/wire/issues where we gather non platform-specific suggestions?
